In [201]:
import pandas as pd
import numpy as np
import re
import ast
import json
from collections import Counter

In [202]:
import warnings
warnings.filterwarnings('ignore')

# Beko

In [203]:
path1 = "../web-scraping-data/data/raw/beko/beko_urun_ozellik.csv"
path2 = "../web-scraping-data/data/raw/beko/beko_urun_ozellik_2.csv"
path3 = "../web-scraping-data/data/raw/beko/beko_urun_ozellik3.csv"

df1 = pd.read_csv(path1)
df2 = pd.read_csv(path2)
df3 = pd.read_csv(path3)

print(f"df1 shape: {df1.shape}")
print(f"df2 shape: {df2.shape}")
print(f"df3 shape: {df3.shape}")

df1 shape: (1184, 10)
df2 shape: (126, 10)
df3 shape: (651, 10)

In [204]:
# beko_turleri.csv dosyasını kat_tur.csv olarak kaydet
beko_turleri_path = "../web-scraping-data/data/raw/beko/beko_turleri.csv"
kat_tur_df = pd.read_csv(beko_turleri_path)

print(kat_tur_df.head())

     kategori          urun_adi
0  Beyaz Eşya         Buzdolabı
1  Beyaz Eşya   Derin Dondurucu
2  Beyaz Eşya  Çamaşır Makinesi
3  Beyaz Eşya  Bulaşık Makinesi
4  Beyaz Eşya  Kurutma Makinesi

In [205]:
# birleştir ve indeksleri sıfırla, aynı ürünü tekilleştir
df = pd.concat([df1, df2, df3], ignore_index=True, sort=False)
df.drop_duplicates(subset='urun_linki', inplace=True)
df.reset_index(drop=True, inplace=True)

print(f"merged df shape: {df.shape}")
df.sample(5, random_state=15)

merged df shape: (1301, 10)

,urun_linki,urun_adi,fiyat,teknik_ozellikler,enerji_sinifi,favori_sayisi,yorum_sayisi,renk_secenekleri,urun_ozellikleri,yorumlar
94,https://www.beko.com.tr/12-kg-camasir-makinesi...,CMX 12140 12 Kg Çamaşır Makinesi,39.959 TL,"{""Kapasite"": ""12 kg"", ""Maksimum Sıkma Devri"": ...",A,120.00,NaN,[],"{""Kapasite"": ""12 kg"", ""Maksimum Sıkma Devri"": ...","[{""yildiz"": ""5"", ""baslik"": ""F/P ÜRÜNÜ"", ""sahip..."
482,https://www.beko.com.tr/kulaklik/jr310bt-bluet...,JR310BT Bluetooth ÇocukKulaklığı OEMavi Kulaklık,2.190 TL,"{""Kulaklık Tipi"": ""Kablosuz kulak üstü kulaklı...",NaN,0.00,NaN,[],"{""Kulaklık Tipi"": ""Kablosuz kulak üstü kulaklı...",[]
295,https://www.beko.com.tr/fitfry-buhar-destekli-...,BFC 450 A FitFry Buhar Destekli Fırın,59.405 TL,"{""Motor Teknolojisi"": ""AeroPerfect"", ""Homewhiz...",A+,5.00,NaN,[],"{""Motor Teknolojisi"": ""AeroPerfect"", ""Homewhiz...",[]
434,https://www.beko.com.tr/hoparlor/band-bt-hopar...,Grundig Band BT Hoparlör Yeşil Hoparlör,2.099 TL,"{""Ses Çıkış Gücü"": ""2x 2,5 W"", ""Çalma Süresi"":...",NaN,2.00,NaN,[],"{""Ses Çıkış Gücü"": ""2x 2,5 W"", ""Çalma Süresi"":...",[]
1015,https://www.beko.com.tr/kucuk-ev-aletleri-yede...,Bıçak Grubu Blender Küçük Ev Aletleri Yedek Pa...,475 TL,{},NaN,1.00,1,[],{},[]

In [206]:
df = df.drop_duplicates().reset_index(drop=True)
df = df.drop_duplicates(subset='urun_linki', keep='first').reset_index(drop=True)
print(f"df shape after removing duplicates: {df.shape}")

df shape after removing duplicates: (1301, 10)

In [207]:
df_yedek = df.copy()

In [208]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   urun_linki         1301 non-null   str
 1   urun_adi           1301 non-null   str
 2   fiyat              1301 non-null   str
 3   teknik_ozellikler  1301 non-null   str
 4   enerji_sinifi      270 non-null    object
 5   favori_sayisi      1237 non-null   float64
 6   yorum_sayisi       126 non-null    object
 7   renk_secenekleri   1301 non-null   str
 8   urun_ozellikleri   1301 non-null   str
 9   yorumlar           1301 non-null   str
dtypes: float64(1), object(2), str(7)
memory usage: 1.2+ MB

In [209]:
# 1. Kategori Sütununu Çıkarma
# URL'i '/' işaretine göre böldüğümüzde liste şu şekilde olur: 
# ['https:', '', 'www.beko.com.tr', 'kategori_adi', 'urun_adi']
# Bize 3. indeksteki 'kategori_adi' lazım.
df['Product_Group'] = df['urun_linki'].str.split('/').str[3]

# 2. Tire (-) İşaretlerini Temizleme
# Tireleri boşluk karakteri ile değiştiriyoruz
df['Product_Group'] = df['Product_Group'].str.replace('-', ' ', regex=False)

# 3. Metin Formatını Düzeltme
# Her kelimenin ilk harfini büyük yapmak için (Örn: "oyun konsolu" -> "Oyun Konsolu")
df['Product_Group'] = df['Product_Group'].str.title()

# Sonucu kontrol etmek için
print(df[['urun_linki', 'Product_Group']].sample(5, random_state=15))

                                             urun_linki  \
94    https://www.beko.com.tr/12-kg-camasir-makinesi...
482   https://www.beko.com.tr/kulaklik/jr310bt-bluet...
295   https://www.beko.com.tr/fitfry-buhar-destekli-...
434   https://www.beko.com.tr/hoparlor/band-bt-hopar...
1015  https://www.beko.com.tr/kucuk-ev-aletleri-yede...

                                      Product_Group
94                           12 Kg Camasir Makinesi
482                                        Kulaklik
295                     Fitfry Buhar Destekli Firin
434                                        Hoparlor
1015  Kucuk Ev Aletleri Yedek Parca Ve Aksesuarlari

In [210]:
unique_values = pd.Series(df["Product_Group"].dropna().unique()).sort_values()
print(unique_values.to_string(index=False))

                       10 Kg Camasir Makinesi
                       10 Kg Kurutma Makinesi
                       11 Kg Camasir Makinesi
                       11 Kg Kurutma Makinesi
                       12 Kg Camasir Makinesi
                       12 Kg Kurutma Makinesi
                    3 Bolmeli Derin Dondurucu
                 3 Programli Bulasik Makinesi
                    4 Bolmeli Derin Dondurucu
                 4 Programli Bulasik Makinesi
                    5 Bolmeli Derin Dondurucu
                 5 Programli Bulasik Makinesi
                    6 Bolmeli Derin Dondurucu
                 6 Programli Bulasik Makinesi
                    7 Bolmeli Derin Dondurucu
                   8 Bolmeli Derin Dondurucu
                        8 Kg Camasir Makinesi
                        8 Kg Kurutma Makinesi
                        9 Kg Camasir Makinesi
                        9 Kg Kurutma Makinesi
                           Ada Tipi Davlumbaz
                                   Agiz Bakim
                     Airfryer Az Yagli Fritoz
                              Akilli Bileklik
                         Akilli Mutfak Robotu
                                  Akilli Saat
                                  Aksesuarlar
                    Android Telefon Modelleri
                           Ankastre Buzdolabi
             Ankastre Duvar Tipi Davlumbazlar
                               Ankastre Firin
                       Ankastre Mikrodalgalar
                      Ankastre Standart Firin
                   Ankastre Surgulu Aspirator
                               Arac Buzdolabi
                            Ayakli Vantilator
                                       Baskul
       Beyaz Esya Yedek Parca Ve Aksesuarlari
                      Bilgisayar Aksesuarlari
                                      Blender
                         Buhar Destekli Firin
                     Buharli Kirisik Giderici
                       Buharli Temizleyiciler
                                  Buharli Utu
                                 Buz Makinesi
        Cam Temizleme Makineleri Ve Robotlari
                             Camasir Makinesi
                                 Cay Makinesi
                    Cekmeceli Derin Dondurucu
                    Cep Telefonu Aksesuarlari
                              Cevre Birimleri
                                   Cilt Bakim
         Classic Serisi Solo Bulasik Makinesi
                          Cok Amacli Pisirici
                   Diger Telefon Aksesuarlari
                           Dijital Termosifon
                                    Dograyici
                               Domino Ocaklar
                            Dondurma Makinesi
                         Duvar Tipi Davlumbaz
                      Ekmek Kizartma Makinesi
                                   El Blender
                                 El Supurgesi
           Elite Serisi Solo Bulasik Makinesi
                  Entegre Davlumbazli Ocaklar
                            Espresso Makinesi
              Ev Ici Akilli Kamera Sistemleri
                        Filtre Kahve Makinesi
                  Fitfry Buhar Destekli Firin
                                 Fitfry Firin
                     Frozen Ve Slush Makinesi
                              Gaming Kulaklik
                      Gardirop Tipi Buzdolabi
                       Gazli Cam Tablali Ocak
            Gazli Inoks Metal Tablali Ocaklar
           Gazli Renkli Metal Tablali Ocaklar
                        Giyilebilir Teknoloji
                              Gomme Aspirator
             Hali Ve Koltuk Yikama Makineleri
             Hamur Yogurma Ve Mutfak Makinesi
                                Hava Sogutucu
                                     Hoparlor
                         Induksiyonlu Ocaklar
                             Infrared Isitici
                                    Iphone 13
                                    Iphone 14
                                    Iphone 15
                                    Iphone 16
                               Iphone 16 Plus
                                Iphone 16 Pro
                            Iphone 16 Pro Max
                                   Iphone 17
                                Iphone 17 Pro
                            Iphone 17 Pro Max
                                   Iphone Air
   Isitma Sogutma Yedek Parca Ve Aksesuarlari
                     Islak Kuru Dikey Supurge
                           Islak Kuru Supurge
                        Kablolu Dikey Supurge
                    Kahve Demleme Ekipmanlari
                                Kahve Ogutucu
                        Kapsul Kahve Makinesi
                          Kati Meyve Sikacagi
                                  Kazanli Utu
                                       Kettle
                               Kiyma Makinesi
                              Konsol Oyunlari
                            Konvektor Isitici
Kucuk Ev Aletleri Yedek Parca Ve Aksesuarlari
                                     Kulaklik
                         Kule Tipi Vantilator
                             Kurutma Makinesi
                   Kurutmali Camasir Makinesi
                                       Laptop
                          Masaustu Bilgisayar
                             Mikrodalga Firin
                                       Mikser
                               Mini Buzdolabi
                                   Mini Firin
                                        Mouse
                           Narenciye Sikacagi
                              Nem Alma Cihazi
                           No Frost Buzdolabi
                                 Ocakli Firin
                                 Oyun Konsolu
                           Oyuncu Ekipmanlari
                                Ozel Bakimlar
         Pisirici Yedek Parca Ve Aksesuarlari
                               Portatif Klima
                                    Powerbank
                       Premix Yogusmali Kombi
                                Robot Supurge
                   Saat Ve Bileklik Aksesuari
                             Sac Duzlestirici
                         Sac Kurutma Makinesi
                                   Sac Masasi
                   Sac Sakal Kesme Makineleri
                          Salon Tipi Klimalar
                  Sandik Tipi Derin Dondurucu
                               Sarj Cihazlari
                         Sarjli Dikey Supurge
                                      Semaver
                              Seramik Isitici
                                Set Ustu Ocak
                                Seyahat Utusu
                                  Split Klima
                          Standart Termosifon
                             Statik Buzdolabi
                                    Su Sebili
                                       Tablet
                Tam Ankastre Bulasik Makinesi
               Tam Otomatik Espresso Makinesi
                        Tavan Tipi Vantilator
                                       Termos
                 Tezgah Alti Bulasik Makinesi
                             Tiras Makineleri
                                Tost Makinesi
                          Toz Torbali Supurge
                                  Toz Torbasi
                         Toz Torbasiz Supurge
                          Turk Kahve Makinesi
                 Ustten Donduruculu Buzdolabi
                                   Utu Masasi
                          Uv Temizleme Cihazi
                         Vitroseramik Ocaklar
                               Yagli Radyator
               Yari Ankastre Bulasik Makinesi
              Yari Otomatik Espresso Makinesi
                       Yaslanma Karsiti Bakim
                               Yazar Kasa Pos
                        Yogurt Kefir Makinesi

In [211]:

# Türkçe karakterleri İngilizce karşılıklarına çeviren ve küçük harf yapan fonksiyon
def metin_temizle(text):
    if pd.isna(text):
        return ""
    text = str(text).lower() 
    ceviri_tablosu = str.maketrans("çğıöşü", "cgiosu")
    text = text.translate(ceviri_tablosu)
    return " ".join(text.split())

# 1. Aşama: Senin Manuel Eşleştirmelerin ve Otomatik Eşleşmelerin Sözlüğü
# Sözlük Yapısı: {'Alt Kategori (Temizlenmiş)': ('Ana Kategori', 'Orijinal Alt Kategori Adı')}
kategori_kurallari = {
    # BEYAZ EŞYA GRUBU
    'camasir makinesi': ('Beyaz Eşya', 'Çamaşır Makinesi'),
    'kurutma makinesi': ('Beyaz Eşya', 'Kurutma Makinesi'),
    'kurutmali camasir makinesi': ('Beyaz Eşya', 'Kurutmalı Çamaşır Makinesi'),
    'bulasik makinesi': ('Beyaz Eşya', 'Bulaşık Makinesi'),
    'derin dondurucu': ('Beyaz Eşya', 'Derin Dondurucu'),
    'buzdolabi': ('Beyaz Eşya', 'Buzdolabı'),
    'firin': ('Beyaz Eşya', 'Fırın'),
    'su sebili': ('Beyaz Eşya', 'Su Sebili'),
    'beyaz esya yedek parca': ('Beyaz Eşya', 'Beyaz Eşya Yedek Parça ve Aksesuarları'),
    'mikrodalga': ('Beyaz Eşya', 'Mikrodalga Fırın'), # Senin Kuralın
    'set ustu ocak': ('Beyaz Eşya', 'Set Üstü Ocak'), # Senin Kuralın
    'domino ocak': ('Beyaz Eşya', 'Set Üstü Ocak'),
    'gazli ocak': ('Beyaz Eşya', 'Set Üstü Ocak'),
    'induksiyonlu ocak': ('Beyaz Eşya', 'Set Üstü Ocak'),
    'vitroseramik ocak': ('Beyaz Eşya', 'Set Üstü Ocak'),

    # ANKASTRE GRUBU
    'ankastre bulasik': ('Ankastre', 'Ankastre Bulaşık Makineleri'), # Senin Kuralın
    'ankastre buzdolabi': ('Ankastre', 'Ankastre Buzdolabı'),
    'ankastre firin': ('Ankastre', 'Ankastre Fırın'),
    'ankastre mikrodalga': ('Ankastre', 'Ankastre Mikrodalgalar'),
    'ankastre davlumbaz': ('Ankastre', 'Ankastre Davlumbazlar'),
    'ankastre aspirator': ('Ankastre', 'Ankastre Aspiratörler'),
    'ankastre set': ('Ankastre', 'Ankastre Set'), # Senin Kuralın
    'ankastre ocak': ('Ankastre', 'Ankastre Ocak'), # Senin Kuralın
    'pisirici yedek parca': ('Ankastre', 'Pişirici Yedek Parça ve Aksesuarları'),
    'ada tipi davlumbaz': ('Ankastre', 'Ankastre Davlumbazlar'),
    'duvar tipi davlumbaz': ('Ankastre', 'Ankastre Davlumbazlar'),
    'gomme aspirator': ('Ankastre', 'Ankastre Aspiratörler'),

    # ELEKTRONİK GRUBU
    'cep telefonu': ('Elektronik', 'Cep Telefonu'), # Senin Kuralın
    'iphone': ('Elektronik', 'Cep Telefonu'),
    'android': ('Elektronik', 'Cep Telefonu'),
    'giyilebilir': ('Elektronik', 'Giyilebilir Teknoloji'), # Senin Kuralın
    'akilli saat': ('Elektronik', 'Giyilebilir Teknoloji'),
    'akilli bileklik': ('Elektronik', 'Giyilebilir Teknoloji'),
    'bilgisayar': ('Elektronik', 'Bilgisayar'), # Senin Kuralın
    'laptop': ('Elektronik', 'Bilgisayar'),
    'tablet': ('Elektronik', 'Bilgisayar'),
    'ses goruntu': ('Elektronik', 'Ses& Görüntü Sistemleri'), # Senin Kuralın
    'hoparlor': ('Elektronik', 'Ses& Görüntü Sistemleri'),
    'kulaklik': ('Elektronik', 'Ses& Görüntü Sistemleri'),
    'oyun': ('Elektronik', 'Hobi - Oyun (Gaming) Ürünleri'), # Senin Kuralın
    'konsol': ('Elektronik', 'Hobi - Oyun (Gaming) Ürünleri'),
    'arac ici kamera': ('Elektronik', 'Araç İçi Kamera'), # Senin Kuralın
    'yazar kasa': ('Elektronik', 'Ödeme Sistemleri'), # Senin Kuralın
    'pos': ('Elektronik', 'Ödeme Sistemleri'),
    'cep telefonu aksesuarlari': ('Elektronik', 'Cep Telefonu Aksesuarları'),
    'powerbank': ('Elektronik', 'Cep Telefonu Aksesuarları'),
    'sarj cihazi': ('Elektronik', 'Cep Telefonu Aksesuarları'),
    
    # ISITMA SOĞUTMA VE ENERJİ GRUBU
    'klima': ('Isıtma Soğutma ve Enerji', 'Klima'),
    'vantilator': ('Isıtma Soğutma ve Enerji', 'Vantilatör'),
    'isitici': ('Elektronik', 'Elektrikli Isıtıcı'), # Senin Kuralın
    'radyator': ('Elektronik', 'Elektrikli Isıtıcı'), 
    'termosifon': ('Isıtma Soğutma ve Enerji', 'Termosifon'),
    'kombi': ('Isıtma Soğutma ve Enerji', 'Kombi'),
    'hava sogutucu': ('Isıtma Soğutma ve Enerji', 'Hava Soğutucu'),
    'nem alma': ('Isıtma Soğutma ve Enerji', 'Nem Alma Cihazı'),
    'isitma sogutma yedek parca': ('Isıtma Soğutma ve Enerji', 'Isıtma Soğutma Yedek Parça ve Aksesuarları'), # Senin Kuralın

    # KÜÇÜK EV ALETLERİ GRUBU
    'kucuk ev aletleri': ('Küçük Ev Aletleri', 'Küçük Ev Aletleri Seti'), # Senin Kuralın (Setleri)
    'supurge': ('Küçük Ev Aletleri', 'Elektrikli Süpürge'), # Senin Kuralın
    'frozen': ('Küçük Ev Aletleri', 'Frozen ve Slush Makinesi'), # Senin Kuralın
    'slush': ('Küçük Ev Aletleri', 'Frozen ve Slush Makinesi'),
    'kahve makinesi': ('Küçük Ev Aletleri', 'Kahve Makinesi'), # Senin Kuralın
    'espresso': ('Küçük Ev Aletleri', 'Kahve Makinesi'),
    'pisirici': ('Küçük Ev Aletleri', 'Pişirici'), # Senin Kuralın
    'airfryer': ('Küçük Ev Aletleri', 'Pişirici'),
    'fritoz': ('Küçük Ev Aletleri', 'Pişirici'),
    'tost makinesi': ('Küçük Ev Aletleri', 'Pişirici'),
    'ekmek kizartma': ('Küçük Ev Aletleri', 'Pişirici'),
    'karistirici': ('Küçük Ev Aletleri', 'Karıştırıcı& Doğrayıcı'), # Senin Kuralın
    'dograyici': ('Küçük Ev Aletleri', 'Karıştırıcı& Doğrayıcı'),
    'blender': ('Küçük Ev Aletleri', 'Karıştırıcı& Doğrayıcı'),
    'mikser': ('Küçük Ev Aletleri', 'Karıştırıcı& Doğrayıcı'),
    'kiyma makinesi': ('Küçük Ev Aletleri', 'Karıştırıcı& Doğrayıcı'),
    'hamur yogurma': ('Küçük Ev Aletleri', 'Karıştırıcı& Doğrayıcı'),
    'kisisel bakim': ('Küçük Ev Aletleri', 'Kişisel Bakım'), # Senin Kuralın
    'agiz bakim': ('Küçük Ev Aletleri', 'Kişisel Bakım'),
    'baskul': ('Küçük Ev Aletleri', 'Kişisel Bakım'),
    'sac duzlestirici': ('Küçük Ev Aletleri', 'Kişisel Bakım'),
    'sac masasi': ('Küçük Ev Aletleri', 'Kişisel Bakım'),
    'tiras makinesi': ('Küçük Ev Aletleri', 'Kişisel Bakım'),
    'outdoor': ('Küçük Ev Aletleri', 'Outdoor Ekipman'), # Senin Kuralın
    'termos': ('Küçük Ev Aletleri', 'Outdoor Ekipman'),
    'kahve ve sofra': ('Küçük Ev Aletleri', 'Kahve ve Sofra Ürünleri'), # Senin Kuralın
    'ev temizlik': ('Küçük Ev Aletleri', 'Ev Temizlik Ekipmanları ve Teknolojileri'), # Senin Kuralın
    'utu': ('Küçük Ev Aletleri', 'Ütü'),
    'cay makinesi': ('Küçük Ev Aletleri', 'Çay Makinesi'),
    'semaver': ('Küçük Ev Aletleri', 'Semaver'),
    'kettle': ('Küçük Ev Aletleri', 'Kettle'),
    'meyve sikacagi': ('Küçük Ev Aletleri', 'Katı Meyve Sıkacağı'),
    'narenciye': ('Küçük Ev Aletleri', 'Narenciye Sıkacağı'),
    'dondurma makinesi': ('Küçük Ev Aletleri', 'Dondurma Makinesi'),
    'buz makinesi': ('Küçük Ev Aletleri', 'Buz Makinesi'),
    'uv temizleme': ('Küçük Ev Aletleri', 'UV Temizleme Cihazı'),
    'yogurt': ('Küçük Ev Aletleri', 'Yoğurt &Kefir Makinesi'),
    'kefir': ('Küçük Ev Aletleri', 'Yoğurt &Kefir Makinesi'),

    # HİJYEN-AKSESUAR-OTO GRUBU
    'aktif hijyen': ('Hijyen-Aksesuar-Oto', 'Aktif Hijyen'), # Senin Kuralın
    'arac buzdolabi': ('Hijyen-Aksesuar-Oto', 'Araç Buzdolabı'),
    'aksesuar': ('Hijyen-Aksesuar-Oto', 'Aksesuarlar'),

    # SU ARITMA GRUBU
    'su aritma': ('Su Arıtma', 'Su Arıtma Cihazları') # Senin Kuralın
}

# 2. Aşama: Eşleştirme Fonksiyonu
def akilli_eslestir(Product_Group):
    # Ürün adını temizle (Örn: "10 Kg Camasir Makinesi" -> "10 kg camasir makinesi")
    temiz_ad = metin_temizle(Product_Group)
    
    # Kural sözlüğündeki anahtar kelimeleri (keys) tek tek dolaş
    for anahtar_kelime, (ana_kat, alt_kat) in kategori_kurallari.items():
        # Eğer sözlükteki anahtar kelime, temizlenmiş ürün adının içinde geçiyorsa
        # (Örn: "camasir makinesi" metni "10 kg camasir makinesi" içinde geçer)
        if re.search(r'\b' + re.escape(anahtar_kelime) + r'\b', temiz_ad):
            return pd.Series([ana_kat, alt_kat])
            
    # Eğer hiçbir kurala uymazsa
    return pd.Series(['Diğer', 'Diğer'])

# 3. Aşama: Fonksiyonu Uygulama ve Yeni Sütunları Oluşturma
# df'indeki 'kategori' sütununu baz alıyoruz (veya doğrudan 'Product_Group' sütununu da kullanabilirsin)
# Eğer senin scraping verinde 'Product_Group' daha açıklayıcıysa df['Product_Group'] kullanmak daha doğru sonuç verebilir.
df[['Main_Category', 'Subcategory']] = df['Product_Group'].apply(akilli_eslestir)

# Sonucu Kontrol Etme (Hangi ürünlerin eşleşemediğini görmek için)
eslesmeyenler = df[df['Main_Category'] == 'Diğer']
print(f"Eşleşmeyen ürün sayısı: {len(eslesmeyenler)}")
if len(eslesmeyenler) > 0:
    print("\nEşleşemeyen ilk 10 ürün:")
    print(eslesmeyenler[['Product_Group']].head(10))

# Eşleşenlerden bir örnek
print("\nEşleşen ürünler örneği:")
print(df[['Product_Group', 'Main_Category', 'Subcategory']].sample(10, random_state=15))

Eşleşmeyen ürün sayısı: 174

Eşleşemeyen ilk 10 ürün:
                         Product_Group
168             Ankastre Mikrodalgalar
188             Gazli Cam Tablali Ocak
189             Gazli Cam Tablali Ocak
190        Entegre Davlumbazli Ocaklar
191        Entegre Davlumbazli Ocaklar
192               Vitroseramik Ocaklar
193  Gazli Inoks Metal Tablali Ocaklar
194             Gazli Cam Tablali Ocak
195                     Domino Ocaklar
196  Gazli Inoks Metal Tablali Ocaklar

Eşleşen ürünler örneği:
                                      Product_Group             Main_Category  \
94                           12 Kg Camasir Makinesi                Beyaz Eşya
482                                        Kulaklik                Elektronik
295                     Fitfry Buhar Destekli Firin                Beyaz Eşya
434                                        Hoparlor                Elektronik
1015  Kucuk Ev Aletleri Yedek Parca Ve Aksesuarlari         Küçük Ev Aletleri
262                            Duvar Tipi Davlumbaz                  Ankastre
890                                   Hava Sogutucu  Isıtma Soğutma ve Enerji
710                       Android Telefon Modelleri                Elektronik
879                                     Split Klima  Isıtma Soğutma ve Enerji
368                                    Oyun Konsolu                Elektronik

                        Subcategory
94                 Çamaşır Makinesi
482         Ses& Görüntü Sistemleri
295                           Fırın
434         Ses& Görüntü Sistemleri
1015         Küçük Ev Aletleri Seti
262           Ankastre Davlumbazlar
890                   Hava Soğutucu
710                    Cep Telefonu
879                           Klima
368   Hobi - Oyun (Gaming) Ürünleri

In [212]:
df.sample(5, random_state=42)

,urun_linki,urun_adi,fiyat,teknik_ozellikler,enerji_sinifi,favori_sayisi,yorum_sayisi,renk_secenekleri,urun_ozellikleri,yorumlar,Product_Group,Main_Category,Subcategory
478,https://www.beko.com.tr/kulaklik/samsung-typec...,Samsung TypeC Kablolu Kulaklık-Siyah Kulaklık,599 TL,"{""Kulaklık Tipi"": ""Kablolu Kulak İçi Kulaklık""...",NaN,1.00,NaN,[],"{""Kulaklık Tipi"": ""Kablolu Kulak İçi Kulaklık""...",[],Kulaklik,Elektronik,Ses& Görüntü Sistemleri
722,https://www.beko.com.tr/cep-telefonu-aksesuarl...,UGREEN USB-C 60W Örgülü Kablo Syh 1M Cep Telef...,379 TL,"{""2 cm"": ""Derinlik"", ""4 cm"": ""Genişlik"", ""5 cm...",NaN,0.00,NaN,[],{},[],Cep Telefonu Aksesuarlari,Elektronik,Cep Telefonu
312,https://www.beko.com.tr/ankastre-mikrodalgalar...,BMM 2020 I Ankastre Mikrodalgalar,16.420 TL,"{""Mikrodalga Hacmi"": ""20"", ""Ürün Rengi"": ""İnok...",NaN,22.00,NaN,[],"{""Mikrodalga Hacmi"": ""20"", ""Ürün Rengi"": ""İnok...",[],Ankastre Mikrodalgalar,Diğer,Diğer
661,https://www.beko.com.tr/android-telefon-modell...,Xiaomi Redmi Note 14 Pro 12/512GB Siyah Androi...,20.999 TL,"{""Dahili Hafıza"": ""512GB"", ""Ön Kamera"": ""32MP""...",NaN,1.00,NaN,[],"{""Dahili Hafıza"": ""512GB"", ""Ön Kamera"": ""32MP""...",[],Android Telefon Modelleri,Elektronik,Cep Telefonu
969,https://www.beko.com.tr/espresso-makinesi/nesp...,Nespresso Aeroccino 4 Süt Köpürtücü Espresso M...,5.999 TL,"{""10 cm"": ""Genişlik"", ""17 cm"": ""Yükseklik"", ""A...",NaN,0.00,NaN,[],{},[],Espresso Makinesi,Küçük Ev Aletleri,Kahve Makinesi

In [213]:
# Tüm sütunları gez ve boş liste/sözlük yapılarını NaN yap
for col in df.columns:
    df[col] = df[col].apply(lambda x: np.nan if str(x).strip() in ['[]', '{}', ''] else x)

# Fiyat
# 1. 'TL' yazısını ve etrafındaki her türlü boşluğu (\n dahil) regex ile temizle
df['fiyat'] = df['fiyat'].str.replace(r'\s*TL', '', regex=True)

# 2. Binlik ayracı olan noktayı (.) tamamen sil (örn: 39.959 -> 39959)
df['fiyat'] = df['fiyat'].str.replace('.', '', regex=False)

# 3. Eğer başka satırlarda kuruş varsa (örn: 475,50), virgülü ondalık formata (.) çevir
df['fiyat'] = df['fiyat'].str.replace(',', '.', regex=False)

# 4. Temizlenmiş metni artık güvenle float tipine dönüştür
df['fiyat'] = pd.to_numeric(df['fiyat'], errors='coerce')


# Bilimsel gösterimi kapat, sayıları virgülden sonra 2 basamaklı normal formatta göster
pd.set_option('display.float_format', lambda x: '%.2f' % x)

# Favori Sayısı
# Metinleri temizle ve sayıya çevir
df['favori_sayisi'] = pd.to_numeric(df['favori_sayisi'], errors='coerce')

# NaN'ları bozmadan tam sayıya çevir (Büyük 'I' harfine dikkat!)
df['favori_sayisi'] = df['favori_sayisi'].astype('Int64')

# NumPy için bilimsel gösterimi kapat (suppress=True)
np.set_printoptions(suppress=True)

# Çıktıyı tekrar kontrol et
print(df['fiyat'].unique())
print(df['favori_sayisi'].unique())

[ 88409.         nan  15159.    57969.    22189.    34829.    19749.
  59129.    28279.    18899.    42409.    48579.    22989.    47839.
  34129.    31389.    39449.    35829.    50489.    36029.    33839.
  36809.    37769.    33869.    40619.    39809.    29489.    38639.
  40259.    32189.    35279.    46799.    39959.    37649.    41069.
  38489.    24479.    25979.    28079.    23729.    34859.    24029.
  33569.    29699.    21179.    23579.    26549.    36149.    30989.
  36869.    23369.    21089.    27899.    27209.    21869.    38999.
  39479.    40379.    39719.    45329.    40799.    38249.    35699.
  23999.    44129.    41849.    43229.    43499.    39749.    37139.
  40499.     8739.    28276.    46466.    15363.    12599.    28734.
  40039.    27982.    45093.    15120.    14700.     9540.    12600.
   5010.     9000.    10260.     5899.     7469.     6599.    11217.
   8119.    15577.    31701.    21499.    12999.     7749.     9949.
  12399.    16849.      525.      260.      350.      300.      750.
  15240.    26790.    98370.    93060.    40680.    31650.    20610.
  20070.    18780.    17580.    16710.    11340.    10500.     9840.
   7360.    22530.    41760.    40530.    24450.    30230.    44610.
  16350.    34860.    17850.    35010.    10140.    18360.    16500.
  24720.    14940.    64830.    14640.    11040.     7230.    12990.
   8830.     9990.    22990.     8320.     6250.     8910.     6270.
  10350.    11490.     9510.    10590.    30359.    32339.    36119.
  40949.    32249.    37589.    28349.    30242.    26193.    23519.
  17074.    18149.    15146.    59405.    17166.    13009.    10989.
  26192.    26223.    26799.    16420.     5279.      500.      600.
  28999.    21999.    27999.      449.    45999.    19899.    13999.
  60999.    67999.    24999.     9999.    47999.    64999.    39999.
  15999.    13499.     6999.    41999.      499.    33999.    40999.
   4799.     5799.     4999.    19999.    45499.    42999.    35999.
  37499.    22499.    52999.    10499.    26999.     3329.     2879.
   1199.    32199.     1599.     1999.     1899.     2399.      599.
  46999.     2899.     7399.     1290.     3299.     1699.     1099.
   2299.     2099.     2149.     2549.     3990.     7690.     1690.
   2999.     1859.     4499.     5499.    10439.     5999.     3999.
    949.     2599.     8999.    17999.     6699.      779.    11959.
   2190.     1090.     4669.      749.      459.     4699.     4299.
   2959.      559.     2499.      121.02    999.     1499.   123899.
   8299.   147899.   135599.   107899.    48999.    56650.    63999.
  80799.   117559.   124299.   110699.    92199.    80099.    98399.
 173599.   135499.    43599.    45950.    70999.    70040.    75099.
 121719.    85399.   102499.   102989.7  127959.   126919.    49999.
  14349.    34299.     9475.    72999.    61799.    12499.    18599.
  20999.    19659.    29999.    11799.    13599.     9199.     9599.
  85499.    15899.    50499.    24699.    19199.     2699.    21599.
  16949.    10199.    13199.    12149.    64649.    12199.      869.
   1399.      699.      379.      299.      849.      789.     1139.
   2749.     1949.      939.      669.      235.     1399.9     799.9
    389.9     399.9    1889.     1249.     1069.      229.      759.
    649.      349.     2489.     2059.      919.    18229.    16299.
   6399.    19599.    14749.    17299.    55000.    10999.    11999.
   6000.     7999.     6409.     7499.   152997.    31596.   107097.
  47394.    39753.    36780.    70332.    56553.    73044.   175917.
  60474.    34134.    65505.    60651.    51024.    33177.    51357.
  56187.    75483.    91512.    45681.    48891.    67464.    79566.
  36924.    14599.     2849.     5849.     9499.     3449.     2449.
   4149.     7299.     3649.     6249.     4549.     4849.     8349.
   4599.    12779.    14699.    16339.    17669.    44299.    30999.
  35399.    38399.    40699.     9299.      700.    11149.     5149.
   3349.     4399.    10699.     7479.     3699.     1729.    11899.
   5599.     7179.    12649.     1359.     6649.     5699.    91599.
  21250.     2624.96   1260.     3674.98   2467.46  27750.   113662.46
  14962.5   29399.96  14499.    91874.98  94762.46   2079.18   1837.46
   3150.    13387.5   79799.96  77948.     1469.98   1994.96   2152.46
   2362.5    3749.     4899.     6849.    10459.      850.     1300.
    650.      220.     1400.      450.      110.     1600.     4000.
   1700.     2450.      475.      400.      800.      550.      425.
    375.     1100.      210.     1800.      950.      900.     1500.
   3000.     3750.    14999.     5399.     5199.     7799.    15599.
  20799.     3099.    10399.     3599.    31299.    20399.    25999.
  73447.48  78697.46  83947.5   54599.96  26775.    77437.46   5512.5
  56700.     8899.     8959.     3949.    10799.     9169.    33549.
   9349.    10549.     7649.     2189.     5139.     4989.     8609.
   5099.     3899.     4789.     2199.     3399.    11949.     2929.
   3929.     3199.      899.     1799.     1299.     3499.     2799.
    799.     1149.    16999.    17199.      249.    13799.    17699.
  14449.     6499.     6049.     6349.     9099.     2559.     3049.
   5649.     3799.    26599.     2359.     4249.     4349.     3149.
   8449.     7839.     1479.    35119.    39669.    10990.  ]
<IntegerArray>
[104,   4,   7,  41,  10,  90,  36,  61,  54,  71,
 ...
 130,  94, 136,  76, 158, 116, 143,  63,  32,  75]
Length: 121, dtype: Int64

In [214]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   urun_linki         1301 non-null   str
 1   urun_adi           1301 non-null   str
 2   fiyat              1176 non-null   float64
 3   teknik_ozellikler  1129 non-null   str
 4   enerji_sinifi      270 non-null    str
 5   favori_sayisi      1237 non-null   Int64
 6   yorum_sayisi       126 non-null    str
 7   renk_secenekleri   80 non-null     str
 8   urun_ozellikleri   901 non-null    str
 9   yorumlar           175 non-null    str
 10  Product_Group      1301 non-null   str
 11  Main_Category      1301 non-null   str
 12  Subcategory        1301 non-null   str
dtypes: Int64(1), float64(1), str(11)
memory usage: 1.3 MB

In [215]:
df = df.drop(columns=['yorumlar', 'renk_secenekleri', 'yorum_sayisi', 'urun_ozellikleri'])

# favori sayısı nan yap
df['favori_sayisi'] = df['favori_sayisi'].fillna(pd.NA).astype('Int64')

In [216]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   urun_linki         1301 non-null   str
 1   urun_adi           1301 non-null   str
 2   fiyat              1176 non-null   float64
 3   teknik_ozellikler  1129 non-null   str
 4   enerji_sinifi      270 non-null    str
 5   favori_sayisi      1237 non-null   Int64
 6   Product_Group      1301 non-null   str
 7   Main_Category      1301 non-null   str
 8   Subcategory        1301 non-null   str
dtypes: Int64(1), float64(1), str(7)
memory usage: 975.1 KB

In [217]:
df["teknik_ozellikler"].sample(5, random_state=15)

94      {"Kapasite": "12 kg", "Maksimum Sıkma Devri": ...
482     {"Kulaklık Tipi": "Kablosuz kulak üstü kulaklı...
295     {"Motor Teknolojisi": "AeroPerfect", "Homewhiz...
434     {"Ses Çıkış Gücü": "2x 2,5 W", "Çalma Süresi":...
1015                                                  NaN
Name: teknik_ozellikler, dtype: str

In [218]:
import pandas as pd
import ast

def parse_dict(val):
    if pd.isna(val):
        return {}
    try:
        parsed_val = ast.literal_eval(val)
        # Sadece gerçekten sözlük olanları alalım
        if isinstance(parsed_val, dict):
            return parsed_val
        return {}
    except (ValueError, SyntaxError):
        return {}

# Sözlük hallerini içeren geçici sütunu oluşturalım
df['teknik_ozellikler_dict'] = df['teknik_ozellikler'].apply(parse_dict)

In [219]:
from collections import Counter

# Her bir sözlüğün içindeki tüm anahtarları (key) tek bir listede topluyoruz
tum_anahtarlar = [key for d in df['teknik_ozellikler_dict'] for key in d.keys()]

# Counter ile bu listedeki elemanların kaçar kez geçtiğini saydırıyoruz
frekanslar = Counter(tum_anahtarlar)

print(f"Toplam {len(frekanslar)} farklı özellik bulundu.\n")
print("Özellik Adı - Bulunma Sayısı")
print("-" * 30)

# En çok tekrar edenden en aza doğru yazdırıyoruz
for özellik, adet in frekanslar.most_common():
    print(f"{özellik}: {adet}")

Toplam 1083 farklı özellik bulundu.

Özellik Adı - Bulunma Sayısı
------------------------------
Ağırlık: Paketsiz: 592
Boyut (cm) (GxYxD): 566
Derinlik: 565
Ürün Rengi: 496
Bluetooth: 279
Enerji Sınıfı: 245
Ekran Tipi: 227
Renk: 224
Ekran Boyutu: 215
İşletim Sistemi: 207
1 cm: 189
Ön Kamera: 188
Wi-Fi: 185
Dahili Hafıza: 175
Marka: 175
2.Arka Kamera: 174
60 cm: 165
8 cm: 164
NFC: 162
Ürün Tipi: 159
İşlemci: 151
Güç: 149
Ses Seviyesi: 143
İşlemci Çekirdek Sayısı: 141
4 cm: 139
Ekran Çözünürlüğü: 137
Kamera Zoom: 135
Motor Tipi: 131
7 cm: 131
Ön Kamera Flaş: 131
15 cm: 126
Görüntülü Konuşma: 126
Arka Kamera: 116
GPS: 116
RAM Kapasitesi: 108
5 cm: 107
Kontrol Sistemi: 100
Mikrofon: 99
Genişlik: 98
Yıllık Enerji Tüketimi (kWh): 93
Ses Kayıt: 90
Kapasite: 87
Yüz Haritalama: 87
16 cm: 81
Kulaklık Tipi: 80
İklim Sınıfı: 78
Toplam Hacim (L): 78
Ses Seviyesi Sınıfı: 78
Soğutma Sistemi: 78
Günlük Enerji Tüketimi (kwh/Gün): 78
Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP): 78
Dondurucu Yeri: 77
Dondurucu Bölme Hacmi (L): 77
Sıcaklık Yükselme Süresi (Saat): 76
3 cm: 76
Voltaj: 74
9 cm: 72
İşletim Sistemi Versionu: 72
2 cm: 68
Çift Hatlı: 67
Pil Kapasitesi: 67
Buzluk Tipi: 66
6 cm: 66
Ürün Ailesi: 66
Çocuk Kilidi: 65
85 cm: 64
17 cm: 62
Kapı Yönü Değiştirme: 61
Günlük Dondurma Kapasitesi (kg/Gün): 61
Aydınlatma Tipi: 59
18 cm: 59
Elektronik Gösterge: 58
Ocak Yüzeyi: 58
30 cm: 58
Kontrol Tipi: 58
21 cm: 57
Su Geçirmezlik: 55
Dondurucu Çekmece Sayısı: 54
31 cm: 54
Soğutucu Bölme Hacmi (L): 53
Sebzelik Adedi: 53
19 cm: 53
Ocak Tipi Ve Göz Sayısı: 52
Ocak Tipi: 52
Kontrol Tipi ve Yeri: 52
12 cm: 50
Program Sayısı: 49
Gaz Tipi: 49
Ocak Ateşleme Tipi: 49
Gaz Emniyet Sistemi: 49
Sağ Arka Bölme: 49
Sağ Ön Bölme: 49
Ürün Serisi: 48
Sol Ön Bölme: 48
Toplam Elektrik Gücü (kW): 48
Sol Arka Bölme: 48
10 cm: 48
Tatil Modu: 47
Soğutucu Bölme Fanı: 47
Kahvaltılık Çekmecesi: 46
Minimum Ses Seviyesi: 46
Maksimum Çekiş Gücü: 46
Yağ Filtre Adedi: 46
Motor Sayısı: 46
Bulaşık Makinesinde Yıkanabilir Filtre: 46
Lamba Adedi: 46
Lamba Tipi: 46
Lamba Gücü (W): 46
Kademe Sayısı: 46
Karbon Filtre: 46
Pil Türü: 45
59 cm: 43
Bek Şapkası Tipi: 43
24 cm: 42
36 cm: 42
Otomatik Kapanma: 42
22 cm: 41
Filtre Tipi: 41
Niş Boyutlar (YxGxD) (cm): 40
Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre): 40
20 cm: 40
Kablo Uzunluğu: 40
ProSmart™ Inverter Kompresör: 39
Bağlantı: 39
25 cm: 39
HarvestFresh™: 38
52 cm: 38
35 cm: 37
Motor Gücü: 36
Hızlı Soğutma: 35
Fırın Hacmi: 35
Fırın Fonksiyon Adedi: 35
Elektrikli Izgara: 35
Standart Tepsi Adedi: 35
Ön Kapak Cam Sayısı: 35
Tencere Izgara Tipi: 35
57 cm: 35
Montaj Yüksekliği (mm): 35
Program-10: 34
Program-12: 34
Program-13: 34
Program-15: 34
Program-5: 34
Program-6: 34
Program-7: 34
Tambur Deseni: 34
Kalan Zaman Göstergesi: 34
Program-1: 34
Program-2: 34
Program-3: 34
Program-4: 34
Program-8: 34
Program-9: 34
Statik Fonksiyon: 34
Kolayca Sökülebilir ve Temizlenebilir Komple İç Cam: 34
Program-11: 33
Paslanmaz Çelik İç Gövde: 33
Fonksiyon 1: 33
Yüksekliği Ayarlanabilir Fincan Rafları: 33
Fincan Raf Sayısı: 33
Çatal Kaşık Sepeti: 33
Program: 33
Program Sıcaklıkları (°C): 33
Ekonomi Programı Süresi (dk): 33
Güç (W): 33
Akım (A): 33
Enerji Tüketimi: 33
Su Tüketimi: 33
Parlatıcı Göstergesi: 33
Tuz Göstergesi: 33
Su Güvenlik Sistemi: 33
Davlumbaz Tipi: 33
23 cm: 33
Dondurucu Bölme Aydınlatma Tipi: 32
Program-14: 32
Fonksiyon 2: 32
Zaman Erteleme Fonksiyonu: 32
Motor Teknolojisi: 32
Buharlı Pişirme: 32
Kapak Açılma Yönü: 32
28 cm: 32
Aux Girişi: 32
Ağırlık (gr): 32
Yarım Yük Yıkama: 31
Alt Sepet Katlanır Tel Sayısı: 31
Elektroturbo (Fan Destekli Pişirme): 31
Üst Sepet Ayar Tipi: 30
Kahve Beki Adaptörü: 30
Verimlilik: 30
İşlemci Hızı: 30
Buharlı Temizleme Fonksiyonu: 29
Aktif gürültü önleyici: 29
Ses Basınç Seviyesi (dB): 29
Su Tankı Kapasitesi: 29
Tek Tuşla Kontrol: 29
Iyon Özelliği: 29
Otomatik Kapı Açma Özelliği: 28
Fonksiyon 3: 28
Alt Isıtıcı: 28
42 cm: 28
Filtre Doluluk Göstergesi: 28
Saat Tipi: 27
Tel Izgara: 27
114 cm: 27
Dahili Depolama Kapasitesi: 27
Çalma Süresi: 27
Gövde rengi: 27
75 cm: 26
70 cm: 26
Bardak Koruma Sistemi: 26
Ekran Kilidi: 26
Soğutma Kapasitesi: 26
Soğutucu Akışkan: 26
Gizli Gösterge: 26
Nem Alma: 26
Küçük Izgara: 25
Çerçeve: 25
26 cm: 25
Ses Çıkış Gücü: 25
Hafıza Kartı Tipi: 25
Parmak İzi Okuyucu: 25
Yıllık Tüketim (kW) Soğuma: 25
Mevsimsel (SEER) Enerji Verimi Soğutma (W/W): 25
Çoklu Programlama Özelliği: 25
Uyku Mode: 25
Dış Ünite Soğutma Çalışma Aralığı(°C): 25
Otomatik Hava Yönlendirme (Yukarı-Aşağı): 25
Toz Torbası Kapasitesi: 25
187 cm: 24
Zamanlayıcı: 24
Otomatik Kapanma Özelliği: 24
Isıtma Kapasitesi (Btu/h): 24
Yıllık Tüketim Isıtma (kW): 24
Mevsimsel (SCOP) Enerji Verimi Isıtma (W/W): 24
Isıtmada Çekilen Enerji (W): 24
Dış Ünite Isıtma Çalışma Aralığı(°C): 24
Hız Ayarı: 24
Şarj Olma Süresi: 24
76 cm: 23
58 cm: 23
Gösterge Tipi: 23
Üst Sepet Katlanır Tel Sayısı: 23
61 cm: 23
33 cm: 23
32 cm: 23
Özel Filtreler: 23
Fonksiyon 4: 22
39 cm: 22
Sıcaklık Ayarı: 22
PractiClean Nano Kaplama: 22
Enerji Sınıfı-Isıtma: 22
44 cm: 21
13 cm: 21
Uyumlu olduğu modeller (MPA): 21
Sessiz Mod: 21
Dış Ünite (GxYxD) mm: 21
İç Ünite (GxYxD) mm: 21
Ürün rengi: 21
Pompa Basıncı: 21
Maksimum Sıcaklık Derecesi: 21
Minimum Sıcaklık Derecesi (°C): 21
Maksimum Sıkma Devri: 20
Su Girişi: 20
Deterjan Sistemi: 20
Buhar: 20
Elektronik Su Kontrol Sistemi: 20
Dengesiz Yük Kontrolü: 20
USB Bağlantısı: 20
SSD Kapasitesi: 20
Hızlı Şarj desteği: 20
Otomatik Temizleme: 20
Kapasite (Isıtma): 20
Fincan Kapasitesi: 20
EverFresh+ Teknolojisi: 19
Toplam Dondurucu Bölme Sayısı: 19
Motor Tipi (ÇM): 19
Zaman Programlama Özelliği: 19
Su Taşma Emniyet Sistemi: 19
Su Kesik İkazı: 19
Su Tüketimi (1 Çevrim): 19
Enerji Tüketimi (100 Çevrim): 19
Bulaşık Makinesinde Yıkanabilir Aksesuarlar: 19
İşlemci Tipi: 19
SSD Özellikleri: 19
11 cm: 19
Sıcaklık Ayarı Kilidi: 19
IronFast: 18
Elektronik Program Takip Göstergesi: 18
Fırın İçi Aydınlatma: 18
Buz Çözme Fonksiyonu: 18
51 cm: 18
LCD Ekran: 18
Akıllı Çalışma Sistemi: 18
Sesli Uyarı: 18
Dar Ağızlı Uç: 18
Eko Modu: 17
84 cm: 17
Ekstra Kurutma Fonksiyonu: 17
İndirilebilir Program: 17
Fan Destekli Isıtıcı: 17
38 cm: 17
Yoğun Emiş Gücü (m³/h): 17
Ayarlanabilir Led Aydınlatma: 17
Yoğun Emiş Gücü: 17
Hava Temizleme Özelliği: 17
Pil: 17
Bellek: 17
Çıkış Gücü: 17
40 cm: 17
Isıtmadaki Enerji Verim Oranı (W/W): 17
Işıklı Uyarı: 17
Ölçü Kaşığı: 17
Cook Sense Teknolojisi (Pişmeyi Algılama): 17
Anti Spill Teknolojisi (Taşmayı Önleme): 17
Çıkarılabilir Su tankı: 17
Batarya: 17
Sıcaklık seviye sayısı: 17
Park Etme Özelliği: 17
Döşeme/Koltuk Fırçası: 17
Kablosuz Çalışma Süresi (Düşük Güç): 17
Kapı Kilidi: 16
Derin Tepsi Adedi: 16
3D Pişirme: 16
34 cm: 16
İşletim Sistemi Özellikleri: 16
RAM Özellikleri: 16
HDMI: 16
İşlemci Özellikleri: 16
Pil Ömrü: 16
27 cm: 16
Cezve Rengi: 16
Kablo Sarma Yuvası: 16
Toz Haznesi Kapasitesi: 16
Kablosuz çalışma süresi(Yüksek güç): 16
Günlük Dondurma Kapasitesi (kg): 15
Kurutma Kapasitesi: 15
Program Takip Göstergesi: 15
65 cm: 15
Mikrodalga Kontrol Paneli: 15
Mikrodalga Çıkış Gücü: 15
Mikrodalga Hacmi: 15
Mikrodalga Fırın Türü: 15
Zamanlayıcı Tipi: 15
Döner Tabla: 15
Kapak Açma Mekanizma Tipi: 15
Cam Dekor Rengi: 15
Ekran Kartı Özellikleri: 15
Aksesuar (Ek Donanım): 15
Micro USB: 15
43 cm: 15
Kablo Tipi: 15
Enerji Kontrol: 15
Yumuşak Hava: 15
Cezve Malzemesi: 15
Soğutma/Dondurma Modu: 14
82 cm: 14
Dokunmatik Tuş: 14
Tank Pozisyonu: 14
Kırışık Önleme Fonksiyonu: 14
Zaman Erteleme Özelliği: 14
Tambur Aydınlatma: 14
Direkt Su Tahliyesi: 14
Su Tankı Dolu Uyarısı: 14
Kondenser Temizleme Uyarısı: 14
Fıltre Temizleme Uyarısı: 14
Program Sonu Sesli Uyarı: 14
Isı pompalı Kurutma Teknolojisi: 14
Akıllı Nem Sensörü: 14
Tambur Hacmi (L): 14
Ses Gücü Seviyesi (dBA): 14
45 cm: 14
Maksimum Zamanlama Süresi: 14
Mikrodalga Güç Kademe Sayısı: 14
Buz Çözme Özelliği: 14
47 cm: 14
Aşırı Isınma Emniyeti: 14
Özel Fonksiyonlar: 14
USB Girişi: 14
14 cm: 14
Anlık Tüketim Göstergesi: 14
Donma Emniyeti: 14
Fincan Boyutu Seçimi: 14
Kapsül Kahve: 14
Batarya tipi: 14
Ölçü Kabı: 14
188 cm: 13
Kir Sensörü: 13
Pratik Filtre: 13
FitFry Teknolojisi: 13
Animoji: 13
Portre Işığı: 13
4 Yönlü Otomatik Hava Kontrolü: 13
Sıcak Tutma Özelliği: 13
41 cm: 13
Dilim Kapasitesi: 13
Cool Shot: 13
Isı Ayarı: 13
Parke / Halı fırçası: 13
Batarya kapasitesi: 13
Dondurucu Bölme Teknolojisi: 12
54 cm: 12
29 cm: 12
Fan ve Alt Isıtıcı: 12
Teleskopik Ray Sistemi: 12
Ekran Kartı: 12
Harddisk Kapasitesi: 12
Uyumlu Olduğu Platformlar: 12
Güvenli şarj için akım korumalı: 12
Kablo uzunluğu: 12
İç Ünite Soğutma Çalışma Aralığı(°C): 12
Gövde Malzemesi: 12
Doğrama Kabı Malzemesi: 12
Ürün Kilidi: 12
Uzatma Borusu: 12
Kablosuz çalışma süresi(Orta güç): 12
Paslanmaz Çelik Bıçak: 12
64 cm: 11
Buhar Destekli Pişirme: 11
Mikrodalga Kavite Tipi: 11
Pasta Tepsi Adedi: 11
Kablosuz Ağ: 11
Mikrofon (MPA): 11
Giriş Gücü: 11
Auto Swing: 11
Hız Kademesi adedi: 11
Güç (W) (9): 11
Vantilatör Tipi: 11
Isıtma Gücü: 11
Malzeme: 11
Hızlı Isınma Süresi: 11
LED Ekran: 11
Fön Başlığı: 11
Seramik Izgara: 11
Bakım Yapan Kaplama: 11
Paspas Özelliği: 11
Taban: 11
Sürekli Buhar: 11
Dikey Ütüleme: 11
Turbo Özelliği: 11
83 cm: 10
78 cm: 10
71 cm: 10
55 cm: 10
İkincil Fonksiyon: 10
Izgara Özelliği: 10
Önden Ayarlanablir Arka Ayaklar: 10
Tezgah Altı Yüksekliği: 10
Hızlı Ön Isıtma Fonksiyonu (Booster): 10
Radyo: 10
Arttırılabilir Hafıza: 10
İç Ünite Isıtma Çalışma Aralığı(°C): 10
Kahve Çeşidi Sayısı: 10
Pişirme Yüzeyi: 10
Plaka Kullanımı: 10
Çıkarılabilir Plakalar: 10
Saçları Pürüzsüz ve Kıvırcık Yapma: 10
Çıkarılabilir hava giriş ızgarası: 10
Kablo Sarıcı: 10
Şarj istasyonu: 10
Yüksek Performanslı Elektrikli Fırça: 10
Dinamik Rezistans: 9
Hızlı Başlatma: 9
Otomatik Pişirme Fonksiyon Adedi: 9
Eko-Turbo Pişirme: 9
İç Hazne Malzemesi: 9
Yüksek Bazaya Montaj: 9
MicroSD Kart Girişi: 9
Hoparlör: 9
3 cihazı aynı anda şarj edebilme: 9
Fan Fonksiyonu: 9
Demlik Kapasitesi: 9
Demlik Malzemesi: 9
Su Isıtıcı Kapasitesi: 9
Su Isıtıcı Malzemesi: 9
Emiş Gücü: 9
Kilitleme Mandalı: 9
Soğuk Saklama Süresi: 9
Sıcak Saklama Süresi: 9
Buzlu Saklama süresi: 9
Soğuk Ayarı: 9
Temizleme Modu: 9
Led Fırça: 9
Ağırlık: Paketli: 9
Blender Ayağı Malzemesi: 9
Paslanmaz Çelik Blender: 9
48 cm: 8
Yoğun Alt Sepet Yıkama Fonksiyonu: 8
Ekstra Hızlı Fonksiyonu: 8
Kapıda Program Takip Göstergesi: 8
ProScent Teknolojisi: 8
İç Izgara Adedi: 8
Kirleri Göstermeyen Katalitik Arka Duvar: 8
Izgara Gücü (W): 8
Kirleri Göstermeyen Katalitik Yan Duvar: 8
Musluk: 8
Uzaktan Kumanda: 8
100 cm: 8
Super Retina HD: 8
Retina HD: 8
Şarj süresi: 8
Salınım Fonksiyonu (NAC): 8
Yakıt Cinsi: 8
Cihaz Tipi: 8
Kapasite (kW): 8
Mevsimsel Mahal Isıtma Enerji Verimliliği Sınıfı: 8
Mevsimsel Mahal Isıtma Enerji Verimliliği (hs): 8
Maksimum Sıcak Su Debisi: 8
Yerden Isıtmaya Uygunluk: 8
Oda Termostatı İle Çalışma: 8
Su ısıtma Enerji Verimliliği (hWH): 8
Ses Gücü Seviyesi, İç Ortam (LWA): 8
Su Isıtma Enerji Verimliliği Sınıfı: 8
Su Isıtma Yük Profili: 8
Alev Modülasyonu: 8
Fan Modülasyonu: 8
Baca Tipi: 8
Genleşme Tankı kapasitesi: 8
Yakıt Tipi: 8
Arıza Teşhis Sistemi: 8
Emniyet Termostatı: 8
Emniyet Ventili: 8
Hava Emiş Emniyeti: 8
Alev Sönme Emniyeti: 8
3 Yollu Vana Blokaj Sistemi: 8
Otomatik By-Pass Sistemi: 8
Pompa Anti Blokaj Sistemi: 8
Açma/Kapama Düğmesi: 8
Difüzör Başlığı: 8
Asma Halkası: 8
Hijyenik Yıkanabilir Başlıklar: 8
Kullanım Şekli: 8
Islak Kuru Kullanım: 8
Etkinlik Alanı Yarıçapı (m): 8
Yedek Sentetik Toz Torbası: 8
Duvara Monte Edilebilen Şarj aleti: 8
Turbo Fırça: 8
Su Haznesi: 8
Doğrayıcı: 8
Doğrayıcı Kabı: 8
Ölçü Kabı: 8
Güvenlik Kilidi: 8
Dondurucu Sepeti: 7
Kapaklı Bölme Sayısı: 7
Hızlı Dondurma Bölmesi: 7
Çıkarılabilir 3. Çekmece: 7
Izgara: 7
Börek Yapma Fonksiyonu: 7
Ana Şasi – Yoğurt Yapma Özelliği: 7
Her Ocak Gözü İçin Sıcaklık Ayarı: 7
Bağlantılar: 7
Müzik Formatlar: 7
Optik Giriş: 7
Equalizer Ayarı: 7
Type¬C veya Micro USB kablolarıyla şarj edilebilir: 7
Kanat Rengi: 7
Pervane Kanat Sayısı: 7
Gövde Rengi: 7
Sıcaklık Ayarı Sayısı: 7
Devrilme Emniyeti: 7
Çalışma Basıncı: 7
Maksimum Çalışma Basıncı: 7
Otomatik Su Alımı: 7
Su Tankı: 7
Su Miktarını Belirleme: 7
Düşük Su Seviyesi Göstergesi: 7
Spinjet Teknolojisi (Su Püskürterek Karıştırma): 7
Su Sıcaklık Ayarı (EM): 7
İkili Isıtma Sistemi: 7
Yağ Toplama Haznesi: 7
Pişirme Kapasitesi: 7
Sepet: 7
Sıcaklık Kontrolü: 7
Pişirme Haznesi: 7
Kapak: 7
Çalışma Göstergesi: 7
İç Hazne Kapasitesi: 7
Hızlı ısıtma fonksiyonu: 7
Kablo Sarma: 7
Vigo Difüzör Başlık: 7
Bıçak Malzemesi: 7
360° Derece Dönebilen Hortum: 7
Taşıma sapı: 7
Kullanım tipi: 7
Şok Buhar: 7
Dikey Otomatik Kapanma Süresi: 7
Yatay Otomatik Kapanma Süresi: 7
Paslanmaz Çelik Çırpıcı: 7
74 cm: 6
91 cm: 6
50 cm: 6
171 cm: 6
86 cm: 6
Ekstra Sessiz Fonksiyonu: 6
IronFinish Teknolojisi: 6
Ocak Göz Sayısı: 6
Ocak Izgara tipi: 6
Sol Arka Yanıcı Gücü: 6
Sol Ön Yanıcı Gücü: 6
Sağ Ön Yanıcı Gücü: 6
Sağ Arka Yanıcı Gücü: 6
Pizza Pişirme: 6
Damacana Yeri: 6
Tank Materyali: 6
Soğuk su tank kapasitesi (L): 6
Soğuk Su Derecesi Aralığı: 6
Soğutma Kapasitesi (lt/saat): 6
Kontrol Sistemi Tipi: 6
Ocak Ekranı: 6
Atıl Isı Göstergesi: 6
Gaz Gücü: 6
Kart Okuyucu: 6
Bağlantı Noktaları: 6
37 cm: 6
IP Sınıfı: 6
Enerji sınıfı (WH) (EP): 6
Titanyum Emaye Kaplamalı Kazan: 6
İzolasyon: 6
Yüksek Basınç Emniyet Valfi: 6
Susuz Çalışma Emniyeti: 6
Korozyona Karşı Koruma: 6
Koruma Sınıfı: 6
Su Seviye Göstergesi: 6
Otomatik Kireç Temizleme Özelliği: 6
360° Dönebilen Kablosuz Kullanım: 6
Işıklı Açma/Kapama Düğmesi: 6
Otomatik Pişirme Program Sayısı: 6
Doluluk göstergesi: 6
Otomatik zemin algılama: 6
Temizleme alanı: 6
Temizlik geçmişini görüntüleme: 6
Halı tırmanma yüksekliği: 6
Programlama: 6
Kendi Kendine Şarj: 6
Wi-fi Bağlantısı: 6
Ekstra Yan Fırça: 6
Hayvan Tüyü Fırçası: 6
Ütü Tipi: 6
Buharsız Ütüleme: 6
Şok Buhar Özelliği: 6
186 cm: 5
182 cm: 5
69 cm: 5
63 cm: 5
Buz Çözme: 5
Dijital Ekran: 5
Zaman Programlayıcı: 5
90 cm: 5
Sıcak Tutma Fonksiyonu: 5
Kapı Açılınca Işık Yanma Özelliği: 5
HDMI Input/Output: 5
Ayarlanabilir yükseklik (mm): 5
Ayarlanabilir Boy: 5
Salınım Açısı (sol sağ ): 5
Elektronik Kontrol Arayüzü: 5
Çıkarılabilir Demleme Ünitesi: 5
Farklı Renk Seçeneği: 5
Renk (41): 5
Hızlı Şarj: 5
Yasaklı alan Tanımlama: 5
Haritalama: 5
Birden fazla harita kaydetme: 5
Oda Tanımlama ve isimlendirme: 5
Sanal Duvar Fonksiyonu: 5
Dijital ekran: 5
Çıkarılabilir Batarya: 5
Dijital Gösterge: 5
Dilimleme: 5
Sürahi Malzemesi: 5
Buz Kırma Fonksiyonu: 5
Çırpma Ucu: 5
Çiğ Köfte Aksesuarı: 5
Yoğurma Ucu: 5
193 cm: 4
66 cm: 4
Hareketli Kapı Rafı: 4
Kolay Kapı Açma Mekanizması: 4
68 cm: 4
İç Aydınlatma: 4
Tablet Deterjan Fonksiyonu: 4
67 cm: 4
Fırın Aydınlatması ve Fan: 4
56 cm: 4
Izgara Seviye Sayısı: 4
104 cm: 4
Bridge Fonksiyonu: 4
Hızlı Isıtma (Booster): 4
Orta Bölme: 4
Mobilya Kapak Ağırlığı (Min-Maks): 4
Mobilya Kapak Ağırlık Ayarı: 4
Homewhiz: 4
Optk Sürücü Özellikleri: 4
Harici Depolama Kapasitesi: 4
LCD pil göstergesi: 4
Akıllı Eko: 4
Sesim: 4
Takip: 4
Uyku Modu: 4
Fonksiyon Sayısı: 4
İçerdiği Aksesuar (2 Buz Kutusu): 4
Pervane Sayısı: 4
Otomatik salınım: 4
Tuş tipi (NAC): 4
Turbo mod: 4
Maksimum Nominal Güç: 4
80 cm: 4
Elektrik Tüketimi: 4
NTC Sensörü: 4
İndüksiyonlu Isıtma: 4
Kırılmaya Karşı Dayanıklı Cam Demlik: 4
Karaf Malzemesi: 4
Çıkarılabilir Filtre Tutucusu: 4
Su göstergesi: 4
Damlama Durdurma Fonksiyonu: 4
Dokunmatik Bas - Çek Teknolojisi: 4
Çay Filtresi: 4
Islak emiş özelliği: 4
Doğrama Kabı Kapasitesi: 4
Farklı Kızartma Ayarı: 4
Tekrar Isıtma: 4
Durdurma Düğmesi: 4
Manuel Ekmek Çıkarma Fonksiyonu: 4
Kırıntı Çekmecesi: 4
Turbo Modu: 4
Şarj göstergesi: 4
Şarjlı Kullanım Süresi (dk): 4
Detaylar için Saç düzeltici: 4
Koruyucu Kılıf: 4
Üreitici HD: 4
Saç Koruma Modu: 4
Rahatsız etme modu: 4
Uzaktan Kontrol (VC): 4
Toz Torbası Tipi: 4
Yükseklik algılama sensörü: 4
Otomatik Kireç Temizleme: 4
Taşınabilir Şişe: 4
185 cm: 3
73 cm: 3
146 cm: 3
Fırın Tipi: 3
Pişirme Bölmesi Hacmi (L): 3
Fırın İçi Aydınlatma (Üst Bölme): 3
Yuvarlak Tepsi Adedi: 3
Üst Isıtıcı: 3
Ana Şasi - Alt Isıtıcı: 3
Fan ve Üst Isıtıcı: 3
Sol Bölme: 3
Yumuşak Kapak Sistemi: 3
103 cm: 3
Et Probu: 3
Dokunmatik Ekran: 3
49 cm: 3
Hafıza: 3
119 cm: 3
RCA Girişler: 3
110 cm: 3
Kendini Temizleme: 3
Otomatik Mod: 3
Nominal Güç: 3
109 cm: 3
145 cm: 3
Dilim Sayısı: 3
Termostat: 3
Emniyet Sistemleri: 3
Fan: 3
Turbo Fonksiyonu: 3
Çekirdekten fincana kahve: 3
Temiz Su Kapasitesi: 3
Simit Isıtma: 3
Saç Kesme Uzunluk Ayarı: 3
Seyahat Kilidi: 3
Temizleme-Bakım Yağı: 3
Ambalaj: 3
Paketleme Birimi: 3
Ölçme Hassasiyeti (g): 3
Üstüne Çıkılınca Otomatik Çalışma: 3
Otomatik Çalışma: 3
Ölçü Birimi: 3
Şarj Ünitesi: 3
5 Kat Seramik Kaplama: 3
Gösterge: 3
Kaplama Malzemesi: 3
Katlanabilir Boru: 3
Filtre Çeşidi: 3
Ses Paketi: 3
Aksesuar temizleme aparatı: 3
Mobil Uygulama: 3
Su tankı kapasitesi: 3
Buhar Hortum Uzunluğu: 3
Kordon Uzunluğu: 3
Kilitleme Sistemi: 3
Su Tankı Çıkma Özelliği: 3
Kullanım Esnasında Su Doldurma Özelliği: 3
Hız Kademesi Ayarı: 3
Parçalama Bıçağı: 3
Kaydırmaz Taban: 3
178 cm: 2
194 cm: 2
191 cm: 2
111 cm: 2
Tencere Kapasitesi: 2
Basınç Kontrolü: 2
Sıcak Tutma: 2
Tandır Aparatı: 2
Sıcaklık Ayarlama: 2
Poşe Fonksiyonu: 2
Düdüklü Et / Tavuk Fonksiyonu: 2
Tarif Kitabı: 2
Yahni / Tencere Yemeği Fonksiyonu: 2
Sote Fonksiyonu: 2
Buharda Pilav Fonksiyonu: 2
Düdüklü Baklagiller Fonksiyonu: 2
Reçel Fonksiyonu: 2
Kısık Ateşte Pişirme Fonksiyonu: 2
Yoğurt Fonksiyonu: 2
Tandır Fonksiyonu: 2
93 cm: 2
Adaptör Damacana Kapağı: 2
Sıcak su tank kapasitesi (L): 2
Sıcak Su Derecesi Aralığı: 2
Isıtma Kapasitesi (ml): 2
Açma / Kapama Işığı: 2
92 cm: 2
79 cm: 2
72 cm: 2
Yere Işık Yansıtma Özelliği: 2
Düşük Sıcaklıkta Pişirme: 2
Paket İçeriği: 2
88 cm: 2
46 cm: 2
97 cm: 2
Salınım Açısı (yukarı-aşağı ±5: 2
RPM (düşük/orta/yüksek): 2
Kanat Çapı: 2
Minimum ses seviyesi: 2
180 cm: 2
24 Saat Programlama: 2
Ekran Led Rengi: 2
Salınım Fonsiyonu: 2
Lejyonella Koruma Fonksiyonu: 2
Otomatik Arıza Teşhis Sistemi: 2
Manuel demleme ayarı: 2
Aroma Fonksiyonu: 2
Öğütme ünitesi: 2
Çekirdek Kahve Hazne Kapasitesi: 2
Kahve Öğütücü Kademesi: 2
Dijital Saatli LCD Ekran: 2
Progranlanabilen baslangıç zamanı: 2
Bıçak: 2
Susuz Çalışmaya Karşıma Koruma Sistemi: 2
Rezistans Tipi: 2
Kirli Su Kapasitesi: 2
Akıllı Bitirme Özelliği: 2
Haznelerini Eşleme Özelliği: 2
Isıtma Rafı: 2
Kalın fön başlığı: 2
İnce fön başlığı: 2
Sınıflandırma: 2
Maksimum Ölçüm Kapasitesi: 2
Düşük Pil Göstergesi: 2
Ölçüm Değeri Seçme Düğmesi: 2
Büyük basma alanı: 2
Şarj Göstergesi (2): 2
Kesim uzunluğu(mm): 2
Kullanım Süresi: 2
Hafıza Fonksiyonu: 2
Lidar Sensörü: 2
Etkinlik Alan Yarıçapı: 2
Yeşil Led Teknolojisi: 2
122 cm: 2
Yedek Sünger Filtre (Yıkanabilir): 2
Buhar sensörü: 2
Aksesuar Çıkarma Düğmesi: 2
Dik Saklama İmkanı: 2
Çırpma, Karıştırma Aparatları: 2
Paslanmaz Çelik Hamur Kancası: 2
Tek Kişilik Yoğurt Kabı Malzemesi: 2
Tek Kişilik Yoğurt Kap Sayısı: 2
Dijital Kontrol Ekranı: 2
Yoğurt Kabı Malzemesi: 2
Tek Kişilik Yoğurt Kabı: 2
Mavi Işık Teknolojisi: 1
179 cm: 1
160 cm: 1
172 cm: 1
Hareketli Gövde Rafı: 1
81 cm: 1
156 cm: 1
102 cm: 1
129 cm: 1
Yıka-kurut çevriminde ağırlıklı su tüketimi (W_wd) (L/cycle) (EU_2021_EP): 1
Eco 40-60 programında sıkma sırasındaki ses gücü sınıfı (EU_2021_EP) (WD): 1
Yıka-kurut çeviriminde enerji verimlilik sınıfı (EU_2021_EP): 1
Zaman Programlama: 1
Taşma Emniyeti: 1
Kurutma Teknolojisi: 1
program-14: 1
Yıkama Performansı: 1
Kombi (Konveksiyon) Özelliği: 1
Otomatik Pişirme (3): 1
Homedirect Uygulaması: 1
HomeDirect Tarif Kütüphanesi: 1
Adım Adım Rehberli Pişirme: 1
Arka Göz: 1
Ön Bölme: 1
Maksimum Ses Seviyesi (dBA): 1
53 cm: 1
232 cm: 1
233 cm: 1
Yıllık Su Tüketimi (L): 1
Buharlı Fanlı Pişirme: 1
Buharlı Pişirme + Turbo + Fan: 1
Pizza Buharlı: 1
Buharlı Pişirme + Statik + Fan: 1
Buharlı Pişirme + Turbo + Alt ısıtıcı: 1
Ankastre Kiti İhtiyacı: 1
Diğer Özellikler (ICTA): 1
Kutu İçeriği: 1
Aksesuar Tipi: 1
Connection / Power: 1
Bağlantı Tipi: 1
Oyun Desteği: 1
3G: 1
Sim Kar ile Bağlantı: 1
120 cm: 1
Banka Uygulamaları: 1
Yemek Kartı Uygulaması: 1
Tuş Takımı: 1
Günlük Satış Raporu: 1
PLU Satış Raporu: 1

In [220]:
# 1. frekanslar sözlüğündeki anahtarlardan isminde sayı (rakam) geçenleri filtreliyoruz
sayi_iceren_anahtarlar = [key for key in frekanslar.keys() if any(c.isdigit() for c in str(key))]

print(f"İsminde sayı geçen toplam {len(sayi_iceren_anahtarlar)} özellik bulundu.\n")
print("=" * 40)

# 2. Sadece bu şüpheli anahtarların aldıkları değerleri ve frekanslarını yazdırıyoruz
for anahtar in sayi_iceren_anahtarlar:
    # df içindeki sözlükleri dönüp, sadece bu anahtara sahip olanların değerlerini çekiyoruz
    degerler = [d[anahtar] for d in df['teknik_ozellikler_dict'] if anahtar in d]
    
    # Değerlerin frekansını çıkarıyoruz (Counter'ı zaten import etmiştik)
    deger_frekanslari = Counter(degerler)
    
    # Çıktıyı yazdırıyoruz
    print(f"ÖZELLİK ADI: '{anahtar}' (Toplam {len(degerler)} üründe var)")
    for deger, adet in deger_frekanslari.most_common():
        print(f"   -> Aldığı Değer: {deger} (Frekans: {adet})")
    print("-" * 40)

İsminde sayı geçen toplam 186 özellik bulundu.

========================================
ÖZELLİK ADI: '76 cm' (Toplam 23 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 22)
   -> Aldığı Değer: Genişlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '83 cm' (Toplam 10 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 10)
----------------------------------------
ÖZELLİK ADI: '193 cm' (Toplam 4 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 4)
----------------------------------------
ÖZELLİK ADI: 'Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP)' (Toplam 78 üründe var)
   -> Aldığı Değer: 0.48 (Frekans: 9)
   -> Aldığı Değer: 0.438 (Frekans: 6)
   -> Aldığı Değer: 0.384 (Frekans: 4)
   -> Aldığı Değer: 0.38 (Frekans: 4)
   -> Aldığı Değer: 0.4 (Frekans: 3)
   -> Aldığı Değer: 0.49 (Frekans: 3)
   -> Aldığı Değer: 0.447 (Frekans: 3)
   -> Aldığı Değer: 0.579 (Frekans: 3)
   -> Aldığı Değer: 0.51 (Frekans: 3)
   -> Aldığı Değer: 0.403 (Frekans: 3)
   -> Aldığı Değer: 0.349 (Frekans: 3)
   -> Aldığı Değer: 0.449 (Frekans: 2)
   -> Aldığı Değer: 0.46 (Frekans: 2)
   -> Aldığı Değer: 0.463 (Frekans: 2)
   -> Aldığı Değer: 0.494 (Frekans: 2)
   -> Aldığı Değer: 0.34 (Frekans: 2)
   -> Aldığı Değer: 0.382 (Frekans: 2)
   -> Aldığı Değer: 0.331 (Frekans: 1)
   -> Aldığı Değer: 0.451 (Frekans: 1)
   -> Aldığı Değer: 0.18 (Frekans: 1)
   -> Aldığı Değer: 0.178 (Frekans: 1)
   -> Aldığı Değer: 0.146 (Frekans: 1)
   -> Aldığı Değer: 0.506 (Frekans: 1)
   -> Aldığı Değer: 0.264 (Frekans: 1)
   -> Aldığı Değer: 0.379 (Frekans: 1)
   -> Aldığı Değer: 0.36 (Frekans: 1)
   -> Aldığı Değer: 0.311 (Frekans: 1)
   -> Aldığı Değer: 0.321 (Frekans: 1)
   -> Aldığı Değer: 0.348 (Frekans: 1)
   -> Aldığı Değer: 0.262 (Frekans: 1)
   -> Aldığı Değer: 0.378 (Frekans: 1)
   -> Aldığı Değer: 0.274 (Frekans: 1)
   -> Aldığı Değer: 0.377 (Frekans: 1)
   -> Aldığı Değer: 0.293 (Frekans: 1)
   -> Aldığı Değer: 0.346 (Frekans: 1)
   -> Aldığı Değer: 0.284 (Frekans: 1)
   -> Aldığı Değer: 0.415 (Frekans: 1)
   -> Aldığı Değer: 0.394 (Frekans: 1)
   -> Aldığı Değer: 0.258 (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '78 cm' (Toplam 10 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 10)
----------------------------------------
ÖZELLİK ADI: '188 cm' (Toplam 13 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 13)
----------------------------------------
ÖZELLİK ADI: '187 cm' (Toplam 24 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 24)
----------------------------------------
ÖZELLİK ADI: '75 cm' (Toplam 26 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 22)
   -> Aldığı Değer: Genişlik (Frekans: 4)
----------------------------------------
ÖZELLİK ADI: '70 cm' (Toplam 26 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 21)
   -> Aldığı Değer: Yükseklik (Frekans: 3)
   -> Aldığı Değer: Derinlik (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '66 cm' (Toplam 4 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 4)
----------------------------------------
ÖZELLİK ADI: '185 cm' (Toplam 3 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 3)
----------------------------------------
ÖZELLİK ADI: '73 cm' (Toplam 3 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 2)
   -> Aldığı Değer: Derinlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '74 cm' (Toplam 6 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 6)
----------------------------------------
ÖZELLİK ADI: '186 cm' (Toplam 5 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 5)
----------------------------------------
ÖZELLİK ADI: '182 cm' (Toplam 5 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 5)
----------------------------------------
ÖZELLİK ADI: '71 cm' (Toplam 10 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 10)
----------------------------------------
ÖZELLİK ADI: '91 cm' (Toplam 6 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 5)
   -> Aldığı Değer: Yükseklik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '179 cm' (Toplam 1 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '59 cm' (Toplam 43 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 38)
   -> Aldığı Değer: Derinlik (Frekans: 5)
----------------------------------------
ÖZELLİK ADI: '54 cm' (Toplam 12 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 11)
   -> Aldığı Değer: Derinlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '84 cm' (Toplam 17 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 14)
   -> Aldığı Değer: Yükseklik (Frekans: 3)
----------------------------------------
ÖZELLİK ADI: '50 cm' (Toplam 6 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 3)
   -> Aldığı Değer: Genişlik (Frekans: 3)
----------------------------------------
ÖZELLİK ADI: '48 cm' (Toplam 8 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 5)
   -> Aldığı Değer: Yükseklik (Frekans: 2)
   -> Aldığı Değer: Derinlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '82 cm' (Toplam 14 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 13)
   -> Aldığı Değer: Genişlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '55 cm' (Toplam 10 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 10)
----------------------------------------
ÖZELLİK ADI: '60 cm' (Toplam 165 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 139)
   -> Aldığı Değer: Yükseklik (Frekans: 26)
----------------------------------------
ÖZELLİK ADI: '160 cm' (Toplam 1 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '178 cm' (Toplam 2 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '171 cm' (Toplam 6 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 6)
----------------------------------------
ÖZELLİK ADI: '172 cm' (Toplam 1 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '69 cm' (Toplam 5 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 4)
   -> Aldığı Değer: Genişlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '194 cm' (Toplam 2 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '81 cm' (Toplam 1 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '191 cm' (Toplam 2 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '58 cm' (Toplam 23 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 16)
   -> Aldığı Değer: Genişlik (Frekans: 4)
   -> Aldığı Değer: Yükseklik (Frekans: 3)
----------------------------------------
ÖZELLİK ADI: '146 cm' (Toplam 3 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 3)
----------------------------------------
ÖZELLİK ADI: '86 cm' (Toplam 6 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 5)
   -> Aldığı Değer: Derinlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '68 cm' (Toplam 4 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 2)
   -> Aldığı Değer: Yükseklik (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '156 cm' (Toplam 1 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '64 cm' (Toplam 11 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 8)
   -> Aldığı Değer: Derinlik (Frekans: 3)
----------------------------------------
ÖZELLİK ADI: '102 cm' (Toplam 1 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '111 cm' (Toplam 2 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '129 cm' (Toplam 1 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '85 cm' (Toplam 64 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 64)
----------------------------------------
ÖZELLİK ADI: 'Program-10' (Toplam 34 üründe var)
   -> Aldığı Değer: Buhar Terapi (Frekans: 18)
   -> Aldığı Değer: Hijyenik Kurutma (Frekans: 7)
   -> Aldığı Değer: Yorgan (Frekans: 5)
   -> Aldığı Değer: Açık Hava/Spor (Goretex) (Frekans: 2)
   -> Aldığı Değer: Perde (Frekans: 1)
   -> Aldığı Değer: Sentetik Kurutma (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-11' (Toplam 33 üründe var)
   -> Aldığı Değer: Hijyen+ (Frekans: 9)
   -> Aldığı Değer: Gömlek (Frekans: 7)
   -> Aldığı Değer: Yorgan/ Nevresim (Frekans: 6)
   -> Aldığı Değer: Ekspres 30' (Frekans: 3)
   -> Aldığı Değer: Açık Hava/ Spor (Frekans: 2)
   -> Aldığı Değer: Havlu (Frekans: 2)
   -> Aldığı Değer: Down Wear / Single Duvet (Frekans: 1)
   -> Aldığı Değer: Leke Programı (Frekans: 1)
   -> Aldığı Değer: Xpress Super Short 50' (Frekans: 1)
   -> Aldığı Değer: 7 Kg Wash & Dry (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-12' (Toplam 34 üründe var)
   -> Aldığı Değer: Leke Programı (Frekans: 10)
   -> Aldığı Değer: Kot (Frekans: 9)
   -> Aldığı Değer: Hijyen+ (Frekans: 8)
   -> Aldığı Değer: Yorgan (Frekans: 2)
   -> Aldığı Değer: Bebek+ (Frekans: 1)
   -> Aldığı Değer: Açık Hava/Spor (Goretex) (Frekans: 1)
   -> Aldığı Değer: Gömlek (Frekans: 1)
   -> Aldığı Değer: Narin (Frekans: 1)
   -> Aldığı Değer: Antialerjik+ (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-13' (Toplam 34 üründe var)
   -> Aldığı Değer: Gömlek (Frekans: 17)
   -> Aldığı Değer: Buhar (Frekans: 6)
   -> Aldığı Değer: Karma (Frekans: 6)
   -> Aldığı Değer: Ekspres 30' (Frekans: 2)
   -> Aldığı Değer: Yorgan (Frekans: 1)
   -> Aldığı Değer: Kot (Frekans: 1)
   -> Aldığı Değer: Wash&Wear (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-15' (Toplam 34 üründe var)
   -> Aldığı Değer: Soğuk Yıkama (Frekans: 18)
   -> Aldığı Değer: Giyime Hazır (Gömlek) (Frekans: 6)
   -> Aldığı Değer: Ekspres 30' (Frekans: 5)
   -> Aldığı Değer: Hijyenik Havalandırma (Frekans: 2)
   -> Aldığı Değer: Havalandırma (Frekans: 1)
   -> Aldığı Değer: 5 kg @ 1 saat (Frekans: 1)
   -> Aldığı Değer: ColdWash (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-5' (Toplam 34 üründe var)
   -> Aldığı Değer: Delicates/Wool/HandWash (Frekans: 18)
   -> Aldığı Değer: Havlu (Frekans: 5)
   -> Aldığı Değer: Ekspres 30' (Frekans: 2)
   -> Aldığı Değer: Yünlü Kurutma (Frekans: 2)
   -> Aldığı Değer: Yorgan/ Nevresim (Frekans: 2)
   -> Aldığı Değer: Sessiz (Frekans: 2)
   -> Aldığı Değer: Hızlı Günlük (Frekans: 1)
   -> Aldığı Değer: Yünlü / Elde yıkama (Frekans: 1)
   -> Aldığı Değer: Narin (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-6' (Toplam 34 üründe var)
   -> Aldığı Değer: Duvet/DownWear (Frekans: 16)
   -> Aldığı Değer: Açık Hava/Spor (Goretex) (Frekans: 7)
   -> Aldığı Değer: Yorgan/ Nevresim (Frekans: 5)
   -> Aldığı Değer: Sessiz (Frekans: 2)
   -> Aldığı Değer: Down Wear (Frekans: 1)
   -> Aldığı Değer: Delicates/Wool/HandWash (Frekans: 1)
   -> Aldığı Değer: DarkWash/Jeans (Frekans: 1)
   -> Aldığı Değer: Gömlek (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-7' (Toplam 34 üründe var)
   -> Aldığı Değer: İndirilen Program (Frekans: 15)
   -> Aldığı Değer: Karma (Frekans: 10)
   -> Aldığı Değer: Tazeleme (Frekans: 5)
   -> Aldığı Değer: Açık Hava/Spor (Goretex) (Frekans: 2)
   -> Aldığı Değer: Narin (Frekans: 1)
   -> Aldığı Değer: Spin + Drain (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-1' (Toplam 34 üründe var)
   -> Aldığı Değer: Pamuklular (Frekans: 33)
   -> Aldığı Değer: Pamuklu (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-2' (Toplam 34 üründe var)
   -> Aldığı Değer: Eko 40-60 (Frekans: 19)
   -> Aldığı Değer: Pamuklu Ekonomik Kurutma (Frekans: 14)
   -> Aldığı Değer: Eco 40-60 (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-3' (Toplam 34 üründe var)
   -> Aldığı Değer: Sentetik (Frekans: 34)
----------------------------------------
ÖZELLİK ADI: 'Program-4' (Toplam 34 üründe var)
   -> Aldığı Değer: Hızlı 14' (Frekans: 18)
   -> Aldığı Değer: Karma (Frekans: 7)
   -> Aldığı Değer: Havlu (Frekans: 3)
   -> Aldığı Değer: Kot (Frekans: 2)
   -> Aldığı Değer: Yünlü Kurutma (Frekans: 2)
   -> Aldığı Değer: Cottons with Prewash (Frekans: 1)
   -> Aldığı Değer: Ekspres / Ekspres 14' (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-8' (Toplam 34 üründe var)
   -> Aldığı Değer: Sıkma Pompa (Frekans: 19)
   -> Aldığı Değer: Zaman Programları (Frekans: 14)
   -> Aldığı Değer: Durulama (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-9' (Toplam 34 üründe var)
   -> Aldığı Değer: Durulama (Frekans: 19)
   -> Aldığı Değer: Hijyenik Havalandırma (Frekans: 7)
   -> Aldığı Değer: Narin (Frekans: 5)
   -> Aldığı Değer: Kot (Frekans: 2)
   -> Aldığı Değer: Pamuklu Kurutma (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-14' (Toplam 32 üründe var)
   -> Aldığı Değer: Havalandırma (Buhar) (Frekans: 11)
   -> Aldığı Değer: Hijyenik Kurutma (Frekans: 7)
   -> Aldığı Değer: Akıllı Program (Frekans: 6)
   -> Aldığı Değer: Buharlı Tazeleme (Frekans: 6)
   -> Aldığı Değer: Hijyen+ (Frekans: 1)
   -> Aldığı Değer: Karma (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Su Tüketimi (1 Çevrim)' (Toplam 19 üründe var)
   -> Aldığı Değer: 49 L (Frekans: 5)
   -> Aldığı Değer: 51 L (Frekans: 3)
   -> Aldığı Değer: 52 L (Frekans: 3)
   -> Aldığı Değer: 44 L (Frekans: 2)
   -> Aldığı Değer: 56 L (Frekans: 2)
   -> Aldığı Değer: 54 L (Frekans: 2)
   -> Aldığı Değer: 40 L (Frekans: 1)
   -> Aldığı Değer: 45 L (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Enerji Tüketimi (100 Çevrim)' (Toplam 19 üründe var)
   -> Aldığı Değer: 49 kWh (Frekans: 5)
   -> Aldığı Değer: 51 kWh (Frekans: 3)
   -> Aldığı Değer: 46 kWh (Frekans: 3)
   -> Aldığı Değer: 44 kWh (Frekans: 2)
   -> Aldığı Değer: 54 kWh (Frekans: 2)
   -> Aldığı Değer: 53 kWh (Frekans: 2)
   -> Aldığı Değer: 24 kWh (Frekans: 1)
   -> Aldığı Değer: 47 kWh (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '63 cm' (Toplam 5 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 4)
   -> Aldığı Değer: Genişlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Fonksiyon 1' (Toplam 33 üründe var)
   -> Aldığı Değer: HijyenMax (Frekans: 21)
   -> Aldığı Değer: HomeWhiz (Frekans: 6)
   -> Aldığı Değer: Yarım Yük (Frekans: 3)
   -> Aldığı Değer: Steam Gloss (Frekans: 2)
   -> Aldığı Değer: Tablet Deterjan (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Fonksiyon 2' (Toplam 32 üründe var)
   -> Aldığı Değer: Ekstra Parlaklık/ Kurutma Fonksiyonu (Frekans: 15)
   -> Aldığı Değer: HijyenMax (App) (Frekans: 6)
   -> Aldığı Değer: Turbo Fonksiyonu (Frekans: 3)
   -> Aldığı Değer: MaxiDry (Frekans: 2)
   -> Aldığı Değer: DeepWash (Frekans: 2)
   -> Aldığı Değer: Zaman erteleme (Frekans: 1)
   -> Aldığı Değer: Ekstra Durulama (Frekans: 1)
   -> Aldığı Değer: SelfDry (Frekans: 1)
   -> Aldığı Değer: Yarım Yük (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Fonksiyon 3' (Toplam 28 üründe var)
   -> Aldığı Değer: Extra kurutma (App) (Frekans: 6)
   -> Aldığı Değer: DeepWash (Frekans: 6)
   -> Aldığı Değer: Zaman Erteleme (Frekans: 5)
   -> Aldığı Değer: Ekstra Durulama (Frekans: 5)
   -> Aldığı Değer: Call Service (Frekans: 4)
   -> Aldığı Değer: Turbo Fonksiyonu (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: 'Fonksiyon 4' (Toplam 22 üründe var)
   -> Aldığı Değer: Yarım Yük (Frekans: 11)
   -> Aldığı Değer: Download Cycle (Frekans: 5)
   -> Aldığı Değer: HomeWhiz (Frekans: 4)
   -> Aldığı Değer: Call Service (Frekans: 1)
   -> Aldığı Değer: Turbo Fonksiyonu (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Çıkarılabilir 3. Çekmece' (Toplam 7 üründe var)
   -> Aldığı Değer: Var (Frekans: 7)
----------------------------------------
ÖZELLİK ADI: '61 cm' (Toplam 23 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 12)
   -> Aldığı Değer: Derinlik (Frekans: 10)
   -> Aldığı Değer: Yükseklik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '65 cm' (Toplam 15 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 14)
   -> Aldığı Değer: Derinlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Yıka-kurut çevriminde ağırlıklı su tüketimi (W_wd) (L/cycle) (EU_2021_EP)' (Toplam 1 üründe var)
   -> Aldığı Değer: 78 L (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Eco 40-60 programında sıkma sırasındaki ses gücü sınıfı (EU_2021_EP) (WD)' (Toplam 1 üründe var)
   -> Aldığı Değer: C (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '67 cm' (Toplam 4 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 4)
----------------------------------------
ÖZELLİK ADI: 'Yıka-kurut çeviriminde enerji verimlilik sınıfı (EU_2021_EP)' (Toplam 1 üründe var)
   -> Aldığı Değer: D (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'program-14' (Toplam 1 üründe var)
   -> Aldığı Değer: Hygiene Therapy (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '29 cm' (Toplam 12 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 6)
   -> Aldığı Değer: Genişlik (Frekans: 3)
   -> Aldığı Değer: Derinlik (Frekans: 3)
----------------------------------------
ÖZELLİK ADI: '3D Pişirme' (Toplam 16 üründe var)
   -> Aldığı Değer: Var (Frekans: 16)
----------------------------------------
ÖZELLİK ADI: '56 cm' (Toplam 4 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 2)
   -> Aldığı Değer: Yükseklik (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '35 cm' (Toplam 37 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 20)
   -> Aldığı Değer: Derinlik (Frekans: 10)
   -> Aldığı Değer: Genişlik (Frekans: 7)
----------------------------------------
ÖZELLİK ADI: '52 cm' (Toplam 38 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 36)
   -> Aldığı Değer: Genişlik (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '6 cm' (Toplam 66 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 28)
   -> Aldığı Değer: Genişlik (Frekans: 28)
   -> Aldığı Değer: Derinlik (Frekans: 10)
----------------------------------------
ÖZELLİK ADI: '51 cm' (Toplam 18 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 15)
   -> Aldığı Değer: Yükseklik (Frekans: 2)
   -> Aldığı Değer: Genişlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '26 cm' (Toplam 25 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 20)
   -> Aldığı Değer: Yükseklik (Frekans: 4)
   -> Aldığı Değer: Genişlik (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '8 cm' (Toplam 164 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 107)
   -> Aldığı Değer: Yükseklik (Frekans: 34)
   -> Aldığı Değer: Derinlik (Frekans: 23)
----------------------------------------
ÖZELLİK ADI: '4 cm' (Toplam 139 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 68)
   -> Aldığı Değer: Yükseklik (Frekans: 49)
   -> Aldığı Değer: Genişlik (Frekans: 22)
----------------------------------------
ÖZELLİK ADI: '33 cm' (Toplam 23 üründe var)
   -> Aldığı Değer: Derinlik (Frekans: 15)
   -> Aldığı Değer: Genişlik (Frekans: 4)
   -> Aldığı Değer: Yükseklik (Frekans: 4)
----------------------------------------
ÖZELLİK ADI: '45 cm' (Toplam 14 üründe var)
   -> Aldığı Değer: Genişlik (Frekans: 8)
   -> Aldığı Değer: Derinlik (Frekans: 4)
   -> Aldığı Değer: Yükseklik (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '24 cm' (Toplam 42 üründe var)
   -> Aldığı Değer: Yükseklik (Frekans: 21)
   -> Aldığı Değer: Genişlik (Frekans: 13)
   -> Aldığı Değer: Derinlik (Frekans: 8)
----------------------------------------

In [221]:
def sozluk_duzelt(eski_sozluk):
    yeni_sozluk = {}
    
    # Ters yazıldığından emin olduğumuz değerleri bir listeye alalım
    ters_degerler = ['Derinlik', 'Genişlik', 'Yükseklik']
    
    for key, value in eski_sozluk.items():
        # Veri tiplerini string'e çevirip sağdaki/soldaki boşlukları temizleyelim (garanti olsun)
        temiz_value = str(value).strip()
        temiz_key = str(key).strip()
        
        # Eğer değer 'Derinlik', 'Genişlik' veya 'Yükseklik' ise yer değiştir
        if temiz_value in ters_degerler:
            yeni_sozluk[temiz_value] = temiz_key
        else:
            # Değilse (Program, Enerji vb.) hiçbir şeye dokunmadan yeni sözlüğe ekle
            yeni_sozluk[key] = value
            
    return yeni_sozluk

# Yeni ve temizlenmiş sözlüklerimizi aynı sütunun üzerine yazalım 
# (İstersen kaybetmemek için 'teknik_ozellikler_temiz' diye yeni bir sütun da açabilirsin)
df['teknik_ozellikler_dict'] = df['teknik_ozellikler_dict'].apply(sozluk_duzelt)

In [222]:
from collections import Counter

# 1. GÜNCEL sözlüklerden tüm anahtarları yeniden topluyoruz
guncel_anahtarlar = [key for d in df['teknik_ozellikler_dict'] for key in d.keys()]
guncel_frekanslar = Counter(guncel_anahtarlar)

# 2. İsminde sayı (rakam) geçen anahtarları YENİDEN filtreliyoruz
sayi_iceren_anahtarlar_kalan = [key for key in guncel_frekanslar.keys() if any(c.isdigit() for c in str(key))]

print(f"Temizlik sonrası isminde sayı geçen toplam {len(sayi_iceren_anahtarlar_kalan)} özellik kaldı.\n")
print("=" * 40)

# 3. Kalan anahtarların aldıkları değerleri ve frekanslarını yazdırıyoruz
for anahtar in sayi_iceren_anahtarlar_kalan:
    # df içindeki GÜNCEL sözlükleri dönüp, değerleri çekiyoruz
    degerler = [d[anahtar] for d in df['teknik_ozellikler_dict'] if anahtar in d]
    
    deger_frekanslari = Counter(degerler)
    
    print(f"ÖZELLİK ADI: '{anahtar}' (Toplam {len(degerler)} üründe var)")
    for deger, adet in deger_frekanslari.most_common():
        print(f"   -> Aldığı Değer: {deger} (Frekans: {adet})")
    print("-" * 40)

Temizlik sonrası isminde sayı geçen toplam 49 özellik kaldı.

========================================
ÖZELLİK ADI: 'Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP)' (Toplam 78 üründe var)
   -> Aldığı Değer: 0.48 (Frekans: 9)
   -> Aldığı Değer: 0.438 (Frekans: 6)
   -> Aldığı Değer: 0.384 (Frekans: 4)
   -> Aldığı Değer: 0.38 (Frekans: 4)
   -> Aldığı Değer: 0.4 (Frekans: 3)
   -> Aldığı Değer: 0.49 (Frekans: 3)
   -> Aldığı Değer: 0.447 (Frekans: 3)
   -> Aldığı Değer: 0.579 (Frekans: 3)
   -> Aldığı Değer: 0.51 (Frekans: 3)
   -> Aldığı Değer: 0.403 (Frekans: 3)
   -> Aldığı Değer: 0.349 (Frekans: 3)
   -> Aldığı Değer: 0.449 (Frekans: 2)
   -> Aldığı Değer: 0.46 (Frekans: 2)
   -> Aldığı Değer: 0.463 (Frekans: 2)
   -> Aldığı Değer: 0.494 (Frekans: 2)
   -> Aldığı Değer: 0.34 (Frekans: 2)
   -> Aldığı Değer: 0.382 (Frekans: 2)
   -> Aldığı Değer: 0.331 (Frekans: 1)
   -> Aldığı Değer: 0.451 (Frekans: 1)
   -> Aldığı Değer: 0.18 (Frekans: 1)
   -> Aldığı Değer: 0.178 (Frekans: 1)
   -> Aldığı Değer: 0.146 (Frekans: 1)
   -> Aldığı Değer: 0.506 (Frekans: 1)
   -> Aldığı Değer: 0.264 (Frekans: 1)
   -> Aldığı Değer: 0.379 (Frekans: 1)
   -> Aldığı Değer: 0.36 (Frekans: 1)
   -> Aldığı Değer: 0.311 (Frekans: 1)
   -> Aldığı Değer: 0.321 (Frekans: 1)
   -> Aldığı Değer: 0.348 (Frekans: 1)
   -> Aldığı Değer: 0.262 (Frekans: 1)
   -> Aldığı Değer: 0.378 (Frekans: 1)
   -> Aldığı Değer: 0.274 (Frekans: 1)
   -> Aldığı Değer: 0.377 (Frekans: 1)
   -> Aldığı Değer: 0.293 (Frekans: 1)
   -> Aldığı Değer: 0.346 (Frekans: 1)
   -> Aldığı Değer: 0.284 (Frekans: 1)
   -> Aldığı Değer: 0.415 (Frekans: 1)
   -> Aldığı Değer: 0.394 (Frekans: 1)
   -> Aldığı Değer: 0.258 (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-10' (Toplam 34 üründe var)
   -> Aldığı Değer: Buhar Terapi (Frekans: 18)
   -> Aldığı Değer: Hijyenik Kurutma (Frekans: 7)
   -> Aldığı Değer: Yorgan (Frekans: 5)
   -> Aldığı Değer: Açık Hava/Spor (Goretex) (Frekans: 2)
   -> Aldığı Değer: Perde (Frekans: 1)
   -> Aldığı Değer: Sentetik Kurutma (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-11' (Toplam 33 üründe var)
   -> Aldığı Değer: Hijyen+ (Frekans: 9)
   -> Aldığı Değer: Gömlek (Frekans: 7)
   -> Aldığı Değer: Yorgan/ Nevresim (Frekans: 6)
   -> Aldığı Değer: Ekspres 30' (Frekans: 3)
   -> Aldığı Değer: Açık Hava/ Spor (Frekans: 2)
   -> Aldığı Değer: Havlu (Frekans: 2)
   -> Aldığı Değer: Down Wear / Single Duvet (Frekans: 1)
   -> Aldığı Değer: Leke Programı (Frekans: 1)
   -> Aldığı Değer: Xpress Super Short 50' (Frekans: 1)
   -> Aldığı Değer: 7 Kg Wash & Dry (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-12' (Toplam 34 üründe var)
   -> Aldığı Değer: Leke Programı (Frekans: 10)
   -> Aldığı Değer: Kot (Frekans: 9)
   -> Aldığı Değer: Hijyen+ (Frekans: 8)
   -> Aldığı Değer: Yorgan (Frekans: 2)
   -> Aldığı Değer: Bebek+ (Frekans: 1)
   -> Aldığı Değer: Açık Hava/Spor (Goretex) (Frekans: 1)
   -> Aldığı Değer: Gömlek (Frekans: 1)
   -> Aldığı Değer: Narin (Frekans: 1)
   -> Aldığı Değer: Antialerjik+ (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-13' (Toplam 34 üründe var)
   -> Aldığı Değer: Gömlek (Frekans: 17)
   -> Aldığı Değer: Buhar (Frekans: 6)
   -> Aldığı Değer: Karma (Frekans: 6)
   -> Aldığı Değer: Ekspres 30' (Frekans: 2)
   -> Aldığı Değer: Yorgan (Frekans: 1)
   -> Aldığı Değer: Kot (Frekans: 1)
   -> Aldığı Değer: Wash&Wear (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-15' (Toplam 34 üründe var)
   -> Aldığı Değer: Soğuk Yıkama (Frekans: 18)
   -> Aldığı Değer: Giyime Hazır (Gömlek) (Frekans: 6)
   -> Aldığı Değer: Ekspres 30' (Frekans: 5)
   -> Aldığı Değer: Hijyenik Havalandırma (Frekans: 2)
   -> Aldığı Değer: Havalandırma (Frekans: 1)
   -> Aldığı Değer: 5 kg @ 1 saat (Frekans: 1)
   -> Aldığı Değer: ColdWash (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-5' (Toplam 34 üründe var)
   -> Aldığı Değer: Delicates/Wool/HandWash (Frekans: 18)
   -> Aldığı Değer: Havlu (Frekans: 5)
   -> Aldığı Değer: Ekspres 30' (Frekans: 2)
   -> Aldığı Değer: Yünlü Kurutma (Frekans: 2)
   -> Aldığı Değer: Yorgan/ Nevresim (Frekans: 2)
   -> Aldığı Değer: Sessiz (Frekans: 2)
   -> Aldığı Değer: Hızlı Günlük (Frekans: 1)
   -> Aldığı Değer: Yünlü / Elde yıkama (Frekans: 1)
   -> Aldığı Değer: Narin (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-6' (Toplam 34 üründe var)
   -> Aldığı Değer: Duvet/DownWear (Frekans: 16)
   -> Aldığı Değer: Açık Hava/Spor (Goretex) (Frekans: 7)
   -> Aldığı Değer: Yorgan/ Nevresim (Frekans: 5)
   -> Aldığı Değer: Sessiz (Frekans: 2)
   -> Aldığı Değer: Down Wear (Frekans: 1)
   -> Aldığı Değer: Delicates/Wool/HandWash (Frekans: 1)
   -> Aldığı Değer: DarkWash/Jeans (Frekans: 1)
   -> Aldığı Değer: Gömlek (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-7' (Toplam 34 üründe var)
   -> Aldığı Değer: İndirilen Program (Frekans: 15)
   -> Aldığı Değer: Karma (Frekans: 10)
   -> Aldığı Değer: Tazeleme (Frekans: 5)
   -> Aldığı Değer: Açık Hava/Spor (Goretex) (Frekans: 2)
   -> Aldığı Değer: Narin (Frekans: 1)
   -> Aldığı Değer: Spin + Drain (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-1' (Toplam 34 üründe var)
   -> Aldığı Değer: Pamuklular (Frekans: 33)
   -> Aldığı Değer: Pamuklu (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-2' (Toplam 34 üründe var)
   -> Aldığı Değer: Eko 40-60 (Frekans: 19)
   -> Aldığı Değer: Pamuklu Ekonomik Kurutma (Frekans: 14)
   -> Aldığı Değer: Eco 40-60 (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-3' (Toplam 34 üründe var)
   -> Aldığı Değer: Sentetik (Frekans: 34)
----------------------------------------
ÖZELLİK ADI: 'Program-4' (Toplam 34 üründe var)
   -> Aldığı Değer: Hızlı 14' (Frekans: 18)
   -> Aldığı Değer: Karma (Frekans: 7)
   -> Aldığı Değer: Havlu (Frekans: 3)
   -> Aldığı Değer: Kot (Frekans: 2)
   -> Aldığı Değer: Yünlü Kurutma (Frekans: 2)
   -> Aldığı Değer: Cottons with Prewash (Frekans: 1)
   -> Aldığı Değer: Ekspres / Ekspres 14' (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-8' (Toplam 34 üründe var)
   -> Aldığı Değer: Sıkma Pompa (Frekans: 19)
   -> Aldığı Değer: Zaman Programları (Frekans: 14)
   -> Aldığı Değer: Durulama (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-9' (Toplam 34 üründe var)
   -> Aldığı Değer: Durulama (Frekans: 19)
   -> Aldığı Değer: Hijyenik Havalandırma (Frekans: 7)
   -> Aldığı Değer: Narin (Frekans: 5)
   -> Aldığı Değer: Kot (Frekans: 2)
   -> Aldığı Değer: Pamuklu Kurutma (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Program-14' (Toplam 32 üründe var)
   -> Aldığı Değer: Havalandırma (Buhar) (Frekans: 11)
   -> Aldığı Değer: Hijyenik Kurutma (Frekans: 7)
   -> Aldığı Değer: Akıllı Program (Frekans: 6)
   -> Aldığı Değer: Buharlı Tazeleme (Frekans: 6)
   -> Aldığı Değer: Hijyen+ (Frekans: 1)
   -> Aldığı Değer: Karma (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Su Tüketimi (1 Çevrim)' (Toplam 19 üründe var)
   -> Aldığı Değer: 49 L (Frekans: 5)
   -> Aldığı Değer: 51 L (Frekans: 3)
   -> Aldığı Değer: 52 L (Frekans: 3)
   -> Aldığı Değer: 44 L (Frekans: 2)
   -> Aldığı Değer: 56 L (Frekans: 2)
   -> Aldığı Değer: 54 L (Frekans: 2)
   -> Aldığı Değer: 40 L (Frekans: 1)
   -> Aldığı Değer: 45 L (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Enerji Tüketimi (100 Çevrim)' (Toplam 19 üründe var)
   -> Aldığı Değer: 49 kWh (Frekans: 5)
   -> Aldığı Değer: 51 kWh (Frekans: 3)
   -> Aldığı Değer: 46 kWh (Frekans: 3)
   -> Aldığı Değer: 44 kWh (Frekans: 2)
   -> Aldığı Değer: 54 kWh (Frekans: 2)
   -> Aldığı Değer: 53 kWh (Frekans: 2)
   -> Aldığı Değer: 24 kWh (Frekans: 1)
   -> Aldığı Değer: 47 kWh (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Fonksiyon 1' (Toplam 33 üründe var)
   -> Aldığı Değer: HijyenMax (Frekans: 21)
   -> Aldığı Değer: HomeWhiz (Frekans: 6)
   -> Aldığı Değer: Yarım Yük (Frekans: 3)
   -> Aldığı Değer: Steam Gloss (Frekans: 2)
   -> Aldığı Değer: Tablet Deterjan (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Fonksiyon 2' (Toplam 32 üründe var)
   -> Aldığı Değer: Ekstra Parlaklık/ Kurutma Fonksiyonu (Frekans: 15)
   -> Aldığı Değer: HijyenMax (App) (Frekans: 6)
   -> Aldığı Değer: Turbo Fonksiyonu (Frekans: 3)
   -> Aldığı Değer: MaxiDry (Frekans: 2)
   -> Aldığı Değer: DeepWash (Frekans: 2)
   -> Aldığı Değer: Zaman erteleme (Frekans: 1)
   -> Aldığı Değer: Ekstra Durulama (Frekans: 1)
   -> Aldığı Değer: SelfDry (Frekans: 1)
   -> Aldığı Değer: Yarım Yük (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Fonksiyon 3' (Toplam 28 üründe var)
   -> Aldığı Değer: Extra kurutma (App) (Frekans: 6)
   -> Aldığı Değer: DeepWash (Frekans: 6)
   -> Aldığı Değer: Zaman Erteleme (Frekans: 5)
   -> Aldığı Değer: Ekstra Durulama (Frekans: 5)
   -> Aldığı Değer: Call Service (Frekans: 4)
   -> Aldığı Değer: Turbo Fonksiyonu (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: 'Fonksiyon 4' (Toplam 22 üründe var)
   -> Aldığı Değer: Yarım Yük (Frekans: 11)
   -> Aldığı Değer: Download Cycle (Frekans: 5)
   -> Aldığı Değer: HomeWhiz (Frekans: 4)
   -> Aldığı Değer: Call Service (Frekans: 1)
   -> Aldığı Değer: Turbo Fonksiyonu (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Çıkarılabilir 3. Çekmece' (Toplam 7 üründe var)
   -> Aldığı Değer: Var (Frekans: 7)
----------------------------------------
ÖZELLİK ADI: 'Yıka-kurut çevriminde ağırlıklı su tüketimi (W_wd) (L/cycle) (EU_2021_EP)' (Toplam 1 üründe var)
   -> Aldığı Değer: 78 L (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Eco 40-60 programında sıkma sırasındaki ses gücü sınıfı (EU_2021_EP) (WD)' (Toplam 1 üründe var)
   -> Aldığı Değer: C (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Yıka-kurut çeviriminde enerji verimlilik sınıfı (EU_2021_EP)' (Toplam 1 üründe var)
   -> Aldığı Değer: D (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'program-14' (Toplam 1 üründe var)
   -> Aldığı Değer: Hygiene Therapy (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '3D Pişirme' (Toplam 16 üründe var)
   -> Aldığı Değer: Var (Frekans: 16)
----------------------------------------
ÖZELLİK ADI: 'Otomatik Pişirme (3)' (Toplam 1 üründe var)
   -> Aldığı Değer: Var (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Yoğun Emiş Gücü (m³/h)' (Toplam 17 üründe var)
   -> Aldığı Değer: 720 m³/h (Frekans: 10)
   -> Aldığı Değer: 850 m³/h (Frekans: 3)
   -> Aldığı Değer: 712 m³/h (Frekans: 2)
   -> Aldığı Değer: 710 m³/h (Frekans: 1)
   -> Aldığı Değer: 830 m³/h (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre)' (Toplam 40 üründe var)
   -> Aldığı Değer: 44-...-60-70 (Frekans: 10)
   -> Aldığı Değer: 43-...-56 (Frekans: 5)
   -> Aldığı Değer: 53 - 55 - 64 dBA (Frekans: 4)
   -> Aldığı Değer: 38-...-59-74 (Frekans: 3)
   -> Aldığı Değer: 46-...-59 (Frekans: 3)
   -> Aldığı Değer: 50-...-69 (Frekans: 3)
   -> Aldığı Değer: 43-...-58-69 (Frekans: 2)
   -> Aldığı Değer: 52 - TBA - 62 (Frekans: 2)
   -> Aldığı Değer: 48-...-68 (Frekans: 1)
   -> Aldığı Değer: 43-...-60-71 (Frekans: 1)
   -> Aldığı Değer: 44-...-60-74 (Frekans: 1)
   -> Aldığı Değer: 49-...-62 (Frekans: 1)
   -> Aldığı Değer: 53-..-64 (Frekans: 1)
   -> Aldığı Değer: 50-...-64 (Frekans: 1)
   -> Aldığı Değer: 49 - 52 - 61 dBA (Frekans: 1)
   -> Aldığı Değer: 51 - 66 dBA (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '3G' (Toplam 1 üründe var)
   -> Aldığı Değer: var ( 5G) (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '2.Arka Kamera' (Toplam 174 üründe var)
   -> Aldığı Değer: Var (Frekans: 174)
----------------------------------------
ÖZELLİK ADI: '3 cihazı aynı anda şarj edebilme' (Toplam 9 üründe var)
   -> Aldığı Değer: Var (Frekans: 7)
   -> Aldığı Değer: 5 cihazı aynı anda şarj edebilme (Frekans: 1)
   -> Aldığı Değer: Üç cihazı aynı anda şarj eder (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '4 Yönlü Otomatik Hava Kontrolü' (Toplam 13 üründe var)
   -> Aldığı Değer: Var (Frekans: 13)
----------------------------------------
ÖZELLİK ADI: '2 Yönlü Otomatik Hava Kontrolü' (Toplam 1 üründe var)
   -> Aldığı Değer: Var (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Güç (W) (9)' (Toplam 11 üründe var)
   -> Aldığı Değer: 30 W (Frekans: 3)
   -> Aldığı Değer: 100 W (Frekans: 2)
   -> Aldığı Değer: 50 W (Frekans: 2)
   -> Aldığı Değer: 200 W (Frekans: 1)
   -> Aldığı Değer: 65 W (Frekans: 1)
   -> Aldığı Değer: 20 W (Frekans: 1)
   -> Aldığı Değer: 55 W (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'İçerdiği Aksesuar (2 Buz Kutusu)' (Toplam 4 üründe var)
   -> Aldığı Değer: Var (Frekans: 4)
----------------------------------------
ÖZELLİK ADI: 'Salınım Açısı (yukarı-aşağı ±5' (Toplam 2 üründe var)
   -> Aldığı Değer: 135 (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '24 Saat Programlama' (Toplam 2 üründe var)
   -> Aldığı Değer: Var (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '3 Yollu Vana Blokaj Sistemi' (Toplam 8 üründe var)
   -> Aldığı Değer: Var (Frekans: 8)
----------------------------------------
ÖZELLİK ADI: 'Temizleme fırçası (2)' (Toplam 1 üründe var)
   -> Aldığı Değer: Var (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '360° Dönebilen Kablosuz Kullanım' (Toplam 6 üründe var)
   -> Aldığı Değer: Var (Frekans: 6)
----------------------------------------
ÖZELLİK ADI: 'Dijital Ekran (3)' (Toplam 1 üründe var)
   -> Aldığı Değer: Evet (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Renk (41)' (Toplam 5 üründe var)
   -> Aldığı Değer: Siyah (Frekans: 5)
----------------------------------------
ÖZELLİK ADI: 'Şarj Göstergesi (2)' (Toplam 2 üründe var)
   -> Aldığı Değer: LCD (Frekans: 1)
   -> Aldığı Değer: LED (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '5 Kat Seramik Kaplama' (Toplam 3 üründe var)
   -> Aldığı Değer: Var (Frekans: 3)
----------------------------------------
ÖZELLİK ADI: '360° Derece Dönebilen Hortum' (Toplam 7 üründe var)
   -> Aldığı Değer: Var (Frekans: 7)
----------------------------------------
ÖZELLİK ADI: '4 Kanatlı Paslanmaz Çelik Bıçak' (Toplam 1 üründe var)
   -> Aldığı Değer: Var (Frekans: 1)
----------------------------------------

In [223]:
def program_fonksiyon_liste_yap(eski_sozluk):
    yeni_sozluk = {}
    programlar = []
    fonksiyonlar = []
    
    for key, value in eski_sozluk.items():
        # Anahtarı küçük harfe çevirip boşluklarını silelim
        temiz_key = str(key).strip().lower()
        
        # Eğer anahtarın İÇİNDE 'program' geçiyorsa listeye ekle
        if 'program' in temiz_key:
            programlar.append(str(value).strip())
            
        # Eğer anahtarın İÇİNDE 'fonksiyon' geçiyorsa listeye ekle
        elif 'fonksiyon' in temiz_key:
            fonksiyonlar.append(str(value).strip())
            
        # İkisi de değilse aynen bırak
        else:
            yeni_sozluk[key] = value
            
    # Eğer programlar listesi boş değilse, doğrudan liste formatında sözlüğe ekle
    if programlar:
        yeni_sozluk['Programlar'] = programlar
        
    # Eğer fonksiyonlar listesi boş değilse, doğrudan liste formatında sözlüğe ekle
    if fonksiyonlar:
        yeni_sozluk['Fonksiyonlar'] = fonksiyonlar
        
    return yeni_sozluk

# Fonksiyonu DataFrame'e uygulayalım
df['teknik_ozellikler_dict'] = df['teknik_ozellikler_dict'].apply(program_fonksiyon_liste_yap)

In [224]:
from collections import Counter

# --- BÖLÜM 1: İÇİNDE SAYI KALAN ANAHTARLARIN KONTROLÜ ---
guncel_anahtarlar = [key for d in df['teknik_ozellikler_dict'] for key in d.keys()]
guncel_frekanslar = Counter(guncel_anahtarlar)

sayi_iceren_anahtarlar_kalan = [key for key in guncel_frekanslar.keys() if any(c.isdigit() for c in str(key))]

print(f"Temizlik sonrası isminde sayı geçen toplam {len(sayi_iceren_anahtarlar_kalan)} özellik kaldı.\n")
print("=" * 40)

for anahtar in sayi_iceren_anahtarlar_kalan:
    degerler = []
    for d in df['teknik_ozellikler_dict']:
        if anahtar in d:
            val = d[anahtar]
            # Eğer değer bir liste ise Counter hata vermesin diye tuple'a çeviriyoruz (garanti olsun)
            if isinstance(val, list):
                val = tuple(val)
            degerler.append(val)
    
    deger_frekanslari = Counter(degerler)
    
    print(f"ÖZELLİK ADI: '{anahtar}' (Toplam {len(degerler)} üründe var)")
    # Çıktı çok uzamasın diye en sık geçen ilk 5 değeri gösteriyoruz, istersen .most_common() içini boş bırakabilirsin
    for deger, adet in deger_frekanslari.most_common(5):
        print(f"   -> Aldığı Değer: {deger} (Frekans: {adet})")
    print("-" * 40)


# --- BÖLÜM 2: YENİ 'Programlar' VE 'Fonksiyonlar' LİSTELERİNİN KONTROLÜ ---
print("\n\n" + "=" * 50)
print("YENİ OLUŞTURULAN 'Programlar' VE 'Fonksiyonlar' KONTROLÜ")
print("=" * 50)

ornek_sayisi = 0
for i, d in enumerate(df['teknik_ozellikler_dict']):
    # İçinde Programlar veya Fonksiyonlar anahtarı olan ilk 5 ürünü yazdıralım
    if 'Programlar' in d or 'Fonksiyonlar' in d:
        print(f"Satır Index: {df.index[i]}")
        if 'Programlar' in d:
            print(f"  Programlar: {d['Programlar']}")
        if 'Fonksiyonlar' in d:
            print(f"  Fonksiyonlar: {d['Fonksiyonlar']}")
        print("-" * 30)
        
        ornek_sayisi += 1
        if ornek_sayisi == 5:
            break

Temizlik sonrası isminde sayı geçen toplam 27 özellik kaldı.

========================================
ÖZELLİK ADI: 'Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP)' (Toplam 78 üründe var)
   -> Aldığı Değer: 0.48 (Frekans: 9)
   -> Aldığı Değer: 0.438 (Frekans: 6)
   -> Aldığı Değer: 0.384 (Frekans: 4)
   -> Aldığı Değer: 0.38 (Frekans: 4)
   -> Aldığı Değer: 0.4 (Frekans: 3)
----------------------------------------
ÖZELLİK ADI: 'Su Tüketimi (1 Çevrim)' (Toplam 19 üründe var)
   -> Aldığı Değer: 49 L (Frekans: 5)
   -> Aldığı Değer: 51 L (Frekans: 3)
   -> Aldığı Değer: 52 L (Frekans: 3)
   -> Aldığı Değer: 44 L (Frekans: 2)
   -> Aldığı Değer: 56 L (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: 'Enerji Tüketimi (100 Çevrim)' (Toplam 19 üründe var)
   -> Aldığı Değer: 49 kWh (Frekans: 5)
   -> Aldığı Değer: 51 kWh (Frekans: 3)
   -> Aldığı Değer: 46 kWh (Frekans: 3)
   -> Aldığı Değer: 44 kWh (Frekans: 2)
   -> Aldığı Değer: 54 kWh (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: 'Çıkarılabilir 3. Çekmece' (Toplam 7 üründe var)
   -> Aldığı Değer: Var (Frekans: 7)
----------------------------------------
ÖZELLİK ADI: 'Yıka-kurut çevriminde ağırlıklı su tüketimi (W_wd) (L/cycle) (EU_2021_EP)' (Toplam 1 üründe var)
   -> Aldığı Değer: 78 L (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Yıka-kurut çeviriminde enerji verimlilik sınıfı (EU_2021_EP)' (Toplam 1 üründe var)
   -> Aldığı Değer: D (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '3D Pişirme' (Toplam 16 üründe var)
   -> Aldığı Değer: Var (Frekans: 16)
----------------------------------------
ÖZELLİK ADI: 'Otomatik Pişirme (3)' (Toplam 1 üründe var)
   -> Aldığı Değer: Var (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Yoğun Emiş Gücü (m³/h)' (Toplam 17 üründe var)
   -> Aldığı Değer: 720 m³/h (Frekans: 10)
   -> Aldığı Değer: 850 m³/h (Frekans: 3)
   -> Aldığı Değer: 712 m³/h (Frekans: 2)
   -> Aldığı Değer: 710 m³/h (Frekans: 1)
   -> Aldığı Değer: 830 m³/h (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre)' (Toplam 40 üründe var)
   -> Aldığı Değer: 44-...-60-70 (Frekans: 10)
   -> Aldığı Değer: 43-...-56 (Frekans: 5)
   -> Aldığı Değer: 53 - 55 - 64 dBA (Frekans: 4)
   -> Aldığı Değer: 38-...-59-74 (Frekans: 3)
   -> Aldığı Değer: 46-...-59 (Frekans: 3)
----------------------------------------
ÖZELLİK ADI: '3G' (Toplam 1 üründe var)
   -> Aldığı Değer: var ( 5G) (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '2.Arka Kamera' (Toplam 174 üründe var)
   -> Aldığı Değer: Var (Frekans: 174)
----------------------------------------
ÖZELLİK ADI: '3 cihazı aynı anda şarj edebilme' (Toplam 9 üründe var)
   -> Aldığı Değer: Var (Frekans: 7)
   -> Aldığı Değer: 5 cihazı aynı anda şarj edebilme (Frekans: 1)
   -> Aldığı Değer: Üç cihazı aynı anda şarj eder (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '4 Yönlü Otomatik Hava Kontrolü' (Toplam 13 üründe var)
   -> Aldığı Değer: Var (Frekans: 13)
----------------------------------------
ÖZELLİK ADI: '2 Yönlü Otomatik Hava Kontrolü' (Toplam 1 üründe var)
   -> Aldığı Değer: Var (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Güç (W) (9)' (Toplam 11 üründe var)
   -> Aldığı Değer: 30 W (Frekans: 3)
   -> Aldığı Değer: 100 W (Frekans: 2)
   -> Aldığı Değer: 50 W (Frekans: 2)
   -> Aldığı Değer: 200 W (Frekans: 1)
   -> Aldığı Değer: 65 W (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'İçerdiği Aksesuar (2 Buz Kutusu)' (Toplam 4 üründe var)
   -> Aldığı Değer: Var (Frekans: 4)
----------------------------------------
ÖZELLİK ADI: 'Salınım Açısı (yukarı-aşağı ±5' (Toplam 2 üründe var)
   -> Aldığı Değer: 135 (Frekans: 2)
----------------------------------------
ÖZELLİK ADI: '3 Yollu Vana Blokaj Sistemi' (Toplam 8 üründe var)
   -> Aldığı Değer: Var (Frekans: 8)
----------------------------------------
ÖZELLİK ADI: 'Temizleme fırçası (2)' (Toplam 1 üründe var)
   -> Aldığı Değer: Var (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '360° Dönebilen Kablosuz Kullanım' (Toplam 6 üründe var)
   -> Aldığı Değer: Var (Frekans: 6)
----------------------------------------
ÖZELLİK ADI: 'Dijital Ekran (3)' (Toplam 1 üründe var)
   -> Aldığı Değer: Evet (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: 'Renk (41)' (Toplam 5 üründe var)
   -> Aldığı Değer: Siyah (Frekans: 5)
----------------------------------------
ÖZELLİK ADI: 'Şarj Göstergesi (2)' (Toplam 2 üründe var)
   -> Aldığı Değer: LCD (Frekans: 1)
   -> Aldığı Değer: LED (Frekans: 1)
----------------------------------------
ÖZELLİK ADI: '5 Kat Seramik Kaplama' (Toplam 3 üründe var)
   -> Aldığı Değer: Var (Frekans: 3)
----------------------------------------
ÖZELLİK ADI: '360° Derece Dönebilen Hortum' (Toplam 7 üründe var)
   -> Aldığı Değer: Var (Frekans: 7)
----------------------------------------
ÖZELLİK ADI: '4 Kanatlı Paslanmaz Çelik Bıçak' (Toplam 1 üründe var)
   -> Aldığı Değer: Var (Frekans: 1)
----------------------------------------


==================================================
YENİ OLUŞTURULAN 'Programlar' VE 'Fonksiyonlar' KONTROLÜ
==================================================
Satır Index: 79
  Programlar: ['Buhar Terapi', 'Hijyen+', 'Leke Programı', 'Gömlek', 'Soğuk Yıkama', 'Delicates/Wool/HandWash', 'Duvet/DownWear', 'Karma', '15', 'Var', '0-24 Saat', 'Pamuklular', 'Eko 40-60', 'Sentetik', "Hızlı 14'", 'Sıkma Pompa', 'Durulama', 'Havalandırma (Buhar)']
------------------------------
Satır Index: 80
  Programlar: ['Buhar Terapi', 'Hijyen+', 'Leke Programı', 'Gömlek', 'Soğuk Yıkama', 'Delicates/Wool/HandWash', 'Duvet/DownWear', 'Karma', '15', 'Var', '0-24 Saat', 'Pamuklular', 'Eko 40-60', 'Sentetik', "Hızlı 14'", 'Sıkma Pompa', 'Durulama', 'Havalandırma (Buhar)']
------------------------------
Satır Index: 81
  Programlar: ['Buhar Terapi', 'Hijyen+', 'Leke Programı', 'Gömlek', 'Soğuk Yıkama', 'Delicates/Wool/HandWash', 'Duvet/DownWear', 'Karma', '15', 'Var', '0-24 Saat', 'Pamuklular', 'Eko 40-60', 'Sentetik', "Hızlı 14'", 'Sıkma Pompa', 'Durulama', 'Havalandırma (Buhar)']
------------------------------
Satır Index: 82
  Programlar: ['Buhar Terapi', 'Gömlek', 'Hijyen+', 'Buhar', 'Soğuk Yıkama', 'Delicates/Wool/HandWash', 'Duvet/DownWear', 'İndirilen Program', '15', 'Var', '0-24 Saat', 'Pamuklular', 'Eko 40-60', 'Sentetik', "Hızlı 14'", 'Sıkma Pompa', 'Durulama', 'Akıllı Program']
  Fonksiyonlar: ['Kırışık Önleme Fonksiyonu']
------------------------------
Satır Index: 83
  Programlar: ['Buhar Terapi', 'Gömlek', 'Hijyen+', 'Buhar', 'Soğuk Yıkama', 'Delicates/Wool/HandWash', 'Duvet/DownWear', 'İndirilen Program', '15', 'Var', '0-24 Saat', 'Pamuklular', 'Eko 40-60', 'Sentetik', "Hızlı 14'", 'Sıkma Pompa', 'Durulama', 'Akıllı Program']
  Fonksiyonlar: ['Kırışık Önleme Fonksiyonu']
------------------------------

In [225]:
from collections import Counter
import pandas as pd

# 1. GÜNCEL FREKANSLARI HESAPLA VE TUTULACAKLARI BELİRLE
tum_anahtarlar = [key for d in df['teknik_ozellikler_dict'] for key in d.keys()]
frekanslar = Counter(tum_anahtarlar)

# Sadece frekansı 5'ten BÜYÜK olan anahtarları bir kümeye (set) alıyoruz (hızlı arama için)
tutulacak_anahtarlar = {key for key, adet in frekanslar.items() if adet > 5}

silinen_sayisi = len(frekanslar) - len(tutulacak_anahtarlar)
print(f"Toplam {len(frekanslar)} benzersiz özellik vardı.")
print(f"Frekansı 5 ve altında olan {silinen_sayisi} özellik siliniyor...")
print(f"Geriye {len(tutulacak_anahtarlar)} adet sağlam özellik (sütun adayı) kaldı.\n")


# 2. SÖZLÜKLERİ FİLTRELE (Nadir olanları uçur)
def nadir_ozellikleri_sil(eski_sozluk):
    # Sadece 'tutulacak_anahtarlar' içinde olan key'leri yeni sözlüğe aktar
    return {k: v for k, v in eski_sozluk.items() if k in tutulacak_anahtarlar}

df['teknik_ozellikler_dict'] = df['teknik_ozellikler_dict'].apply(nadir_ozellikleri_sil)


# 3. SÖZLÜKLERİ SÜTUNLARA PARÇALA VE ANA DF İLE BİRLEŞTİR
# pd.json_normalize sözlükleri alır ve hızlıca DataFrame sütunlarına çevirir
yeni_sutunlar_df = pd.json_normalize(df['teknik_ozellikler_dict'])

# Satırların kaymaması için orijinal DataFrame'in indexini yeni oluşan DataFrame'e kopyalıyoruz
yeni_sutunlar_df.index = df.index

# Orijinal df ile yeni oluşan sütunları yan yana birleştiriyoruz (axis=1)
df = pd.concat([df, yeni_sutunlar_df], axis=1)

print("İşlem tamam! Sözlükler başarıyla sütunlara ayrıldı.")
print("Eklenen yeni sütunlardan bazıları:")
print(list(yeni_sutunlar_df.columns)[:10]) # İlk 10 sütun adını gösterelim

Toplam 865 benzersiz özellik vardı.
Frekansı 5 ve altında olan 349 özellik siliniyor...
Geriye 516 adet sağlam özellik (sütun adayı) kaldı.

İşlem tamam! Sözlükler başarıyla sütunlara ayrıldı.
Eklenen yeni sütunlardan bazıları:
['Dondurucu Bölme Teknolojisi', 'Derinlik', 'Genişlik', 'Yükseklik', 'Sıcaklık Yükselme Süresi (Saat)', 'Ürün Rengi', 'Dondurucu Yeri', 'Elektronik Gösterge', 'Kontrol Sistemi', 'Tatil Modu']

In [226]:
df.drop(columns=['teknik_ozellikler', 'teknik_ozellikler_dict'], inplace=True)

In [227]:
# 1. Eksik değerlerin yüzdelik oranını hesapla
eksik_yuzde = df.isnull().mean() * 100

# 2. Hata vermeden (listeleri de destekleyerek) eşsiz değerleri sayan ufak bir fonksiyon
def essiz_sayiyi_bul(sutun):
    try:
        # Önce standart yöntemi denesin
        return sutun.nunique()
    except TypeError:
        # Eğer sütunda liste varsa (TypeError verirse), listeleri tuple'a çevirip öyle saysın
        return sutun.apply(lambda x: tuple(x) if isinstance(x, list) else x).nunique()

# Bu fonksiyonu tüm dataframe'e uygula
essiz_sayi = df.apply(essiz_sayiyi_bul)

# 3. İkisini tek bir DataFrame'de birleştirerek tabloyu oluştur
ozet_tablo = pd.DataFrame({
    'Eksik Değer Oranı (%)': eksik_yuzde.round(2),
    'Eşsiz Değer Sayısı': essiz_sayi
})

# En çok boşluk olan (sorunlu) sütunları en üstte görmek için sırala
ozet_tablo = ozet_tablo.sort_values(by='Eksik Değer Oranı (%)', ascending=False)

# Limitleri kaldır ve göster
pd.set_option('display.max_rows', None) 
ozet_tablo

,Eksik Değer Oranı (%),Eşsiz Değer Sayısı
Hayvan Tüyü Fırçası,99.54,1
Ütü Tipi,99.54,1
Susuz Çalışma Emniyeti,99.54,1
Doluluk göstergesi,99.54,3
Titanyum Emaye Kaplamalı Kazan,99.54,1
Yüksek Basınç Emniyet Valfi,99.54,1
IP Sınıfı,99.54,1
Enerji sınıfı (WH) (EP),99.54,1
İzolasyon,99.54,1
Sağ Ön Yanıcı Gücü,99.54,1
Sağ Arka Yanıcı Gücü,99.54,1
Ocak Göz Sayısı,99.54,3
Sol Ön Yanıcı Gücü,99.54,2
Buharsız Ütüleme,99.54,1
Sol Arka Yanıcı Gücü,99.54,2
Kendi Kendine Şarj,99.54,1
Ekstra Yan Fırça,99.54,1
Otomatik zemin algılama,99.54,1
Temizleme alanı,99.54,3
Temizlik geçmişini görüntüleme,99.54,1
Halı tırmanma yüksekliği,99.54,2
Wi-fi Bağlantısı,99.54,1
Koruma Sınıfı,99.54,1
Atıl Isı Göstergesi,99.54,1
Pizza Pişirme,99.54,1
Damacana Yeri,99.54,2
Tank Materyali,99.54,1
Soğuk su tank kapasitesi (L),99.54,2
Ocak Izgara tipi,99.54,1
Soğutma Kapasitesi (lt/saat),99.54,2
Soğuk Su Derecesi Aralığı,99.54,2
Kontrol Sistemi Tipi,99.54,1
Ocak Ekranı,99.54,3
Gaz Gücü,99.54,2
Bağlantı Noktaları,99.54,5
Otomatik Kireç Temizleme Özelliği,99.54,1
Işıklı Açma/Kapama Düğmesi,99.54,1
360° Dönebilen Kablosuz Kullanım,99.54,1
Kart Okuyucu,99.54,1
Şok Buhar Özelliği,99.54,1
Korozyona Karşı Koruma,99.54,1
IronFinish Teknolojisi,99.54,1
Su Seviye Göstergesi,99.54,1
Pişirme Kapasitesi,99.46,7
Vigo Difüzör Başlık,99.46,1
Yatay Otomatik Kapanma Süresi,99.46,3
Dikey Otomatik Kapanma Süresi,99.46,2
Şok Buhar,99.46,7
Her Ocak Gözü İçin Sıcaklık Ayarı,99.46,2
Paslanmaz Çelik Çırpıcı,99.46,1
Hızlı Dondurma Bölmesi,99.46,1
Dondurucu Sepeti,99.46,3
Kanat Rengi,99.46,3
Taşıma sapı,99.46,1
360° Derece Dönebilen Hortum,99.46,1
Pervane Kanat Sayısı,99.46,3
Sıcaklık Ayarı Sayısı,99.46,2
Maksimum Çalışma Basıncı,99.46,1
Devrilme Emniyeti,99.46,1
Çalışma Basıncı,99.46,2
Su Miktarını Belirleme,99.46,1
Equalizer Ayarı,99.46,3
Su Tankı,99.46,1
Optik Giriş,99.46,1
Müzik Formatlar,99.46,1
Çıkarılabilir 3. Çekmece,99.46,1
Otomatik Su Alımı,99.46,1
Düşük Su Seviyesi Göstergesi,99.46,1
Kapaklı Bölme Sayısı,99.46,2
Type¬C veya Micro USB kablolarıyla şarj edilebilir,99.46,1
Bıçak Malzemesi,99.46,3
Kullanım tipi,99.46,1
Gövde Rengi,99.46,2
İç Hazne Kapasitesi,99.46,7
Sepet,99.46,2
İkili Isıtma Sistemi,99.46,1
Izgara,99.46,1
Pişirme Haznesi,99.46,1
Ana Şasi – Yoğurt Yapma Özelliği,99.46,1
Çalışma Göstergesi,99.46,1
Kapak,99.46,1
Kablo Sarma,99.46,2
Bağlantılar,99.46,3
Sıcaklık Kontrolü,99.46,1
Yağ Toplama Haznesi,99.46,1
Su Sıcaklık Ayarı (EM),99.46,1
Spinjet Teknolojisi (Su Püskürterek Karıştırma),99.46,1
Ölçü Kabı,99.39,1
Doğrayıcı Kabı,99.39,1
Mevsimsel Mahal Isıtma Enerji Verimliliği (hs),99.39,4
Güvenlik Kilidi,99.39,1
Retina HD,99.39,1
Hijyenik Yıkanabilir Başlıklar,99.39,1
Duvara Monte Edilebilen Şarj aleti,99.39,1
Yedek Sentetik Toz Torbası,99.39,5
Yakıt Cinsi,99.39,1
Alev Modülasyonu,99.39,1
Su ısıtma Enerji Verimliliği (hWH),99.39,4
Oda Termostatı İle Çalışma,99.39,1
Yerden Isıtmaya Uygunluk,99.39,1
Maksimum Sıcak Su Debisi,99.39,3
"Ses Gücü Seviyesi, İç Ortam (LWA)",99.39,4
Su Isıtma Enerji Verimliliği Sınıfı,99.39,1
Su Isıtma Yük Profili,99.39,1
Turbo Fırça,99.39,1
Fan Modülasyonu,99.39,1
Uzaktan Kumanda,99.39,1
3 Yollu Vana Blokaj Sistemi,99.39,1
Alev Sönme Emniyeti,99.39,1
Asma Halkası,99.39,1
Otomatik By-Pass Sistemi,99.39,1
Pompa Anti Blokaj Sistemi,99.39,1
Super Retina HD,99.39,1
Şarj süresi,99.39,7
Baca Tipi,99.39,1
Genleşme Tankı kapasitesi,99.39,2
Yakıt Tipi,99.39,1
Arıza Teşhis Sistemi,99.39,1
Emniyet Termostatı,99.39,1
Emniyet Ventili,99.39,1
Hava Emiş Emniyeti,99.39,1
Etkinlik Alanı Yarıçapı (m),99.39,3
Islak Kuru Kullanım,99.39,1
Kullanım Şekli,99.39,3
Izgara Gücü (W),99.39,2
Difüzör Başlığı,99.39,1
İç Izgara Adedi,99.39,1
ProScent Teknolojisi,99.39,1
Musluk,99.39,4
Açma/Kapama Düğmesi,99.39,1
Kirleri Göstermeyen Katalitik Yan Duvar,99.39,1
Kirleri Göstermeyen Katalitik Arka Duvar,99.39,1
Doğrayıcı,99.39,1
Kapasite (kW),99.39,4
Cihaz Tipi,99.39,1
Su Haznesi,99.39,3
Mevsimsel Mahal Isıtma Enerji Verimliliği Sınıfı,99.39,1
Temizleme Modu,99.31,2
Ağırlık: Paketli,99.31,7
Led Fırça,99.31,1
Hızlı Başlatma,99.31,1
Eko-Turbo Pişirme,99.31,1
Kilitleme Mandalı,99.31,1
Yüksek Bazaya Montaj,99.31,1
MicroSD Kart Girişi,99.31,2
Su Isıtıcı Malzemesi,99.31,4
Emiş Gücü,99.31,7
İç Hazne Malzemesi,99.31,2
Sıcak Saklama Süresi,99.31,3
Hoparlör,99.31,5
Su Isıtıcı Kapasitesi,99.31,3
Soğuk Saklama Süresi,99.31,3
Buzlu Saklama süresi,99.31,3
Paslanmaz Çelik Blender,99.31,1
Blender Ayağı Malzemesi,99.31,1
Soğuk Ayarı,99.31,1
3 cihazı aynı anda şarj edebilme,99.31,3
Demlik Kapasitesi,99.31,3
Demlik Malzemesi,99.31,3
Dinamik Rezistans,99.31,1
Önden Ayarlanablir Arka Ayaklar,99.23,1
Kahve Çeşidi Sayısı,99.23,4
Radyo,99.23,1
Yüksek Performanslı Elektrikli Fırça,99.23,1
Kablo Sarıcı,99.23,3
Arttırılabilir Hafıza,99.23,2
İç Ünite Isıtma Çalışma Aralığı(°C),99.23,1
Çıkarılabilir hava giriş ızgarası,99.23,1
Saçları Pürüzsüz ve Kıvırcık Yapma,99.23,1
Çıkarılabilir Plakalar,99.23,1
Plaka Kullanımı,99.23,2
Şarj istasyonu,99.23,1
Tezgah Altı Yüksekliği,99.23,2
Izgara Özelliği,99.23,1
Pişirme Yüzeyi,99.23,5
Bakım Yapan Kaplama,99.15,2
Seramik Izgara,99.15,1
Fön Başlığı,99.15,1
Hızlı Isınma Süresi,99.15,3
Malzeme,99.15,3
Turbo Özelliği,99.15,1
Paspas Özelliği,99.15,1
Mikrodalga Kavite Tipi,99.15,2
Buhar Destekli Pişirme,99.15,2
Dikey Ütüleme,99.15,1
LED Ekran,99.15,1
Pasta Tepsi Adedi,99.15,1
Kablosuz Ağ,99.15,4
Mikrofon (MPA),99.15,1
Hız Kademesi adedi,99.15,4
Güç (W) (9),99.15,7
Taban,99.15,3
Sürekli Buhar,99.15,9
Isıtma Gücü,99.15,5
Vantilatör Tipi,99.15,5
Auto Swing,99.15,1
Giriş Gücü,99.15,7
Paslanmaz Çelik Bıçak,99.08,1
Dondurucu Bölme Teknolojisi,99.08,3
Fan ve Alt Isıtıcı,99.08,1
Güvenli şarj için akım korumalı,99.08,2
İç Ünite Soğutma Çalışma Aralığı(°C),99.08,3
Kablo uzunluğu,99.08,8
Uzatma Borusu,99.08,5
Ürün Kilidi,99.08,1
Uyumlu Olduğu Platformlar,99.08,3
Harddisk Kapasitesi,99.08,5
Doğrama Kabı Malzemesi,99.08,3
Ekran Kartı,99.08,3
Kablosuz çalışma süresi(Orta güç),99.08,7
Gövde Malzemesi,99.08,2
Teleskopik Ray Sistemi,99.08,1
Portre Işığı,99.00,1
FitFry Teknolojisi,99.00,1
Batarya kapasitesi,99.00,7
Sıcak Tutma Özelliği,99.00,1
4 Yönlü Otomatik Hava Kontrolü,99.00,1
Parke / Halı fırçası,99.00,2
Cool Shot,99.00,1
Kir Sensörü,99.00,1
Pratik Filtre,99.00,2
Animoji,99.00,1
Isı Ayarı,99.00,2
Dilim Kapasitesi,99.00,2
Aşırı Isınma Emniyeti,98.92,1
Anlık Tüketim Göstergesi,98.92,1
Soğutma/Dondurma Modu,98.92,1
Kondenser Temizleme Uyarısı,98.92,1
Fıltre Temizleme Uyarısı,98.92,1
Fincan Boyutu Seçimi,98.92,1
USB Girişi,98.92,1
Zaman Erteleme Özelliği,98.92,1
Kapsül Kahve,98.92,2
Isı pompalı Kurutma Teknolojisi,98.92,2
Akıllı Nem Sensörü,98.92,2
Ses Gücü Seviyesi (dBA),98.92,3
Su Tankı Dolu Uyarısı,98.92,1
Dokunmatik Tuş,98.92,1
Tank Pozisyonu,98.92,1
Tambur Aydınlatma,98.92,1
Direkt Su Tahliyesi,98.92,1
Batarya tipi,98.92,2
Ölçü Kabı,98.92,7
Donma Emniyeti,98.92,1
Buz Çözme Özelliği,98.92,3
Mikrodalga Güç Kademe Sayısı,98.92,3
Maksimum Zamanlama Süresi,98.92,5
Tambur Hacmi (L),98.92,3
Kapak Açma Mekanizma Tipi,98.85,3
Mikrodalga Çıkış Gücü,98.85,3
Günlük Dondurma Kapasitesi (kg),98.85,7
Mikrodalga Hacmi,98.85,6
Döner Tabla,98.85,1
Zamanlayıcı Tipi,98.85,2
Mikrodalga Fırın Türü,98.85,2
Cezve Malzemesi,98.85,3
Kablo Tipi,98.85,10
Ekran Kartı Özellikleri,98.85,6
Cam Dekor Rengi,98.85,3
Micro USB,98.85,2
Aksesuar (Ek Donanım),98.85,6
Mikrodalga Kontrol Paneli,98.85,2
Kurutma Kapasitesi,98.85,6
Yumuşak Hava,98.85,1
Enerji Kontrol,98.85,1
3D Pişirme,98.77,1
Derin Tepsi Adedi,98.77,1
Pil Ömrü,98.77,5
İşletim Sistemi Özellikleri,98.77,1
İşlemci Özellikleri,98.77,11
HDMI,98.77,1
Kapı Kilidi,98.77,2
Kablo Sarma Yuvası,98.77,1
Kablosuz çalışma süresi(Yüksek güç),98.77,9
RAM Özellikleri,98.77,5
Cezve Rengi,98.77,4
Toz Haznesi Kapasitesi,98.77,13
Park Etme Özelliği,98.69,3
Anti Spill Teknolojisi (Taşmayı Önleme),98.69,1
Kablosuz Çalışma Süresi (Düşük Güç),98.69,10
Isıtmadaki Enerji Verim Oranı (W/W),98.69,9
Döşeme/Koltuk Fırçası,98.69,1
Eko Modu,98.69,1
Işıklı Uyarı,98.69,1
Ölçü Kaşığı,98.69,1
Cook Sense Teknolojisi (Pişmeyi Algılama),98.69,1
Çıkarılabilir Su tankı,98.69,1
Batarya,98.69,5
Pil,98.69,9
Hava Temizleme Özelliği,98.69,1
Fan Destekli Isıtıcı,98.69,1
Sıcaklık seviye sayısı,98.69,5
Yoğun Emiş Gücü,98.69,1
Yoğun Emiş Gücü (m³/h),98.69,5
Ayarlanabilir Led Aydınlatma,98.69,1
Bellek,98.69,6
Çıkış Gücü,98.69,13
Akıllı Çalışma Sistemi,98.62,1
Sesli Uyarı,98.62,1
IronFast,98.62,1
Dar Ağızlı Uç,98.62,1
LCD Ekran,98.62,1
Fırın İçi Aydınlatma,98.62,1
Su Kesik İkazı,98.54,1
Su Taşma Emniyet Sistemi,98.54,1
Toplam Dondurucu Bölme Sayısı,98.54,7
Motor Tipi (ÇM),98.54,1
EverFresh+ Teknolojisi,98.54,1
Sıcaklık Ayarı Kilidi,98.54,1
Su Tüketimi (1 Çevrim),98.54,8
Enerji Tüketimi (100 Çevrim),98.54,8
İşlemci Tipi,98.54,4
Bulaşık Makinesinde Yıkanabilir Aksesuarlar,98.54,1
SSD Özellikleri,98.54,4
SSD Kapasitesi,98.46,3
Fincan Kapasitesi,98.46,7
Elektronik Su Kontrol Sistemi,98.46,1
Maksimum Sıkma Devri,98.46,4
USB Bağlantısı,98.46,1
Su Girişi,98.46,1
Dengesiz Yük Kontrolü,98.46,1
Buhar,98.46,2
Deterjan Sistemi,98.46,1
Hızlı Şarj desteği,98.46,1
Otomatik Temizleme,98.46,1
Kapasite (Isıtma),98.46,7
Minimum Sıcaklık Derecesi (°C),98.39,9
Sessiz Mod,98.39,1
Dış Ünite (GxYxD) mm,98.39,6
İç Ünite (GxYxD) mm,98.39,6
Ürün rengi,98.39,7
Maksimum Sıcaklık Derecesi,98.39,5
Pompa Basıncı,98.39,4
Uyumlu olduğu modeller (MPA),98.39,10
Enerji Sınıfı-Isıtma,98.31,3
PractiClean Nano Kaplama,98.31,1
Sıcaklık Ayarı,98.31,2
Özel Filtreler,98.23,4
Gösterge Tipi,98.23,2
Üst Sepet Katlanır Tel Sayısı,98.23,1
Hız Ayarı,98.16,6
Mevsimsel (SCOP) Enerji Verimi Isıtma (W/W),98.16,6
Şarj Olma Süresi,98.16,8
Isıtmada Çekilen Enerji (W),98.16,12
Isıtma Kapasitesi (Btu/h),98.16,14
Dış Ünite Isıtma Çalışma Aralığı(°C),98.16,4
Yıllık Tüketim Isıtma (kW),98.16,10
Zamanlayıcı,98.16,2
Otomatik Kapanma Özelliği,98.16,1
Küçük Izgara,98.08,1
Çerçeve,98.08,3
Otomatik Hava Yönlendirme (Yukarı-Aşağı),98.08,1
Mevsimsel (SEER) Enerji Verimi Soğutma (W/W),98.08,9
Toz Torbası Kapasitesi,98.08,13
Yıllık Tüketim (kW) Soğuma,98.08,14
Hafıza Kartı Tipi,98.08,2
Parmak İzi Okuyucu,98.08,1
Dış Ünite Soğutma Çalışma Aralığı(°C),98.08,9
Uyku Mode,98.08,1
Ses Çıkış Gücü,98.08,9
Nem Alma,98.00,1
Gizli Gösterge,98.00,3
Ekran Kilidi,98.00,1
Soğutucu Akışkan,98.00,2
Bardak Koruma Sistemi,98.00,1
Soğutma Kapasitesi,98.00,12
Dahili Depolama Kapasitesi,97.92,6
Saat Tipi,97.92,4
Tel Izgara,97.92,1
Gövde rengi,97.92,13
Çalma Süresi,97.92,9
Alt Isıtıcı,97.85,1
Filtre Doluluk Göstergesi,97.85,1
Otomatik Kapı Açma Özelliği,97.85,1
Ses Basınç Seviyesi (dB),97.77,7
Su Tankı Kapasitesi,97.77,15
Tek Tuşla Kontrol,97.77,1
Iyon Özelliği,97.77,1
Aktif gürültü önleyici,97.77,1
Kahve Beki Adaptörü,97.69,2
Verimlilik,97.69,12
İşlemci Hızı,97.69,5
Üst Sepet Ayar Tipi,97.69,1
Alt Sepet Katlanır Tel Sayısı,97.62,1
Yarım Yük Yıkama,97.62,1
Elektroturbo (Fan Destekli Pişirme),97.62,1
Ağırlık (gr),97.54,21
Kapak Açılma Yönü,97.54,1
Motor Teknolojisi,97.54,1
Buharlı Pişirme,97.54,4
Aux Girişi,97.54,1
Dondurucu Bölme Aydınlatma Tipi,97.54,3
Parlatıcı Göstergesi,97.46,1
Davlumbaz Tipi,97.46,5
Enerji Tüketimi,97.46,9
Paslanmaz Çelik İç Gövde,97.46,1
Akım (A),97.46,1
Çatal Kaşık Sepeti,97.46,2
Su Tüketimi,97.46,5
Güç (W),97.46,2
Fincan Raf Sayısı,97.46,2
Yüksekliği Ayarlanabilir Fincan Rafları,97.46,1
Tuz Göstergesi,97.46,1
Su Güvenlik Sistemi,97.46,2
Kolayca Sökülebilir ve Temizlenebilir Komple İç Cam,97.39,1
Tambur Deseni,97.39,3
Kalan Zaman Göstergesi,97.39,1
Elektrikli Izgara,97.31,1
Tencere Izgara Tipi,97.31,8
Ön Kapak Cam Sayısı,97.31,2
Standart Tepsi Adedi,97.31,1
Montaj Yüksekliği (mm),97.31,4
Fırın Hacmi,97.31,5
Hızlı Soğutma,97.31,1
Motor Gücü,97.23,20
HarvestFresh™,97.08,1
ProSmart™ Inverter Kompresör,97.00,1
Bağlantı,97.00,3
Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre),96.93,16
Kablo Uzunluğu,96.93,15
Niş Boyutlar (YxGxD) (cm),96.93,4
Filtre Tipi,96.85,4
Otomatik Kapanma,96.77,2
Bek Şapkası Tipi,96.69,3
Pil Türü,96.54,2
Karbon Filtre,96.46,1
Yağ Filtre Adedi,96.46,3
Kahvaltılık Çekmecesi,96.46,1
Lamba Tipi,96.46,1
Lamba Adedi,96.46,2
Lamba Gücü (W),96.46,3
Bulaşık Makinesinde Yıkanabilir Filtre,96.46,1
Kademe Sayısı,96.46,2
Minimum Ses Seviyesi,96.46,10
Maksimum Çekiş Gücü,96.46,16
Motor Sayısı,96.46,1
Soğutucu Bölme Fanı,96.39,1
Tatil Modu,96.39,1
Sol Arka Bölme,96.31,8
Ürün Serisi,96.31,12
Toplam Elektrik Gücü (kW),96.31,6
Sol Ön Bölme,96.31,10
Sağ Ön Bölme,96.23,8
Gaz Tipi,96.23,1
Ocak Ateşleme Tipi,96.23,1
Gaz Emniyet Sistemi,96.23,1
Sağ Arka Bölme,96.23,9
Kontrol Tipi ve Yeri,96.00,4
Ocak Tipi Ve Göz Sayısı,96.00,10
Ocak Tipi,96.00,4
Soğutucu Bölme Hacmi (L),95.93,19
Sebzelik Adedi,95.93,2
Dondurucu Çekmece Sayısı,95.85,6
Su Geçirmezlik,95.77,6
Elektronik Gösterge,95.54,12
Ocak Yüzeyi,95.54,3
Kontrol Tipi,95.54,6
Aydınlatma Tipi,95.47,6
Kapı Yönü Değiştirme,95.31,1
Günlük Dondurma Kapasitesi (kg/Gün),95.31,22
Çocuk Kilidi,95.00,1
Buzluk Tipi,94.93,6
Ürün Ailesi,94.93,5
Pil Kapasitesi,94.85,8
Çift Hatlı,94.85,1
İşletim Sistemi Versionu,94.47,6
Voltaj,94.31,2
Sıcaklık Yükselme Süresi (Saat),94.16,13
Dondurucu Bölme Hacmi (L),94.08,33
Dondurucu Yeri,94.08,6
Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP),94.00,39
İklim Sınıfı,94.00,2
Günlük Enerji Tüketimi (kwh/Gün),94.00,43
Ses Seviyesi Sınıfı,94.00,2
Toplam Hacim (L),94.00,37
Soğutma Sistemi,94.00,3
Kulaklık Tipi,93.85,14
Yüz Haritalama,93.31,1
Kapasite,93.31,24
Ses Kayıt,93.08,1
Yıllık Enerji Tüketimi (kWh),92.85,57
Mikrofon,92.39,2
Kontrol Sistemi,92.31,7
RAM Kapasitesi,91.70,7
Programlar,91.24,44
Arka Kamera,91.08,15
GPS,91.08,1
Görüntülü Konuşma,90.32,1
Motor Tipi,89.93,16
Ön Kamera Flaş,89.93,1
Kamera Zoom,89.62,2
Ekran Çözünürlüğü,89.47,20
İşlemci Çekirdek Sayısı,89.16,6
Ses Seviyesi,89.01,26
Güç,88.55,45
İşlemci,88.39,27
Ürün Tipi,87.78,12
NFC,87.55,1
Fonksiyonlar,87.39,40
2.Arka Kamera,86.63,1
Marka,86.55,4
Dahili Hafıza,86.55,5
Wi-Fi,85.78,1
Ön Kamera,85.55,12
İşletim Sistemi,84.09,13
Ekran Boyutu,83.47,24
Renk,82.78,34
Ekran Tipi,82.55,11
Enerji Sınıfı,81.17,9
enerji_sinifi,79.25,9
Bluetooth,78.55,4
Ürün Rengi,61.88,47
Boyut (cm) (GxYxD),56.50,151
Ağırlık: Paketsiz,54.50,272
Derinlik,18.91,180
Genişlik,17.60,79
Yükseklik,14.99,105
fiyat,9.61,544
favori_sayisi,4.92,120
Subcategory,0.00,46
Main_Category,0.00,6
Product_Group,0.00,171
urun_adi,0.00,1236
urun_linki,0.00,1301

In [228]:
df.shape

(1301, 524)

In [229]:
# Sütun adını senin veri setindeki orijinal adına (Subcategory) güncelliyoruz
kategori_sutunu = 'Subcategory'

# 1. Her bir alt kategori için sütunların boşluk oranını hesapla 
# (apply yerine doğrudan isnull() üzerinden groupby yapmak çok daha hızlıdır)
kategori_bazli_bosluk = df.isnull().groupby(df[kategori_sutunu]).mean() * 100

# 2. Her bir sütun için "en düşük" boşluk oranını bul (Yani o sütunun en dolu olduğu kategoriyi baz al)
minimum_bosluk_oranlari = kategori_bazli_bosluk.min()

# 3. Kendi belirlediğin sınır: En dolu olduğu kategoride bile %75'ın üzerinde boş olan sütunları bul
silinecek_sutunlar = minimum_bosluk_oranlari[minimum_bosluk_oranlari > 75].index.tolist()

print(f"Toplam {len(df.columns)} sütun var.")
print(f"Hiçbir kategoride %25 doluluğa bile ulaşamayan {len(silinecek_sutunlar)} çöp sütun siliniyor...")

# 4. Bu sütunları DataFrame'den tamamen uçur
df = df.drop(columns=silinecek_sutunlar)

print(f"Geriye {len(df.columns)} adet kaliteli sütun kaldı.")

Toplam 524 sütun var.
Hiçbir kategoride %25 doluluğa bile ulaşamayan 86 çöp sütun siliniyor...
Geriye 438 adet kaliteli sütun kaldı.

In [230]:
# 1. Hata vermeden (listeleri de destekleyerek) eşsiz değerleri sayan fonksiyon
def essiz_sayiyi_bul(sutun):
    try:
        return sutun.nunique()
    except TypeError:
        # Eğer sütunda liste varsa, listeleri geçici olarak tuple'a çevirip say
        return sutun.apply(lambda x: tuple(x) if isinstance(x, list) else x).nunique()

# 2. Eksik değer oranını hesapla
eksik_yuzde = df.isnull().mean() * 100

# 3. Eşsiz sayıyı hesapla
essiz_sayi = df.apply(essiz_sayiyi_bul)

# 4. Tabloyu oluştur
ozet_tablo = pd.DataFrame({
    'Eksik Değer Oranı (%)': eksik_yuzde.round(2),
    'Eşsiz Değer Sayısı': essiz_sayi
})

# En çok boşluk olanları en üstte görmek için sırala
ozet_tablo = ozet_tablo.sort_values(by='Eksik Değer Oranı (%)', ascending=False)

# Aradaki satırlar gizlenmesin diye limiti kaldır ve göster
pd.set_option('display.max_rows', None) 
ozet_tablo

,Eksik Değer Oranı (%),Eşsiz Değer Sayısı
360° Dönebilen Kablosuz Kullanım,99.54,1
IP Sınıfı,99.54,1
Enerji sınıfı (WH) (EP),99.54,1
Titanyum Emaye Kaplamalı Kazan,99.54,1
Yüksek Basınç Emniyet Valfi,99.54,1
Tank Materyali,99.54,1
Damacana Yeri,99.54,2
Soğuk su tank kapasitesi (L),99.54,2
Şok Buhar Özelliği,99.54,1
Buharsız Ütüleme,99.54,1
Soğutma Kapasitesi (lt/saat),99.54,2
Kontrol Sistemi Tipi,99.54,1
Ütü Tipi,99.54,1
Soğuk Su Derecesi Aralığı,99.54,2
Su Seviye Göstergesi,99.54,1
Işıklı Açma/Kapama Düğmesi,99.54,1
Susuz Çalışma Emniyeti,99.54,1
Koruma Sınıfı,99.54,1
İzolasyon,99.54,1
Korozyona Karşı Koruma,99.54,1
Bağlantılar,99.46,3
Gövde Rengi,99.46,2
Çalışma Basıncı,99.46,2
İkili Isıtma Sistemi,99.46,1
Şok Buhar,99.46,7
Pişirme Haznesi,99.46,1
Pişirme Kapasitesi,99.46,7
Sıcaklık Kontrolü,99.46,1
Sepet,99.46,2
Çalışma Göstergesi,99.46,1
İç Hazne Kapasitesi,99.46,7
Kablo Sarma,99.46,2
Type¬C veya Micro USB kablolarıyla şarj edilebilir,99.46,1
Pervane Kanat Sayısı,99.46,3
Paslanmaz Çelik Çırpıcı,99.46,1
Yağ Toplama Haznesi,99.46,1
Kapaklı Bölme Sayısı,99.46,2
Hızlı Dondurma Bölmesi,99.46,1
Yatay Otomatik Kapanma Süresi,99.46,3
Dikey Otomatik Kapanma Süresi,99.46,2
Kapak,99.46,1
Sıcaklık Ayarı Sayısı,99.46,2
Devrilme Emniyeti,99.46,1
Kanat Rengi,99.46,3
Maksimum Çalışma Basıncı,99.46,1
360° Derece Dönebilen Hortum,99.46,1
Vigo Difüzör Başlık,99.46,1
Taşıma sapı,99.46,1
Kullanım tipi,99.46,1
Su Isıtma Yük Profili,99.39,1
Su Isıtma Enerji Verimliliği Sınıfı,99.39,1
Fan Modülasyonu,99.39,1
Alev Modülasyonu,99.39,1
Baca Tipi,99.39,1
Doğrayıcı Kabı,99.39,1
Güvenlik Kilidi,99.39,1
Ölçü Kabı,99.39,1
Musluk,99.39,4
Difüzör Başlığı,99.39,1
Açma/Kapama Düğmesi,99.39,1
Duvara Monte Edilebilen Şarj aleti,99.39,1
Su Haznesi,99.39,3
Doğrayıcı,99.39,1
Turbo Fırça,99.39,1
Otomatik By-Pass Sistemi,99.39,1
Yakıt Tipi,99.39,1
Arıza Teşhis Sistemi,99.39,1
Genleşme Tankı kapasitesi,99.39,2
3 Yollu Vana Blokaj Sistemi,99.39,1
Emniyet Ventili,99.39,1
Emniyet Termostatı,99.39,1
Alev Sönme Emniyeti,99.39,1
Hava Emiş Emniyeti,99.39,1
Maksimum Sıcak Su Debisi,99.39,3
Mevsimsel Mahal Isıtma Enerji Verimliliği (hs),99.39,4
Mevsimsel Mahal Isıtma Enerji Verimliliği Sınıfı,99.39,1
Yerden Isıtmaya Uygunluk,99.39,1
ProScent Teknolojisi,99.39,1
Uzaktan Kumanda,99.39,1
Şarj süresi,99.39,7
"Ses Gücü Seviyesi, İç Ortam (LWA)",99.39,4
Yakıt Cinsi,99.39,1
Su ısıtma Enerji Verimliliği (hWH),99.39,4
Etkinlik Alanı Yarıçapı (m),99.39,3
Kapasite (kW),99.39,4
Oda Termostatı İle Çalışma,99.39,1
Cihaz Tipi,99.39,1
Asma Halkası,99.39,1
Pompa Anti Blokaj Sistemi,99.39,1
Soğuk Saklama Süresi,99.31,3
Dinamik Rezistans,99.31,1
Su Isıtıcı Kapasitesi,99.31,3
3 cihazı aynı anda şarj edebilme,99.31,3
Demlik Malzemesi,99.31,3
Temizleme Modu,99.31,2
Led Fırça,99.31,1
Paslanmaz Çelik Blender,99.31,1
Soğuk Ayarı,99.31,1
Sıcak Saklama Süresi,99.31,3
Yüksek Bazaya Montaj,99.31,1
Blender Ayağı Malzemesi,99.31,1
Ağırlık: Paketli,99.31,7
İç Hazne Malzemesi,99.31,2
Hoparlör,99.31,5
Kilitleme Mandalı,99.31,1
Demlik Kapasitesi,99.31,3
Su Isıtıcı Malzemesi,99.31,4
Buzlu Saklama süresi,99.31,3
Saçları Pürüzsüz ve Kıvırcık Yapma,99.23,1
Şarj istasyonu,99.23,1
Tezgah Altı Yüksekliği,99.23,2
Çıkarılabilir hava giriş ızgarası,99.23,1
Yüksek Performanslı Elektrikli Fırça,99.23,1
İç Ünite Isıtma Çalışma Aralığı(°C),99.23,1
Plaka Kullanımı,99.23,2
Pişirme Yüzeyi,99.23,5
Önden Ayarlanablir Arka Ayaklar,99.23,1
Çıkarılabilir Plakalar,99.23,1
Kablo Sarıcı,99.23,3
Taban,99.15,3
Dikey Ütüleme,99.15,1
Paspas Özelliği,99.15,1
Fön Başlığı,99.15,1
Turbo Özelliği,99.15,1
Pasta Tepsi Adedi,99.15,1
LED Ekran,99.15,1
Mikrofon (MPA),99.15,1
Sürekli Buhar,99.15,9
Auto Swing,99.15,1
Giriş Gücü,99.15,7
Isıtma Gücü,99.15,5
Güç (W) (9),99.15,7
Vantilatör Tipi,99.15,5
Bakım Yapan Kaplama,99.15,2
Hız Kademesi adedi,99.15,4
Buhar Destekli Pişirme,99.15,2
Hızlı Isınma Süresi,99.15,3
Seramik Izgara,99.15,1
Malzeme,99.15,3
Paslanmaz Çelik Bıçak,99.08,1
Dondurucu Bölme Teknolojisi,99.08,3
Fan ve Alt Isıtıcı,99.08,1
Kablo uzunluğu,99.08,8
İç Ünite Soğutma Çalışma Aralığı(°C),99.08,3
Güvenli şarj için akım korumalı,99.08,2
Uyumlu Olduğu Platformlar,99.08,3
Doğrama Kabı Malzemesi,99.08,3
Harddisk Kapasitesi,99.08,5
Gövde Malzemesi,99.08,2
Ürün Kilidi,99.08,1
Teleskopik Ray Sistemi,99.08,1
Uzatma Borusu,99.08,5
Kablosuz çalışma süresi(Orta güç),99.08,7
Batarya kapasitesi,99.00,7
4 Yönlü Otomatik Hava Kontrolü,99.00,1
Kir Sensörü,99.00,1
Parke / Halı fırçası,99.00,2
Pratik Filtre,99.00,2
FitFry Teknolojisi,99.00,1
Sıcak Tutma Özelliği,99.00,1
Dilim Kapasitesi,99.00,2
Isı Ayarı,99.00,2
Cool Shot,99.00,1
Batarya tipi,98.92,2
Aşırı Isınma Emniyeti,98.92,1
Ölçü Kabı,98.92,7
Anlık Tüketim Göstergesi,98.92,1
Tambur Hacmi (L),98.92,3
Isı pompalı Kurutma Teknolojisi,98.92,2
Akıllı Nem Sensörü,98.92,2
Kapsül Kahve,98.92,2
Ses Gücü Seviyesi (dBA),98.92,3
Fincan Boyutu Seçimi,98.92,1
Donma Emniyeti,98.92,1
Fıltre Temizleme Uyarısı,98.92,1
Su Tankı Dolu Uyarısı,98.92,1
Tank Pozisyonu,98.92,1
Dokunmatik Tuş,98.92,1
Kondenser Temizleme Uyarısı,98.92,1
Direkt Su Tahliyesi,98.92,1
Tambur Aydınlatma,98.92,1
Zaman Erteleme Özelliği,98.92,1
Enerji Kontrol,98.85,1
Kurutma Kapasitesi,98.85,6
Kablo Tipi,98.85,10
Aksesuar (Ek Donanım),98.85,6
Ekran Kartı Özellikleri,98.85,6
Cezve Malzemesi,98.85,3
Yumuşak Hava,98.85,1
Cam Dekor Rengi,98.85,3
Micro USB,98.85,2
İşlemci Özellikleri,98.77,11
Toz Haznesi Kapasitesi,98.77,13
Kablosuz çalışma süresi(Yüksek güç),98.77,9
Pil Ömrü,98.77,5
İşletim Sistemi Özellikleri,98.77,1
RAM Özellikleri,98.77,5
HDMI,98.77,1
Cezve Rengi,98.77,4
Derin Tepsi Adedi,98.77,1
Kapı Kilidi,98.77,2
Kablo Sarma Yuvası,98.77,1
3D Pişirme,98.77,1
Kablosuz Çalışma Süresi (Düşük Güç),98.69,10
Yoğun Emiş Gücü,98.69,1
Sıcaklık seviye sayısı,98.69,5
Hava Temizleme Özelliği,98.69,1
Park Etme Özelliği,98.69,3
Batarya,98.69,5
Çıkarılabilir Su tankı,98.69,1
Anti Spill Teknolojisi (Taşmayı Önleme),98.69,1
Cook Sense Teknolojisi (Pişmeyi Algılama),98.69,1
Ölçü Kaşığı,98.69,1
Isıtmadaki Enerji Verim Oranı (W/W),98.69,9
Çıkış Gücü,98.69,13
Işıklı Uyarı,98.69,1
Döşeme/Koltuk Fırçası,98.69,1
Yoğun Emiş Gücü (m³/h),98.69,5
Ayarlanabilir Led Aydınlatma,98.69,1
Bellek,98.69,6
Pil,98.69,9
Fan Destekli Isıtıcı,98.69,1
Akıllı Çalışma Sistemi,98.62,1
Dar Ağızlı Uç,98.62,1
Fırın İçi Aydınlatma,98.62,1
IronFast,98.62,1
LCD Ekran,98.62,1
Sesli Uyarı,98.62,1
Bulaşık Makinesinde Yıkanabilir Aksesuarlar,98.54,1
EverFresh+ Teknolojisi,98.54,1
Su Kesik İkazı,98.54,1
Sıcaklık Ayarı Kilidi,98.54,1
Toplam Dondurucu Bölme Sayısı,98.54,7
İşlemci Tipi,98.54,4
Motor Tipi (ÇM),98.54,1
Su Tüketimi (1 Çevrim),98.54,8
Su Taşma Emniyet Sistemi,98.54,1
Enerji Tüketimi (100 Çevrim),98.54,8
SSD Özellikleri,98.54,4
USB Bağlantısı,98.46,1
Otomatik Temizleme,98.46,1
Fincan Kapasitesi,98.46,7
Dengesiz Yük Kontrolü,98.46,1
Buhar,98.46,2
Hızlı Şarj desteği,98.46,1
SSD Kapasitesi,98.46,3
Kapasite (Isıtma),98.46,7
Su Girişi,98.46,1
Deterjan Sistemi,98.46,1
Elektronik Su Kontrol Sistemi,98.46,1
Maksimum Sıkma Devri,98.46,4
Ürün rengi,98.39,7
Maksimum Sıcaklık Derecesi,98.39,5
Minimum Sıcaklık Derecesi (°C),98.39,9
İç Ünite (GxYxD) mm,98.39,6
Dış Ünite (GxYxD) mm,98.39,6
Uyumlu olduğu modeller (MPA),98.39,10
Pompa Basıncı,98.39,4
Sessiz Mod,98.39,1
Sıcaklık Ayarı,98.31,2
Enerji Sınıfı-Isıtma,98.31,3
Özel Filtreler,98.23,4
Gösterge Tipi,98.23,2
Üst Sepet Katlanır Tel Sayısı,98.23,1
Otomatik Kapanma Özelliği,98.16,1
Zamanlayıcı,98.16,2
Isıtmada Çekilen Enerji (W),98.16,12
Mevsimsel (SCOP) Enerji Verimi Isıtma (W/W),98.16,6
Yıllık Tüketim Isıtma (kW),98.16,10
Hız Ayarı,98.16,6
Isıtma Kapasitesi (Btu/h),98.16,14
Şarj Olma Süresi,98.16,8
Dış Ünite Isıtma Çalışma Aralığı(°C),98.16,4
Dış Ünite Soğutma Çalışma Aralığı(°C),98.08,9
Yıllık Tüketim (kW) Soğuma,98.08,14
Uyku Mode,98.08,1
Mevsimsel (SEER) Enerji Verimi Soğutma (W/W),98.08,9
Otomatik Hava Yönlendirme (Yukarı-Aşağı),98.08,1
Çerçeve,98.08,3
Küçük Izgara,98.08,1
Toz Torbası Kapasitesi,98.08,13
Ekran Kilidi,98.00,1
Bardak Koruma Sistemi,98.00,1
Soğutucu Akışkan,98.00,2
Gizli Gösterge,98.00,3
Soğutma Kapasitesi,98.00,12
Nem Alma,98.00,1
Tel Izgara,97.92,1
Gövde rengi,97.92,13
Saat Tipi,97.92,4
Dahili Depolama Kapasitesi,97.92,6
Alt Isıtıcı,97.85,1
Filtre Doluluk Göstergesi,97.85,1
Otomatik Kapı Açma Özelliği,97.85,1
Tek Tuşla Kontrol,97.77,1
Iyon Özelliği,97.77,1
Su Tankı Kapasitesi,97.77,15
Kahve Beki Adaptörü,97.69,2
Üst Sepet Ayar Tipi,97.69,1
Yarım Yük Yıkama,97.62,1
Elektroturbo (Fan Destekli Pişirme),97.62,1
Alt Sepet Katlanır Tel Sayısı,97.62,1
Kapak Açılma Yönü,97.54,1
Buharlı Pişirme,97.54,4
Dondurucu Bölme Aydınlatma Tipi,97.54,3
Motor Teknolojisi,97.54,1
Ağırlık (gr),97.54,21
Aux Girişi,97.54,1
Akım (A),97.46,1
Fincan Raf Sayısı,97.46,2
Davlumbaz Tipi,97.46,5
Su Güvenlik Sistemi,97.46,2
Yüksekliği Ayarlanabilir Fincan Rafları,97.46,1
Tuz Göstergesi,97.46,1
Paslanmaz Çelik İç Gövde,97.46,1
Çatal Kaşık Sepeti,97.46,2
Güç (W),97.46,2
Parlatıcı Göstergesi,97.46,1
Su Tüketimi,97.46,5
Enerji Tüketimi,97.46,9
Tambur Deseni,97.39,3
Kolayca Sökülebilir ve Temizlenebilir Komple İç Cam,97.39,1
Kalan Zaman Göstergesi,97.39,1
Montaj Yüksekliği (mm),97.31,4
Hızlı Soğutma,97.31,1
Tencere Izgara Tipi,97.31,8
Standart Tepsi Adedi,97.31,1
Fırın Hacmi,97.31,5
Elektrikli Izgara,97.31,1
Ön Kapak Cam Sayısı,97.31,2
Motor Gücü,97.23,20
HarvestFresh™,97.08,1
Bağlantı,97.00,3
ProSmart™ Inverter Kompresör,97.00,1
Kablo Uzunluğu,96.93,15
Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre),96.93,16
Filtre Tipi,96.85,4
Otomatik Kapanma,96.77,2
Bek Şapkası Tipi,96.69,3
Maksimum Çekiş Gücü,96.46,16
Lamba Adedi,96.46,2
Lamba Tipi,96.46,1
Bulaşık Makinesinde Yıkanabilir Filtre,96.46,1
Motor Sayısı,96.46,1
Kahvaltılık Çekmecesi,96.46,1
Yağ Filtre Adedi,96.46,3
Minimum Ses Seviyesi,96.46,10
Karbon Filtre,96.46,1
Lamba Gücü (W),96.46,3
Kademe Sayısı,96.46,2
Tatil Modu,96.39,1
Soğutucu Bölme Fanı,96.39,1
Sol Arka Bölme,96.31,8
Sol Ön Bölme,96.31,10
Toplam Elektrik Gücü (kW),96.31,6
Ürün Serisi,96.31,12
Gaz Tipi,96.23,1
Sağ Ön Bölme,96.23,8
Sağ Arka Bölme,96.23,9
Gaz Emniyet Sistemi,96.23,1
Ocak Ateşleme Tipi,96.23,1
Kontrol Tipi ve Yeri,96.00,4
Ocak Tipi Ve Göz Sayısı,96.00,10
Ocak Tipi,96.00,4
Soğutucu Bölme Hacmi (L),95.93,19
Sebzelik Adedi,95.93,2
Dondurucu Çekmece Sayısı,95.85,6
Su Geçirmezlik,95.77,6
Elektronik Gösterge,95.54,12
Ocak Yüzeyi,95.54,3
Kontrol Tipi,95.54,6
Aydınlatma Tipi,95.47,6
Kapı Yönü Değiştirme,95.31,1
Günlük Dondurma Kapasitesi (kg/Gün),95.31,22
Çocuk Kilidi,95.00,1
Ürün Ailesi,94.93,5
Buzluk Tipi,94.93,6
Pil Kapasitesi,94.85,8
Çift Hatlı,94.85,1
İşletim Sistemi Versionu,94.47,6
Voltaj,94.31,2
Sıcaklık Yükselme Süresi (Saat),94.16,13
Dondurucu Yeri,94.08,6
Dondurucu Bölme Hacmi (L),94.08,33
Toplam Hacim (L),94.00,37
Ses Seviyesi Sınıfı,94.00,2
Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP),94.00,39
Günlük Enerji Tüketimi (kwh/Gün),94.00,43
Soğutma Sistemi,94.00,3
İklim Sınıfı,94.00,2
Kulaklık Tipi,93.85,14
Yüz Haritalama,93.31,1
Kapasite,93.31,24
Ses Kayıt,93.08,1
Yıllık Enerji Tüketimi (kWh),92.85,57
Mikrofon,92.39,2
Kontrol Sistemi,92.31,7
RAM Kapasitesi,91.70,7
Programlar,91.24,44
Arka Kamera,91.08,15
GPS,91.08,1
Görüntülü Konuşma,90.32,1
Motor Tipi,89.93,16
Ön Kamera Flaş,89.93,1
Kamera Zoom,89.62,2
Ekran Çözünürlüğü,89.47,20
İşlemci Çekirdek Sayısı,89.16,6
Ses Seviyesi,89.01,26
Güç,88.55,45
İşlemci,88.39,27
Ürün Tipi,87.78,12
NFC,87.55,1
Fonksiyonlar,87.39,40
2.Arka Kamera,86.63,1
Marka,86.55,4
Dahili Hafıza,86.55,5
Wi-Fi,85.78,1
Ön Kamera,85.55,12
İşletim Sistemi,84.09,13
Ekran Boyutu,83.47,24
Renk,82.78,34
Ekran Tipi,82.55,11
Enerji Sınıfı,81.17,9
enerji_sinifi,79.25,9
Bluetooth,78.55,4
Ürün Rengi,61.88,47
Boyut (cm) (GxYxD),56.50,151
Ağırlık: Paketsiz,54.50,272
Derinlik,18.91,180
Genişlik,17.60,79
Yükseklik,14.99,105
fiyat,9.61,544
favori_sayisi,4.92,120
Subcategory,0.00,46
Main_Category,0.00,6
Product_Group,0.00,171
urun_adi,0.00,1236
urun_linki,0.00,1301

In [231]:
tek_degerli_rapor = []

for col in df.columns:
    try:
        # Boş olmayan verileri al
        gecerli_veri = df[col].dropna()
        
        # Eğer sadece 1 çeşit değer varsa
        if gecerli_veri.nunique() == 1:
            tek_deger = gecerli_veri.iloc[0] # O tek değeri yakala
            doluluk = (len(gecerli_veri) / len(df)) * 100
            tek_degerli_rapor.append({
                'Sütun Adı': col, 
                'İçindeki Tek Değer': tek_deger,
                'Doluluk Oranı (%)': round(doluluk, 2)
            })
            
    except TypeError:
        # Liste barındıran sütunlar için hata yakalama
        gecerli_veri = df[col].dropna()
        if gecerli_veri.apply(lambda x: tuple(x) if isinstance(x, list) else x).nunique() == 1:
            tek_deger = gecerli_veri.iloc[0]
            doluluk = (len(gecerli_veri) / len(df)) * 100
            tek_degerli_rapor.append({
                'Sütun Adı': col, 
                'İçindeki Tek Değer': str(tek_deger), # Listeyi metin gibi göster
                'Doluluk Oranı (%)': round(doluluk, 2)
            })

# Raporu DataFrame'e çevir ve doluluk oranına göre sırala
df_rapor = pd.DataFrame(tek_degerli_rapor)
df_rapor = df_rapor.sort_values(by='Doluluk Oranı (%)', ascending=False).reset_index(drop=True)

# Limitleri kaldırıp tabloyu gösterelim
pd.set_option('display.max_rows', None)
df_rapor

,Sütun Adı,İçindeki Tek Değer,Doluluk Oranı (%)
0,Wi-Fi,Var,14.22
1,2.Arka Kamera,Var,13.37
2,NFC,Var,12.45
3,Ön Kamera Flaş,Var,10.07
4,Görüntülü Konuşma,Var,9.68
5,GPS,Var,8.92
6,Ses Kayıt,Var,6.92
7,Yüz Haritalama,Var,6.69
8,Çift Hatlı,Var,5.15
9,Çocuk Kilidi,Var,5.00
10,Kapı Yönü Değiştirme,Var,4.69
11,Gaz Emniyet Sistemi,Var,3.77
12,Gaz Tipi,Doğalgaz,3.77
13,Ocak Ateşleme Tipi,Düğmeden Ateşleme,3.77
14,Soğutucu Bölme Fanı,Var,3.61
15,Tatil Modu,Var,3.61
16,Kahvaltılık Çekmecesi,Var,3.54
17,Bulaşık Makinesinde Yıkanabilir Filtre,Var,3.54
18,Karbon Filtre,Opsiyonel,3.54
19,Motor Sayısı,1,3.54
20,Lamba Tipi,Led,3.54
21,ProSmart™ Inverter Kompresör,Var,3.00
22,HarvestFresh™,Standard,2.92
23,Hızlı Soğutma,Var,2.69
24,Elektrikli Izgara,Var,2.69
25,Standart Tepsi Adedi,1,2.69
26,Kalan Zaman Göstergesi,Var,2.61
27,Kolayca Sökülebilir ve Temizlenebilir Komple İ...,Var,2.61
28,Tuz Göstergesi,Var,2.54
29,Akım (A),10,2.54
30,Yüksekliği Ayarlanabilir Fincan Rafları,Var,2.54
31,Paslanmaz Çelik İç Gövde,Var,2.54
32,Parlatıcı Göstergesi,Var,2.54
33,Motor Teknolojisi,AeroPerfect,2.46
34,Kapak Açılma Yönü,Aşağı Açılır,2.46
35,Aux Girişi,Var,2.46
36,Elektroturbo (Fan Destekli Pişirme),Var,2.38
37,Alt Sepet Katlanır Tel Sayısı,4,2.38
38,Yarım Yük Yıkama,Var,2.38
39,Üst Sepet Ayar Tipi,3 Kademeli Ayar,2.31
40,Tek Tuşla Kontrol,Var,2.23
41,Iyon Özelliği,Var,2.23
42,Filtre Doluluk Göstergesi,Var,2.15
43,Alt Isıtıcı,Var,2.15
44,Otomatik Kapı Açma Özelliği,Var,2.15
45,Tel Izgara,1,2.08
46,Bardak Koruma Sistemi,Var,2.00
47,Ekran Kilidi,Var,2.00
48,Nem Alma,Var,2.00
49,Küçük Izgara,Var,1.92
50,Otomatik Hava Yönlendirme (Yukarı-Aşağı),Var,1.92
51,Uyku Mode,Var,1.92
52,Otomatik Kapanma Özelliği,Var,1.84
53,Üst Sepet Katlanır Tel Sayısı,3,1.77
54,Sessiz Mod,Var,1.61
55,USB Bağlantısı,Var,1.54
56,Dengesiz Yük Kontrolü,Var,1.54
57,Elektronik Su Kontrol Sistemi,Var,1.54
58,Deterjan Sistemi,Var,1.54
59,Su Girişi,Tek (Soğuk),1.54
60,Hızlı Şarj desteği,Var,1.54
61,Otomatik Temizleme,Var,1.54
62,Motor Tipi (ÇM),ProSmart™Inverter,1.46
63,EverFresh+ Teknolojisi,Var,1.46
64,Su Kesik İkazı,Var,1.46
65,Su Taşma Emniyet Sistemi,Var,1.46
66,Bulaşık Makinesinde Yıkanabilir Aksesuarlar,Var,1.46
67,Sıcaklık Ayarı Kilidi,Var,1.46
68,IronFast,Var,1.38
69,Sesli Uyarı,Var,1.38
70,Akıllı Çalışma Sistemi,Var,1.38
71,Dar Ağızlı Uç,Var,1.38
72,Fırın İçi Aydınlatma,Var,1.38
73,LCD Ekran,Var,1.38
74,Ayarlanabilir Led Aydınlatma,Sarı-Beyaz-Gün Işığı Renk Seçenekleri,1.31
75,Fan Destekli Isıtıcı,Var,1.31
76,Anti Spill Teknolojisi (Taşmayı Önleme),Var,1.31
77,Döşeme/Koltuk Fırçası,Var,1.31
78,Işıklı Uyarı,Var,1.31
79,Cook Sense Teknolojisi (Pişmeyi Algılama),Var,1.31
80,Hava Temizleme Özelliği,Var,1.31
81,Ölçü Kaşığı,Var,1.31
82,Çıkarılabilir Su tankı,Var,1.31
83,Yoğun Emiş Gücü,Var,1.31
84,Kablo Sarma Yuvası,Var,1.23
85,İşletim Sistemi Özellikleri,"Windows 11 Home Single Language, Turkish / Eng...",1.23
86,Derin Tepsi Adedi,1,1.23
87,3D Pişirme,Var,1.23
88,HDMI,Var,1.23
89,Enerji Kontrol,Var,1.15
90,Yumuşak Hava,Var,1.15
91,Tank Pozisyonu,Üst,1.08
92,Zaman Erteleme Özelliği,0-24 Saat,1.08
93,Kondenser Temizleme Uyarısı,Var,1.08
94,Direkt Su Tahliyesi,Var,1.08
95,Dokunmatik Tuş,Var,1.08
96,Tambur Aydınlatma,DC LED,1.08
97,Fıltre Temizleme Uyarısı,Var,1.08
98,Aşırı Isınma Emniyeti,Var,1.08
99,Su Tankı Dolu Uyarısı,Var,1.08
100,Donma Emniyeti,Var,1.08
101,Anlık Tüketim Göstergesi,Var,1.08
102,Fincan Boyutu Seçimi,Var,1.08
103,Kir Sensörü,Var,1.00
104,Cool Shot,Var,1.00
105,Sıcak Tutma Özelliği,Var,1.00
106,4 Yönlü Otomatik Hava Kontrolü,Var,1.00
107,FitFry Teknolojisi,Var,1.00
108,Paslanmaz Çelik Bıçak,Var,0.92
109,Teleskopik Ray Sistemi,1 Seviye,0.92
110,Fan ve Alt Isıtıcı,Var,0.92
111,Ürün Kilidi,Var,0.92
112,Seramik Izgara,Var,0.85
113,Mikrofon (MPA),yok,0.85
114,Auto Swing,Var,0.85
115,Pasta Tepsi Adedi,1,0.85
116,LED Ekran,Var,0.85
117,Turbo Özelliği,Var,0.85
118,Dikey Ütüleme,Var,0.85
119,Fön Başlığı,Var,0.85
120,Paspas Özelliği,Var,0.85
121,İç Ünite Isıtma Çalışma Aralığı(°C),16~30,0.77
122,Şarj istasyonu,Var,0.77
123,Önden Ayarlanablir Arka Ayaklar,Var,0.77
124,Çıkarılabilir Plakalar,Var,0.77
125,Saçları Pürüzsüz ve Kıvırcık Yapma,Var,0.77
126,Çıkarılabilir hava giriş ızgarası,Var,0.77
127,Yüksek Performanslı Elektrikli Fırça,Var,0.77
128,Dinamik Rezistans,Var,0.69
129,Soğuk Ayarı,Var,0.69
130,Yüksek Bazaya Montaj,Var (Maksimum 50 cm),0.69
131,Led Fırça,Var,0.69
132,Kilitleme Mandalı,Var,0.69
133,Blender Ayağı Malzemesi,Metal,0.69
134,Paslanmaz Çelik Blender,Var,0.69
135,ProScent Teknolojisi,Tazeleme,0.61
136,3 Yollu Vana Blokaj Sistemi,Var,0.61
137,Otomatik By-Pass Sistemi,Var,0.61
138,Turbo Fırça,Var,0.61
139,Ölçü Kabı,Var,0.61
140,Hava Emiş Emniyeti,Var,0.61
141,Açma/Kapama Düğmesi,Var,0.61
142,Güvenlik Kilidi,Var,0.61
143,Doğrayıcı Kabı,Var,0.61
144,Duvara Monte Edilebilen Şarj aleti,Var,0.61
145,Difüzör Başlığı,Var,0.61
146,Asma Halkası,Var,0.61
147,Doğrayıcı,Var,0.61
148,Yakıt Cinsi,Elektrik,0.61
149,Cihaz Tipi,Premix Tam Yoğuşmalı,0.61
150,Yerden Isıtmaya Uygunluk,Var,0.61
151,Mevsimsel Mahal Isıtma Enerji Verimliliği Sınıfı,A,0.61
152,Oda Termostatı İle Çalışma,Var,0.61
153,Su Isıtma Enerji Verimliliği Sınıfı,A,0.61
154,Alev Modülasyonu,Var,0.61
155,Su Isıtma Yük Profili,XL,0.61
156,Uzaktan Kumanda,Var,0.61
157,Yakıt Tipi,Doğalgaz,0.61
158,Pompa Anti Blokaj Sistemi,Var,0.61
159,Emniyet Ventili,Var,0.61
160,Baca Tipi,Hermetik,0.61
161,Fan Modülasyonu,Var,0.61
162,Arıza Teşhis Sistemi,Var,0.61
163,Emniyet Termostatı,Var,0.61
164,Alev Sönme Emniyeti,Var,0.61
165,Paslanmaz Çelik Çırpıcı,Var,0.54
166,Hızlı Dondurma Bölmesi,Var,0.54
167,Vigo Difüzör Başlık,Var,0.54
168,Taşıma sapı,Var,0.54
169,360° Derece Dönebilen Hortum,Var,0.54
170,Kullanım tipi,Var,0.54
171,Pişirme Haznesi,"Çıkarılabilir, yanmaz, yapışmaz",0.54
172,Devrilme Emniyeti,Var,0.54
173,Maksimum Çalışma Basıncı,13 bar,0.54
174,Type¬C veya Micro USB kablolarıyla şarj edileb...,Var,0.54
175,Kapak,Çekmece Sistemi,0.54
176,Yağ Toplama Haznesi,Var,0.54
177,Sıcaklık Kontrolü,Var,0.54
178,Çalışma Göstergesi,Var,0.54
179,İkili Isıtma Sistemi,Var,0.54
180,Tank Materyali,Paslanmaz Çelik,0.46
181,Kontrol Sistemi Tipi,Mekanik,0.46
182,Enerji sınıfı (WH) (EP),C,0.46
183,IP Sınıfı,IPX2,0.46
184,Titanyum Emaye Kaplamalı Kazan,Var,0.46
185,İzolasyon,Monoblok Poliuretan,0.46
186,Yüksek Basınç Emniyet Valfi,Var,0.46
187,Susuz Çalışma Emniyeti,Var,0.46
188,Koruma Sınıfı,IP 25,0.46
189,Korozyona Karşı Koruma,Var,0.46
190,Su Seviye Göstergesi,Var,0.46
191,360° Dönebilen Kablosuz Kullanım,Var,0.46
192,Işıklı Açma/Kapama Düğmesi,Var,0.46
193,Buharsız Ütüleme,Var,0.46
194,Ütü Tipi,Buharlı Ütü,0.46
195,Şok Buhar Özelliği,Var,0.46

In [232]:
silinecek_sutunlar = []
donusturulen_sutunlar = []

for col in df.columns:
    try:
        # Sadece eşsiz değeri 1 olan sütunlarla ilgileniyoruz
        gecerli_veri = df[col].dropna()
        if gecerli_veri.nunique() == 1:
            # O tek değeri al ve küçük harfe çevir (küçük/büyük harf karmaşasını önlemek için)
            tek_deger = str(gecerli_veri.iloc[0]).strip().lower()
            
            # KURAL 1: İstisna (Gaz Tipi -> Doğalgaz)
            if col == 'Gaz Tipi' and tek_deger == 'doğalgaz':
                df = df.rename(columns={'Gaz Tipi': 'Doğalgaz'})
                # Dolu olanları 1, boş (NaN) olanları 0 yap
                df['Doğalgaz'] = df['Doğalgaz'].notnull().astype(int)
                donusturulen_sutunlar.append('Doğalgaz (Eski adı: Gaz Tipi)')
                
            # KURAL 2: İçinde 'var' geçiyorsa tut ve 1/0 yap
            elif 'var' in tek_deger:
                df[col] = df[col].notnull().astype(int)
                donusturulen_sutunlar.append(col)
                
            # KURAL 3: İçinde 'var' geçmiyorsa ve istisna değilse silinecekler listesine at
            else:
                silinecek_sutunlar.append(col)
                
    except TypeError:
        # Liste içeren sütunlarda da aynı mantığı işlet
        gecerli_veri = df[col].dropna()
        if gecerli_veri.apply(lambda x: tuple(x) if isinstance(x, list) else x).nunique() == 1:
            tek_deger = str(gecerli_veri.iloc[0]).strip().lower()
            if 'var' in tek_deger:
                df[col] = df[col].notnull().astype(int)
                donusturulen_sutunlar.append(col)
            else:
                silinecek_sutunlar.append(col)

# 4. ADIM: İçinde "var" geçmeyen tek değerli çöp sütunları sil
df = df.drop(columns=silinecek_sutunlar)

print(f"Toplam {len(donusturulen_sutunlar)} adet 'Var' içeren sütun 1/0 formatına dönüştürülüp kurtarıldı!")
print(f"İçinde 'Var' geçmeyen {len(silinecek_sutunlar)} adet gereksiz sütun silindi.")
print("-" * 40)
print(f"Güncel Sütun Sayısı: {len(df.columns)}")

Toplam 152 adet 'Var' içeren sütun 1/0 formatına dönüştürülüp kurtarıldı!
İçinde 'Var' geçmeyen 44 adet gereksiz sütun silindi.
----------------------------------------
Güncel Sütun Sayısı: 394

In [233]:
# verbose=True ve show_counts=True parametreleri gizlemeyi önler ve tüm detayları verir
df.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 394 columns):
 #    Column                                                         Non-Null Count  Dtype
---   ------                                                         --------------  -----
 0    urun_linki                                                     1301 non-null   str
 1    urun_adi                                                       1301 non-null   str
 2    fiyat                                                          1176 non-null   float64
 3    enerji_sinifi                                                  270 non-null    str
 4    favori_sayisi                                                  1237 non-null   Int64
 5    Product_Group                                                  1301 non-null   str
 6    Main_Category                                                  1301 non-null   str
 7    Subcategory                                                    1301 non-null   str
 8    Dondurucu Bölme Teknolojisi                                    12 non-null     str
 9    Derinlik                                                       1055 non-null   str
 10   Genişlik                                                       1072 non-null   str
 11   Yükseklik                                                      1106 non-null   str
 12   Sıcaklık Yükselme Süresi (Saat)                                76 non-null     str
 13   Ürün Rengi                                                     496 non-null    str
 14   Dondurucu Yeri                                                 77 non-null     str
 15   Elektronik Gösterge                                            58 non-null     str
 16   Kontrol Sistemi                                                100 non-null    str
 17   Tatil Modu                                                     1301 non-null   int64
 18   ProSmart™ Inverter Kompresör                                   1301 non-null   int64
 19   Aydınlatma Tipi                                                59 non-null     str
 20   Kapı Yönü Değiştirme                                           1301 non-null   int64
 21   İklim Sınıfı                                                   78 non-null     str
 22   Ses Seviyesi                                                   143 non-null    str
 23   Toplam Hacim (L)                                               78 non-null     str
 24   Ses Seviyesi Sınıfı                                            78 non-null     str
 25   Soğutma Sistemi                                                78 non-null     str
 26   Soğutucu Bölme Fanı                                            1301 non-null   int64
 27   EverFresh+ Teknolojisi                                         1301 non-null   int64
 28   Soğutucu Bölme Hacmi (L)                                       53 non-null     str
 29   Kahvaltılık Çekmecesi                                          1301 non-null   int64
 30   Dondurucu Çekmece Sayısı                                       54 non-null     str
 31   Buzluk Tipi                                                    66 non-null     str
 32   Dondurucu Bölme Aydınlatma Tipi                                32 non-null     str
 33   Dondurucu Bölme Hacmi (L)                                      77 non-null     str
 34   Sebzelik Adedi                                                 53 non-null     str
 35   Enerji Sınıfı                                                  245 non-null    str
 36   Yıllık Enerji Tüketimi (kWh)                                   93 non-null     str
 37   Günlük Enerji Tüketimi (kwh/Gün)                               78 non-null     str
 38   Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP)             78 non-null     str
 39   Ağırlık: Paketsiz                                              592 non-null    str
 40   Boyut (cm) (GxYxD)                                             566 non-null    str
 41   Ürün Tipi                                                      159 non-null    str
 42   Günlük Dondurma Kapasitesi (kg/Gün)                            61 non-null     str
 43   Kapı Kilidi                                                    16 non-null     str
 44   Hızlı Soğutma                                                  1301 non-null   int64
 45   Toplam Dondurucu Bölme Sayısı                                  19 non-null     str
 46   Kapaklı Bölme Sayısı                                           7 non-null      str
 47   Hızlı Dondurma Bölmesi                                         1301 non-null   int64
 48   Kapasite                                                       87 non-null     str
 49   Maksimum Sıkma Devri                                           20 non-null     str
 50   IronFast                                                       1301 non-null   int64
 51   Çocuk Kilidi                                                   1301 non-null   int64
 52   Deterjan Sistemi                                               1301 non-null   int64
 53   Buhar                                                          20 non-null     str
 54   Motor Tipi                                                     131 non-null    str
 55   Tambur Deseni                                                  34 non-null     str
 56   Elektronik Su Kontrol Sistemi                                  1301 non-null   int64
 57   Gösterge Tipi                                                  23 non-null     str
 58   Kalan Zaman Göstergesi                                         1301 non-null   int64
 59   Su Taşma Emniyet Sistemi                                       1301 non-null   int64
 60   Dengesiz Yük Kontrolü                                          1301 non-null   int64
 61   Su Kesik İkazı                                                 1301 non-null   int64
 62   Su Tüketimi (1 Çevrim)                                         19 non-null     str
 63   Enerji Tüketimi (100 Çevrim)                                   19 non-null     str
 64   Programlar                                                     114 non-null    object
 65   Dinamik Rezistans                                              1301 non-null   int64
 66   Bağlantı                                                       39 non-null     str
 67   Fonksiyonlar                                                   164 non-null    object
 68   Ekran Tipi                                                     227 non-null    str
 69   Paslanmaz Çelik İç Gövde                                       1301 non-null   int64
 70   Otomatik Kapı Açma Özelliği                                    1301 non-null   int64
 71   Bardak Koruma Sistemi                                          1301 non-null   int64
 72   Yarım Yük Yıkama                                               1301 non-null   int64
 73   Yüksekliği Ayarlanabilir Fincan Rafları                        1301 non-null   int64
 74   Fincan Raf Sayısı                                              33 non-null     str
 75   Çatal Kaşık Sepeti                                             33 non-null     str
 76   Güç (W)                                                        33 non-null     str
 77   Enerji Tüketimi                                                33 non-null     str
 78   Su Tüketimi                                                    33 non-null     str
 79   Parlatıcı Göstergesi                                           1301 non-null   int64
 80   Tuz Göstergesi                                                 1301 non-null   int64
 81   Su Güvenlik Sistemi                                            33 non-null     str
 82   Kir Sensörü                                                    1301 non-null   int64
 83   Kurutma Kapasitesi                                             15 non-null     str
 84   Dokunmatik Tuş                                                 1301 non-null   int64
 85   Direkt Su Tahliyesi                                            1301 non-null   int64
 86   Su Tankı Dolu Uyarısı                                          1301 non-null   int64
 87   Kondenser Temizleme Uyarısı                                    1301 non-null   int64
 88   Fıltre Temizleme Uyarısı                                       1301 non-null   int64
 89   Pratik Filtre                                                  13 non-null     str
 90   Isı pompalı Kurutma Teknolojisi                                14 non-null     str
 91   Akıllı Nem Sensörü                                             14 non-null     str
 92   Tambur Hacmi (L)                                               14 non-null     str
 93   Ses Gücü Seviyesi (dBA)                                        14 non-null     str
 94   Ürün Serisi                                                    48 non-null     str
 95   Fırın Hacmi                                                    35 non-null     str
 96   Fırın İçi Aydınlatma                                           1301 non-null   int64
 97   Elektrikli Izgara                                              1301 non-null   int64
 98   Ön Kapak Cam Sayısı                                            35 non-null     str
 99   Elektroturbo (Fan Destekli Pişirme)                            1301 non-null   int64
 100  Saat Tipi                                                      27 non-null     str
 101  Fan ve Alt Isıtıcı                                             1301 non-null   int64
 102  Alt Isıtıcı                                                    1301 non-null   int64
 103  Fan Destekli Isıtıcı                                           1301 non-null   int64
 104  Küçük Izgara                                                   1301 non-null   int64
 105  Kolayca Sökülebilir ve Temizlenebilir Komple İç Cam            1301 non-null   int64
 106  Buharlı Pişirme                                                32 non-null     str
 107  Doğalgaz                                                       1301 non-null   int64
 108  Ocak Yüzeyi                                                    58 non-null     str
 109  Kahve Beki Adaptörü                                            30 non-null     str
 110  Gaz Emniyet Sistemi                                            1301 non-null   int64
 111  Buhar Destekli Pişirme                                         11 non-null     str
 112  3D Pişirme                                                     1301 non-null   int64
 113  FitFry Teknolojisi                                             1301 non-null   int64
 114  Ekran Kilidi                                                   1301 non-null   int64
 115  Ocak Tipi Ve Göz Sayısı                                        52 non-null     str
 116  Ocak Tipi                                                      52 non-null     str
 117  Bek Şapkası Tipi                                               43 non-null     str
 118  Kontrol Tipi ve Yeri                                           52 non-null     str
 119  Sol Ön Bölme                                                   48 non-null     str
 120  Sağ Arka Bölme                                                 49 non-null     str
 121  Toplam Elektrik Gücü (kW)                                      48 non-null     str
 122  Tencere Izgara Tipi                                            35 non-null     str
 123  Çerçeve                                                        25 non-null     str
 124  Sağ Ön Bölme                                                   49 non-null     str
 125  Sol Arka Bölme                                                 48 non-null     str
 126  Güç                                                            149 non-null    str
 127  Zamanlayıcı                                                    24 non-null     str
 128  Sıcaklık Ayarı                                                 22 non-null     str
 129  Bulaşık Makinesinde Yıkanabilir Aksesuarlar                    1301 non-null   int64
 130  İç Hazne Malzemesi                                             9 non-null      str
 131  LCD Ekran                                                      1301 non-null   int64
 132  Aşırı Isınma Emniyeti                                          1301 non-null   int64
 133  Damacana Yeri                                                  6 non-null      str
 134  Musluk                                                         8 non-null      str
 135  Soğuk su tank kapasitesi (L)                                   6 non-null      str
 136  Soğuk Su Derecesi Aralığı                                      6 non-null      str
 137  Soğutma Kapasitesi (lt/saat)                                   6 non-null      str
 138  Yoğun Emiş Gücü (m³/h)                                         17 non-null     str
 139  Minimum Ses Seviyesi                                           46 non-null     str
 140  Davlumbaz Tipi                                                 33 non-null     str
 141  Cam Dekor Rengi                                                15 non-null     str
 142  Maksimum Çekiş Gücü                                            46 non-null     str
 143  Yağ Filtre Adedi                                               46 non-null     str
 144  Montaj Yüksekliği (mm)                                         35 non-null     str
 145  Bulaşık Makinesinde Yıkanabilir Filtre                         1301 non-null   int64
 146  Kontrol Tipi                                                   58 non-null     str
 147  Lamba Adedi                                                    46 non-null     str
 148  Lamba Gücü (W)                                                 46 non-null     str
 149  Yoğun Emiş Gücü                                                1301 non-null   int64
 150  Otomatik Kapanma Özelliği                                      1301 non-null   int64
 151  Kademe Sayısı                                                  46 non-null     str
 152  Filtre Tipi                                                    41 non-null     str
 153  Filtre Doluluk Göstergesi                                      1301 non-null   int64
 154  Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre)  40 non-null     str
 155  Hava Temizleme Özelliği                                        1301 non-null   int64
 156  Önden Ayarlanablir Arka Ayaklar                                1301 non-null   int64
 157  Yüksek Bazaya Montaj                                           1301 non-null   int64
 158  Tezgah Altı Yüksekliği                                         10 non-null     str
 159  Ekran Boyutu                                                   215 non-null    str
 160  İşlemci Tipi                                                   19 non-null     str
 161  RAM Kapasitesi                                                 108 non-null    str
 162  RAM Özellikleri                                                16 non-null     str
 163  İşletim Sistemi                                                207 non-null    str
 164  USB Bağlantısı                                                 1301 non-null   int64
 165  HDMI                                                           1301 non-null   int64
 166  İşlemci Özellikleri                                            16 non-null     str
 167  Pil Ömrü                                                       16 non-null     str
 168  Bluetooth                                                      279 non-null    str
 169  SSD Kapasitesi                                                 20 non-null     str
 170  SSD Özellikleri                                                19 non-null     str
 171  Ekran Kartı Özellikleri                                        15 non-null     str
 172  Dahili Depolama Kapasitesi                                     27 non-null     str
 173  Arka Kamera                                                    116 non-null    str
 174  Ön Kamera                                                      188 non-null    str
 175  Aksesuar (Ek Donanım)                                          15 non-null     str
 176  İşlemci                                                        151 non-null    str
 177  Ekran Çözünürlüğü                                              137 non-null    str
 178  Pil                                                            17 non-null     str
 179  Micro USB                                                      15 non-null     str
 180  Mikrofon                                                       99 non-null     str
 181  Bellek                                                         17 non-null     str
 182  Hoparlör                                                       9 non-null      str
 183  GPS                                                            1301 non-null   int64
 184  Harddisk Kapasitesi                                            12 non-null     str
 185  Uyumlu Olduğu Platformlar                                      12 non-null     str
 186  Bağlantılar                                                    7 non-null      str
 187  Kulaklık Tipi                                                  80 non-null     str
 188  NFC                                                            1301 non-null   int64
 189  Aux Girişi                                                     1301 non-null   int64
 190  Uzaktan Kumanda                                                1301 non-null   int64
 191  Dahili Hafıza                                                  175 non-null    str
 192  Renk                                                           224 non-null    str
 193  İşlemci Çekirdek Sayısı                                        141 non-null    str
 194  2.Arka Kamera                                                  1301 non-null   int64
 195  Kamera Zoom                                                    135 non-null    str
 196  Ön Kamera Flaş                                                 1301 non-null   int64
 197  Wi-Fi                                                          1301 non-null   int64
 198  Marka                                                          175 non-null    str
 199  Yüz Haritalama                                                 1301 non-null   int64
 200  Çift Hatlı                                                     1301 non-null   int64
 201  Ses Kayıt                                                      1301 non-null   int64
 202  Pil Kapasitesi                                                 67 non-null     str
 203  Ürün Ailesi                                                    66 non-null     str
 204  İşletim Sistemi Versionu                                       72 non-null     str
 205  Görüntülü Konuşma                                              1301 non-null   int64
 206  3 cihazı aynı anda şarj edebilme                               9 non-null      str
 207  Ağırlık (gr)                                                   32 non-null     str
 208  Uyumlu olduğu modeller (MPA)                                   21 non-null     str
 209  Çıkış Gücü                                                     17 non-null     str
 210  Güvenli şarj için akım korumalı                                12 non-null     str
 211  Hızlı Şarj desteği                                             1301 non-null   int64
 212  Kablo Tipi                                                     15 non-null     str
 213  Giriş Gücü                                                     11 non-null     str
 214  Type¬C veya Micro USB kablolarıyla şarj edilebilir             1301 non-null   int64
 215  Kablo uzunluğu                                                 12 non-null     str
 216  Şarj süresi                                                    8 non-null      str
 217  Su Geçirmezlik                                                 55 non-null     str
 218  Soğutma Kapasitesi                                             26 non-null     str

In [234]:
# Renk
renk_gruplari = {
    'siyah': ['siyah', 'antrasit', 'grafit', 'piyano', 'midnight', 'dark', 'koyu', 'cosmic', 'black'],
    'gri': ['gri', 'i̇noks', 'inoks', 'gümüş', 'metalik', 'manhattan', 'platinum', 'glass', 'gray', 'grey', 'silver'],
    'mavi': ['mavi', 'buz', 'cool', 'cloud', 'arctic', 'starlight', 'quiet', 'lacivert', 'blue'],
    'pembe': ['pembe', 'rose', 'cherry', 'lilac', 'blossom', 'menekşe', 'pink'],
    'beyaz': ['beyaz', 'i̇pek', 'ipek', 'doğal', 'harmony', 'şeffaf', 'white'],
    'kırmızı': ['kırmızı', 'red'],
    'sarı': ['sarı', 'yellow', 'altın', 'gold'],
    'yeşil': ['yeşil', 'green'],
    'turuncu': ['turuncu', 'orange'],
    'bej': ['bej', 'beige'],
    'mor': ['mor', 'purple'],
    'kahverengi': ['kahverengi', 'brown']
}

# 1. ADIM: İsminde 'renk' veya 'reng' geçen tüm sütunları otomatik bul
renk_sutunlari = [col for col in df.columns if 'renk' in col.lower() or 'reng' in col.lower()]

print(f"Tespit edilen renk sütunları ({len(renk_sutunlari)} adet):\n{renk_sutunlari}\n")

# 2. ADIM: Hatalı "kolay" değerlerini NaN (boş) yap
# Regex ile büyük/küçük harf veya etrafındaki boşluklar fark etmeksizin "kolay" değerini yakalarız
for col in renk_sutunlari:
    df[col] = df[col].replace(r'(?i)^\s*kolay\s*$', np.nan, regex=True)

# 3. ADIM: Her satır için bu sütunlardaki metinleri yan yana birleştirip küçük harfe çevir
kombine_renk_metni = df[renk_sutunlari].fillna('').astype(str).agg(' '.join, axis=1).str.lower()

# 4. ADIM: Renk sözlüğünü dön ve makinenin anlayacağı 1/0 sütunlarını yarat
olusturulan_renk_sutunlari = []

for ana_renk, kelimeler in renk_gruplari.items():
    pattern = '|'.join(kelimeler)
    yeni_sutun_adi = f"Renk_{ana_renk.capitalize()}"
    olusturulan_renk_sutunlari.append(yeni_sutun_adi)
    
    # Kelimelerden biri geçiyorsa 1, geçmiyorsa 0 ata
    df[yeni_sutun_adi] = kombine_renk_metni.str.contains(pattern, case=False, na=False).astype(int)

# 5. ADIM: Dağınıklık yaratan eski renk sütunlarını DataFrame'den tamamen sil
df = df.drop(columns=renk_sutunlari)

print("İşlem Başarılı! 'Kolay' hataları temizlendi, renkler 1/0 olarak gruplandı ve eski sütunlar silindi.")
print("-" * 50)
print(f"Oluşturulan Yeni Sütunlar:\n{olusturulan_renk_sutunlari}\n")
print(f"Güncel Sütun Sayısı: {len(df.columns)}")

Tespit edilen renk sütunları (8 adet):
['Ürün Rengi', 'Cam Dekor Rengi', 'Renk', 'Kanat Rengi', 'Gövde Rengi', 'Cezve Rengi', 'Ürün rengi', 'Gövde rengi']

İşlem Başarılı! 'Kolay' hataları temizlendi, renkler 1/0 olarak gruplandı ve eski sütunlar silindi.
--------------------------------------------------
Oluşturulan Yeni Sütunlar:
['Renk_Siyah', 'Renk_Gri', 'Renk_Mavi', 'Renk_Pembe', 'Renk_Beyaz', 'Renk_Kırmızı', 'Renk_Sarı', 'Renk_Yeşil', 'Renk_Turuncu', 'Renk_Bej', 'Renk_Mor', 'Renk_Kahverengi']

Güncel Sütun Sayısı: 398

In [235]:
# Enerji Sınıfı 
# 1. ÇELİŞENLER: İki sütun da dolu ama değerler BİRBİRİNDEN FARKLI MI?
celisenler = df[(df['enerji_sinifi'].notnull()) & (df['Enerji Sınıfı'].notnull()) & (df['enerji_sinifi'] != df['Enerji Sınıfı'])]

print("1. ÇELİŞEN DEĞERLER (İki sütun da dolu ama içindeki bilgiler farklı)")
print("-" * 60)
if len(celisenler) > 0:
    print(f"Dikkat! {len(celisenler)} satırda iki sütun birbiriyle çelişiyor. İşte o satırlar:")
    display(celisenler[['enerji_sinifi', 'Enerji Sınıfı']])
else:
    print("Harika! İki sütunun da dolu olduğu yerlerde hiçbir çelişki (farklılık) yok.")


# 2. EKSİĞİ TAMAMLAYANLAR: Ana sütunda olmayıp, diğerinde olanlar
farkli_olanlar = df[df['enerji_sinifi'].isnull() & df['Enerji Sınıfı'].notnull()]

print("\n2. EKLENECEK FARKLI DEĞERLER (Ana sütunda yok, yedek sütunda var)")
print("-" * 60)
if len(farkli_olanlar) > 0:
    print(f"Ana sütuna aktarılacak toplam {len(farkli_olanlar)} adet veri var. İşte tablosu:")
    # Çok uzun olmasın diye ilk 15 tanesini gösterelim (istersen .head(15) kısmını silebilirsin)
    display(farkli_olanlar[['enerji_sinifi', 'Enerji Sınıfı']].head(15))
else:
    print("Aktarılacak farklı bir veri bulunamadı.")


# 3. BİRLEŞTİRME VE TEMİZLİK İŞLEMİ
print("\n3. BİRLEŞTİRME SONUCU")
print("-" * 60)
# 'enerji_sinifi'ndeki boş (NaN) olan yerleri 'Enerji Sınıfı'ndaki değerlerle doldur
df['enerji_sinifi'] = df['enerji_sinifi'].fillna(df['Enerji Sınıfı'])

# İşi biten yedek sütunu tamamen sil
df = df.drop(columns=['Enerji Sınıfı'])

print("İşlem Başarılı! Farklı olan/eksik olan veriler ana sütuna aktarıldı ve yedek sütun silindi.")
print(f"Güncel 'enerji_sinifi' dolu satır sayısı: {df['enerji_sinifi'].notnull().sum()}")

1. ÇELİŞEN DEĞERLER (İki sütun da dolu ama içindeki bilgiler farklı)
------------------------------------------------------------
Harika! İki sütunun da dolu olduğu yerlerde hiçbir çelişki (farklılık) yok.

2. EKLENECEK FARKLI DEĞERLER (Ana sütunda yok, yedek sütunda var)
------------------------------------------------------------
Aktarılacak farklı bir veri bulunamadı.

3. BİRLEŞTİRME SONUCU
------------------------------------------------------------
İşlem Başarılı! Farklı olan/eksik olan veriler ana sütuna aktarıldı ve yedek sütun silindi.
Güncel 'enerji_sinifi' dolu satır sayısı: 270

In [236]:
# Su Tüketimi

#  Ana sütun ve yedek sütun isimlerini belirliyoruz
ana_sutun = 'Su Tüketimi'
yedek_sutun = 'Su Tüketimi (1 Çevrim)'

# 1. ÇELİŞENLER: İki sütun da dolu ama değerler BİRBİRİNDEN FARKLI MI?
celisenler = df[(df[ana_sutun].notnull()) & (df[yedek_sutun].notnull()) & (df[ana_sutun] != df[yedek_sutun])]

print("1. ÇELİŞEN DEĞERLER (İki sütun da dolu ama içindeki bilgiler farklı)")
print("-" * 60)
if len(celisenler) > 0:
    print(f"Dikkat! {len(celisenler)} satırda iki sütun birbiriyle çelişiyor. İşte o satırlar:")
    display(celisenler[[ana_sutun, yedek_sutun]])
else:
    print(f"Harika! '{ana_sutun}' ve '{yedek_sutun}' sütunlarının ikisinin de dolu olduğu yerlerde hiçbir çelişki yok.")


# 2. EKSİĞİ TAMAMLAYANLAR: Ana sütunda olmayıp, diğerinde olanlar
farkli_olanlar = df[df[ana_sutun].isnull() & df[yedek_sutun].notnull()]

print("\n2. EKLENECEK FARKLI DEĞERLER (Ana sütunda yok, yedek sütunda var)")
print("-" * 60)
if len(farkli_olanlar) > 0:
    print(f"Ana sütuna aktarılacak toplam {len(farkli_olanlar)} adet veri var. İşte tablosu:")
    display(farkli_olanlar[[ana_sutun, yedek_sutun]].head(15))
else:
    print("Aktarılacak farklı bir veri bulunamadı.")


# 3. BİRLEŞTİRME VE TEMİZLİK İŞLEMİ
print("\n3. BİRLEŞTİRME SONUCU")
print("-" * 60)
# 'Su Tüketimi'ndeki boş (NaN) olan yerleri 'Su Tüketimi (1 Çevrim)'ndeki değerlerle doldur
df[ana_sutun] = df[ana_sutun].fillna(df[yedek_sutun])

# İşi biten yedek sütunu tamamen sil
df = df.drop(columns=[yedek_sutun])

print(f"İşlem Başarılı! Veriler '{ana_sutun}' sütununda birleştirildi ve '{yedek_sutun}' sütunu silindi.")
print(f"Güncel '{ana_sutun}' dolu satır sayısı: {df[ana_sutun].notnull().sum()}")

1. ÇELİŞEN DEĞERLER (İki sütun da dolu ama içindeki bilgiler farklı)
------------------------------------------------------------
Harika! 'Su Tüketimi' ve 'Su Tüketimi (1 Çevrim)' sütunlarının ikisinin de dolu olduğu yerlerde hiçbir çelişki yok.

2. EKLENECEK FARKLI DEĞERLER (Ana sütunda yok, yedek sütunda var)
------------------------------------------------------------
Ana sütuna aktarılacak toplam 19 adet veri var. İşte tablosu:

   Su Tüketimi Su Tüketimi (1 Çevrim)
79         NaN                   51 L
80         NaN                   49 L
81         NaN                   51 L
82         NaN                   44 L
83         NaN                   44 L
84         NaN                   49 L
85         NaN                   56 L
86         NaN                   52 L
87         NaN                   49 L
88         NaN                   40 L
89         NaN                   52 L
90         NaN                   45 L
91         NaN                   49 L
92         NaN                   51 L
93         NaN                   49 L

3. BİRLEŞTİRME SONUCU
------------------------------------------------------------
İşlem Başarılı! Veriler 'Su Tüketimi' sütununda birleştirildi ve 'Su Tüketimi (1 Çevrim)' sütunu silindi.
Güncel 'Su Tüketimi' dolu satır sayısı: 52

In [237]:
# Su Hazanesi - Su Tankı

def kapasite_duzelt(deger):
    if pd.isna(deger):
        return deger
    
    # Sayıyı ve birimi ayırmak için regex (Örn: "350 mL" içinden 350'yi ve mL'yi alır)
    deger_str = str(deger).lower().replace(',', '.')
    sayi_ara = re.search(r"(\d+\.?\d*)", deger_str)
    
    if sayi_ara:
        sayi = float(sayi_ara.group(1))
        # Eğer birim mL ise 1000'e bölerek Litre'ye çevir
        if 'ml' in deger_str:
            return sayi / 1000
        # Diğer durumlarda (Litre varsayıyoruz) sayıyı olduğu gibi bırak
        return sayi
    return np.nan

# 1. ADIM: Mevcut 'Su Tankı Kapasitesi'ni sayısallaştır ve mL -> L dönüşümü yap
df['Su Tankı Kapasitesi'] = df['Su Tankı Kapasitesi'].apply(kapasite_duzelt)

# 2. ADIM: Diğer sütun olan 'Soğuk su tank kapasitesi (L)' için de aynısını yap ve birleştir
if 'Soğuk su tank kapasitesi (L)' in df.columns:
    df['Soğuk su tank kapasitesi (L)'] = df['Soğuk su tank kapasitesi (L)'].apply(kapasite_duzelt)
    
    # Ana sütunu yedek sütunla doldur
    df['Su Tankı Kapasitesi'] = df['Su Tankı Kapasitesi'].fillna(df['Soğuk su tank kapasitesi (L)'])
    
    # İşi biten yedek sütunu sil
    df = df.drop(columns=['Soğuk su tank kapasitesi (L)'])

print("Birimler Standardize Edildi!")
print("-" * 40)
print(f"Su Tankı Kapasitesi sütunu artık 'Litre' cinsinden sayısal değerler içeriyor.")
print(f"Örnek Değerler: {df['Su Tankı Kapasitesi'].dropna().unique()[:5]}")
print(f"Toplam Dolu Satır: {df['Su Tankı Kapasitesi'].notnull().sum()}")

Birimler Standardize Edildi!
----------------------------------------
Su Tankı Kapasitesi sütunu artık 'Litre' cinsinden sayısal değerler içeriyor.
Örnek Değerler: [ 3.   3.6 44.   8.   6. ]
Toplam Dolu Satır: 35

In [238]:
# Ağırlık

def agirlik_temizle_ve_kg_yap(deger):
    if pd.isna(deger):
        return deger
    
    # Metni temizle: küçük harf yap, virgülü noktaya çevir
    deger_str = str(deger).lower().replace(',', '.')
    
    # Düzenli ifade (Regex) ile sayısal kısmı çek
    sayi_ara = re.search(r"(\d+\.?\d*)", deger_str)
    
    if sayi_ara:
        sayi = float(sayi_ara.group(1))
        
        # Birim kontrolü: Eğer gram ise 1000'e bölerek kg'a çevir
        if 'gr' in deger_str or 'gram' in deger_str:
            return sayi / 1000
        
        # Diğer durumlarda (kg veya birimsiz ise) kg kabul et
        return sayi
    return np.nan

# 1. ADIM: Ağırlıkla ilgili tüm sütunları tespit et
agirlik_sutunlari = [col for col in df.columns if 'ağırlık' in col.lower()]

# 2. ADIM: Her bir sütuna temizleme ve kg dönüşüm fonksiyonunu uygula
for col in agirlik_sutunlari:
    df[col] = df[col].apply(agirlik_temizle_ve_kg_yap)

# 3. ADIM: Tek bir standart isimli sütunda (Agirlik (kg)) birleştir
# Önce boş bir float sütun oluşturuyoruz
df['Agirlik (kg)'] = np.nan

# Hiyerarşik birleştirme (Önce net ağırlıkları, sonra paketliyi al)
oncelik_sirasi = ['Ağırlık: Paketsiz', 'Ağırlık (gr)', 'Ağırlık', 'Ağırlık: Paketli']

for sutun in oncelik_sirasi:
    if sutun in df.columns:
        df['Agirlik (kg)'] = df['Agirlik (kg)'].fillna(df[sutun])

# 4. ADIM: Veri tipini kesin olarak float yap ve eski sütunları sil
df['Agirlik (kg)'] = df['Agirlik (kg)'].astype(float)
df = df.drop(columns=agirlik_sutunlari, errors='ignore')

print("Ağırlık Verileri Standardize Edildi!")
print("-" * 50)
print(f"Yeni Sütun Adı: Agirlik (kg)")
print(f"Veri Tipi: {df['Agirlik (kg)'].dtype}")
print(f"Dolu Satır Sayısı: {df['Agirlik (kg)'].notnull().sum()}")
print("\nÖrnek Değerler (Kg cinsinden):")
print(df['Agirlik (kg)'].dropna().head())

Ağırlık Verileri Standardize Edildi!
--------------------------------------------------
Yeni Sütun Adı: Agirlik (kg)
Veri Tipi: float64
Dolu Satır Sayısı: 624

Örnek Değerler (Kg cinsinden):
0   115.00
1   105.00
2   105.00
3   105.00
4    87.50
Name: Agirlik (kg), dtype: float64

In [239]:
# Şarj Süresi

def sure_temizle_ve_dakika_yap(deger):
    if pd.isna(deger):
        return deger
    
    deger_str = str(deger).lower().replace(',', '.')
    
    # Sayıları bul (Örn: "3.5", "4-5" gibi durumlarda ilk sayıyı veya ortalamayı alabiliriz)
    # Burada ilk bulunan sayıyı alıyoruz
    sayilar = re.findall(r"(\d+\.?\d*)", deger_str)
    
    if sayilar:
        sayi = float(sayilar[0])
        
        # Birim kontrolü
        # Eğer 'saat' geçiyorsa 60 ile çarp (dakikaya çevir)
        if 'saat' in deger_str or 'sa' in deger_str or 'hr' in deger_str:
            return sayi * 60
        
        # Zaten dakika ise (dk, daki, min) olduğu gibi bırak
        return sayi
    
    return np.nan

# 1. ADIM: İlgili sütunları tespit et
sarj_sutunlari = ['Şarj Olma Süresi', 'Şarj süresi']

# 2. ADIM: Temizleme ve dakika dönüşümünü uygula
for col in sarj_sutunlari:
    if col in df.columns:
        df[col] = df[col].apply(sure_temizle_ve_dakika_yap)

# 3. ADIM: 'Sarj_Suresi_dk' isminde tek bir sütunda birleştir
df['Sarj_Suresi_dk'] = np.nan

if 'Şarj Olma Süresi' in df.columns:
    df['Sarj_Suresi_dk'] = df['Sarj_Suresi_dk'].fillna(df['Şarj Olma Süresi'])

if 'Şarj süresi' in df.columns:
    df['Sarj_Suresi_dk'] = df['Sarj_Suresi_dk'].fillna(df['Şarj süresi'])

# 4. ADIM: Eski sütunları sil
df = df.drop(columns=[col for col in sarj_sutunlari if col in df.columns], errors='ignore')

print("Şarj Süreleri Standardize Edildi!")
print("-" * 50)
print(f"Yeni Sütun Adı: Sarj_Suresi_dk")
print(f"Dolu Satır Sayısı: {df['Sarj_Suresi_dk'].notnull().sum()}")
print("\nÖrnek Değerler (Dakika cinsinden):")
print(df['Sarj_Suresi_dk'].dropna().unique()[:5])

Şarj Süreleri Standardize Edildi!
--------------------------------------------------
Yeni Sütun Adı: Sarj_Suresi_dk
Dolu Satır Sayısı: 32

Örnek Değerler (Dakika cinsinden):
[330. 180. 240. 120.  60.]

In [243]:
import re
import pandas as pd
import numpy as np

# 1. ADIM: GENEL BOOLEAN (EVET/VAR) DÖNÜŞÜMÜ (Hata Onarılmış Sürüm)
def boolean_cevir(val):
    # Eğer değer bir liste veya dizi ise, işlem yapmadan olduğu gibi bırak
    if isinstance(val, (list, np.ndarray, pd.Series, dict)): 
        return val
    
    # Boş değer kontrolü (Scalar değerler için)
    if pd.isna(val): 
        return val
        
    s = str(val).lower().strip()
    if s in ['evet', 'var', 'mevcut', 'yes', 'true', '1.0', '1']: 
        return 1
    if s in ['hayır', 'yok', 'mevcut değil', 'no', 'false', '0.0', '0']: 
        return 0
    return val

# Sadece metin sütunlarını seçip hatasız şekilde uygulayalım
obj_cols = df.select_dtypes(include=['object']).columns
for col in obj_cols:
    df[col] = df[col].apply(boolean_cevir)

# 2. ADIM: GELİŞMİŞ SAYI TEMİZLEYİCİ (BİRİM ODAKLI)
def ultra_temizleyici(deger):
    # Liste veya dizi gelirse temizleme işlemini pas geç (hata önleme)
    if isinstance(deger, (list, np.ndarray, dict)) or pd.isna(deger) or deger == "":
        return deger
    
    # Eğer zaten sayıysa, olduğu gibi bırak
    if isinstance(deger, (int, float)): 
        return float(deger)
    
    txt = str(deger).lower().replace(',', '.')
    
    # Regex: Birimin yanındaki sayıyı yakala
    match = re.search(r"(\d+\.?\d*)\s*(w|watt|kw|l|lt|litre|ml|gb|mb|mah|btu|kg|gr|gram|dk|dakika|saat|sa|cm|mm|db|kwh)", txt)
    
    if match:
        sayi = float(match.group(1))
        birim = match.group(2)
        if birim == 'kw': return sayi * 1000
        if birim == 'ml': return sayi / 1000
        if birim == 'mb': return sayi / 1024
        if birim in ['gr', 'gram']: return sayi / 1000
        if birim in ['saat', 'sa']: return sayi * 60
        if birim == 'mm': return sayi / 10
        return sayi
    
    # Sayıları bul ve en büyüğünü al
    sayilar = re.findall(r"(\d+\.?\d*)", txt)
    if sayilar:
        return max([float(s) for s in sayilar])
    return np.nan

# 3. ADIM: SAYISAL SÜTUNLARI TEMİZLEME
temizlenecek_sayisallar = ['Genişlik', 'Yükseklik', 'Derinlik', 'Ses Seviyesi', 'Yıllık Enerji Tüketimi (kWh)', 'fiyat']
for col in temizlenecek_sayisallar:
    if col in df.columns:
        df[col] = df[col].apply(ultra_temizleyici)

# 4. ADIM: GRUP BİRLEŞTİRME
mapping = {
    'Guc (W)': ['Lamba Gücü (W)', 'Güç (W) (9)', 'Motor Gücü', 'Isıtmada Çekilen Enerji (W)', 'Çıkış Gücü', 'Giriş Gücü'],
    'Agirlik (kg)': ['Ağırlık: Paketsiz', 'Ağırlık (gr)', 'Ağırlık: Paketli', 'Günlük Dondurma Kapasitesi (kg/Gün)'],
    'Sarj_Suresi_dk': ['Şarj Olma Süresi', 'Şarj süresi', 'Kablosuz Çalışma Süresi (Düşük Güç)', 'Kablosuz çalışma süresi(Orta güç)'],
    'Su_Kapasitesi (L)': ['Toplam Hacim (L)', 'Soğutucu Bölme Hacmi (L)', 'Dondurucu Bölme Hacmi (L)', 'Su Tankı Kapasitesi (L)', 'Su Haznesi'],
    'RAM (GB)': ['RAM Kapasitesi', 'Bellek'],
    'Depolama (GB)': ['SSD Kapasitesi', 'Dahili Depolama Kapasitesi', 'Harddisk Kapasitesi', 'Dahili Hafıza'],
    'Batarya (mAh)': ['Pil Kapasitesi', 'Batarya kapasitesi', 'Pil']
}

for yeni, eskiler in mapping.items():
    if yeni not in df.columns:
        df[yeni] = np.nan
    for eski in eskiler:
        if eski in df.columns:
            temiz_veri = df[eski].apply(ultra_temizleyici)
            df[yeni] = df[yeni].combine_first(temiz_veri)

# 5. ADIM: BOYUT PARÇALAMA
if 'Boyut (cm) (GxYxD)' in df.columns:
    boyut_split = df['Boyut (cm) (GxYxD)'].astype(str).str.extract(r'(\d+\.?\d*)\s*[xX*]\s*(\d+\.?\d*)\s*[xX*]\s*(\d+\.?\d*)')
    df['Genişlik'] = df['Genişlik'].combine_first(pd.to_numeric(boyut_split[0], errors='coerce'))
    df['Yükseklik'] = df['Yükseklik'].combine_first(pd.to_numeric(boyut_split[1], errors='coerce'))
    df['Derinlik'] = df['Derinlik'].combine_first(pd.to_numeric(boyut_split[2], errors='coerce'))

# 6. ADIM: TEMİZLİK VE TİP ZORLAMASI
silinecekler = [item for sublist in mapping.values() for item in sublist] + ['Boyut (cm) (GxYxD)']
df.drop(columns=[c for c in silinecekler if c in df.columns], errors='ignore', inplace=True)

# Zorunlu float dönüşümü
hedef_sutunlar = list(mapping.keys()) + temizlenecek_sayisallar
for col in hedef_sutunlar:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

print("Hata giderildi ve süreç tamamlandı! Sütunlar artık sayısal ve dolu.")

Hata giderildi ve süreç tamamlandı! Sütunlar artık sayısal ve dolu.

In [244]:
df.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 375 columns):
 #    Column                                                         Non-Null Count  Dtype
---   ------                                                         --------------  -----
 0    urun_linki                                                     1301 non-null   str
 1    urun_adi                                                       1301 non-null   str
 2    fiyat                                                          1176 non-null   float64
 3    enerji_sinifi                                                  270 non-null    str
 4    favori_sayisi                                                  1237 non-null   Int64
 5    Product_Group                                                  1301 non-null   str
 6    Main_Category                                                  1301 non-null   str
 7    Subcategory                                                    1301 non-null   str
 8    Dondurucu Bölme Teknolojisi                                    12 non-null     str
 9    Derinlik                                                       1055 non-null   float64
 10   Genişlik                                                       1072 non-null   float64
 11   Yükseklik                                                      1106 non-null   float64
 12   Sıcaklık Yükselme Süresi (Saat)                                76 non-null     str
 13   Dondurucu Yeri                                                 77 non-null     str
 14   Elektronik Gösterge                                            58 non-null     object
 15   Kontrol Sistemi                                                100 non-null    str
 16   Tatil Modu                                                     1301 non-null   int64
 17   ProSmart™ Inverter Kompresör                                   1301 non-null   int64
 18   Aydınlatma Tipi                                                59 non-null     str
 19   Kapı Yönü Değiştirme                                           1301 non-null   int64
 20   İklim Sınıfı                                                   78 non-null     str
 21   Ses Seviyesi                                                   143 non-null    float64
 22   Ses Seviyesi Sınıfı                                            78 non-null     str
 23   Soğutma Sistemi                                                78 non-null     str
 24   Soğutucu Bölme Fanı                                            1301 non-null   int64
 25   EverFresh+ Teknolojisi                                         1301 non-null   int64
 26   Kahvaltılık Çekmecesi                                          1301 non-null   int64
 27   Dondurucu Çekmece Sayısı                                       54 non-null     object
 28   Buzluk Tipi                                                    66 non-null     str
 29   Dondurucu Bölme Aydınlatma Tipi                                32 non-null     str
 30   Sebzelik Adedi                                                 53 non-null     object
 31   Yıllık Enerji Tüketimi (kWh)                                   93 non-null     float64
 32   Günlük Enerji Tüketimi (kwh/Gün)                               78 non-null     str
 33   Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP)             78 non-null     str
 34   Ürün Tipi                                                      159 non-null    str
 35   Kapı Kilidi                                                    16 non-null     float64
 36   Hızlı Soğutma                                                  1301 non-null   int64
 37   Toplam Dondurucu Bölme Sayısı                                  19 non-null     str
 38   Kapaklı Bölme Sayısı                                           7 non-null      object
 39   Hızlı Dondurma Bölmesi                                         1301 non-null   int64
 40   Kapasite                                                       87 non-null     str
 41   Maksimum Sıkma Devri                                           20 non-null     str
 42   IronFast                                                       1301 non-null   int64
 43   Çocuk Kilidi                                                   1301 non-null   int64
 44   Deterjan Sistemi                                               1301 non-null   int64
 45   Buhar                                                          20 non-null     str
 46   Motor Tipi                                                     131 non-null    str
 47   Tambur Deseni                                                  34 non-null     str
 48   Elektronik Su Kontrol Sistemi                                  1301 non-null   int64
 49   Gösterge Tipi                                                  23 non-null     str
 50   Kalan Zaman Göstergesi                                         1301 non-null   int64
 51   Su Taşma Emniyet Sistemi                                       1301 non-null   int64
 52   Dengesiz Yük Kontrolü                                          1301 non-null   int64
 53   Su Kesik İkazı                                                 1301 non-null   int64
 54   Enerji Tüketimi (100 Çevrim)                                   19 non-null     str
 55   Programlar                                                     114 non-null    object
 56   Dinamik Rezistans                                              1301 non-null   int64
 57   Bağlantı                                                       39 non-null     str
 58   Fonksiyonlar                                                   164 non-null    object
 59   Ekran Tipi                                                     227 non-null    str
 60   Paslanmaz Çelik İç Gövde                                       1301 non-null   int64
 61   Otomatik Kapı Açma Özelliği                                    1301 non-null   int64
 62   Bardak Koruma Sistemi                                          1301 non-null   int64
 63   Yarım Yük Yıkama                                               1301 non-null   int64
 64   Yüksekliği Ayarlanabilir Fincan Rafları                        1301 non-null   int64
 65   Fincan Raf Sayısı                                              33 non-null     str
 66   Çatal Kaşık Sepeti                                             33 non-null     str
 67   Güç (W)                                                        33 non-null     str
 68   Enerji Tüketimi                                                33 non-null     str
 69   Su Tüketimi                                                    52 non-null     str
 70   Parlatıcı Göstergesi                                           1301 non-null   int64
 71   Tuz Göstergesi                                                 1301 non-null   int64
 72   Su Güvenlik Sistemi                                            33 non-null     str
 73   Kir Sensörü                                                    1301 non-null   int64
 74   Kurutma Kapasitesi                                             15 non-null     str
 75   Dokunmatik Tuş                                                 1301 non-null   int64
 76   Direkt Su Tahliyesi                                            1301 non-null   int64
 77   Su Tankı Dolu Uyarısı                                          1301 non-null   int64
 78   Kondenser Temizleme Uyarısı                                    1301 non-null   int64
 79   Fıltre Temizleme Uyarısı                                       1301 non-null   int64
 80   Pratik Filtre                                                  13 non-null     object
 81   Isı pompalı Kurutma Teknolojisi                                14 non-null     str
 82   Akıllı Nem Sensörü                                             14 non-null     str
 83   Tambur Hacmi (L)                                               14 non-null     str
 84   Ses Gücü Seviyesi (dBA)                                        14 non-null     str
 85   Ürün Serisi                                                    48 non-null     str
 86   Fırın Hacmi                                                    35 non-null     str
 87   Fırın İçi Aydınlatma                                           1301 non-null   int64
 88   Elektrikli Izgara                                              1301 non-null   int64
 89   Ön Kapak Cam Sayısı                                            35 non-null     str
 90   Elektroturbo (Fan Destekli Pişirme)                            1301 non-null   int64
 91   Saat Tipi                                                      27 non-null     str
 92   Fan ve Alt Isıtıcı                                             1301 non-null   int64
 93   Alt Isıtıcı                                                    1301 non-null   int64
 94   Fan Destekli Isıtıcı                                           1301 non-null   int64
 95   Küçük Izgara                                                   1301 non-null   int64
 96   Kolayca Sökülebilir ve Temizlenebilir Komple İç Cam            1301 non-null   int64
 97   Buharlı Pişirme                                                32 non-null     object
 98   Doğalgaz                                                       1301 non-null   int64
 99   Ocak Yüzeyi                                                    58 non-null     str
 100  Kahve Beki Adaptörü                                            30 non-null     str
 101  Gaz Emniyet Sistemi                                            1301 non-null   int64
 102  Buhar Destekli Pişirme                                         11 non-null     object
 103  3D Pişirme                                                     1301 non-null   int64
 104  FitFry Teknolojisi                                             1301 non-null   int64
 105  Ekran Kilidi                                                   1301 non-null   int64
 106  Ocak Tipi Ve Göz Sayısı                                        52 non-null     str
 107  Ocak Tipi                                                      52 non-null     str
 108  Bek Şapkası Tipi                                               43 non-null     str
 109  Kontrol Tipi ve Yeri                                           52 non-null     str
 110  Sol Ön Bölme                                                   48 non-null     str
 111  Sağ Arka Bölme                                                 49 non-null     str
 112  Toplam Elektrik Gücü (kW)                                      48 non-null     str
 113  Tencere Izgara Tipi                                            35 non-null     str
 114  Çerçeve                                                        25 non-null     str
 115  Sağ Ön Bölme                                                   49 non-null     str
 116  Sol Arka Bölme                                                 48 non-null     str
 117  Güç                                                            149 non-null    str
 118  Zamanlayıcı                                                    24 non-null     float64
 119  Sıcaklık Ayarı                                                 22 non-null     object
 120  Bulaşık Makinesinde Yıkanabilir Aksesuarlar                    1301 non-null   int64
 121  İç Hazne Malzemesi                                             9 non-null      str
 122  LCD Ekran                                                      1301 non-null   int64
 123  Aşırı Isınma Emniyeti                                          1301 non-null   int64
 124  Damacana Yeri                                                  6 non-null      str
 125  Musluk                                                         8 non-null      object
 126  Soğuk Su Derecesi Aralığı                                      6 non-null      str
 127  Soğutma Kapasitesi (lt/saat)                                   6 non-null      str
 128  Yoğun Emiş Gücü (m³/h)                                         17 non-null     str
 129  Minimum Ses Seviyesi                                           46 non-null     str
 130  Davlumbaz Tipi                                                 33 non-null     str
 131  Maksimum Çekiş Gücü                                            46 non-null     str
 132  Yağ Filtre Adedi                                               46 non-null     object
 133  Montaj Yüksekliği (mm)                                         35 non-null     str
 134  Bulaşık Makinesinde Yıkanabilir Filtre                         1301 non-null   int64
 135  Kontrol Tipi                                                   58 non-null     str
 136  Lamba Adedi                                                    46 non-null     str
 137  Yoğun Emiş Gücü                                                1301 non-null   int64
 138  Otomatik Kapanma Özelliği                                      1301 non-null   int64
 139  Kademe Sayısı                                                  46 non-null     str
 140  Filtre Tipi                                                    41 non-null     str
 141  Filtre Doluluk Göstergesi                                      1301 non-null   int64
 142  Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre)  40 non-null     str
 143  Hava Temizleme Özelliği                                        1301 non-null   int64
 144  Önden Ayarlanablir Arka Ayaklar                                1301 non-null   int64
 145  Yüksek Bazaya Montaj                                           1301 non-null   int64
 146  Tezgah Altı Yüksekliği                                         10 non-null     str
 147  Ekran Boyutu                                                   215 non-null    str
 148  İşlemci Tipi                                                   19 non-null     str
 149  RAM Özellikleri                                                16 non-null     str
 150  İşletim Sistemi                                                207 non-null    str
 151  USB Bağlantısı                                                 1301 non-null   int64
 152  HDMI                                                           1301 non-null   int64
 153  İşlemci Özellikleri                                            16 non-null     str
 154  Pil Ömrü                                                       16 non-null     str
 155  Bluetooth                                                      279 non-null    object
 156  SSD Özellikleri                                                19 non-null     str
 157  Ekran Kartı Özellikleri                                        15 non-null     str
 158  Arka Kamera                                                    116 non-null    str
 159  Ön Kamera                                                      188 non-null    str
 160  Aksesuar (Ek Donanım)                                          15 non-null     str
 161  İşlemci                                                        151 non-null    str
 162  Ekran Çözünürlüğü                                              137 non-null    str
 163  Micro USB                                                      15 non-null     str
 164  Mikrofon                                                       99 non-null     float64
 165  Hoparlör                                                       9 non-null      object
 166  GPS                                                            1301 non-null   int64
 167  Uyumlu Olduğu Platformlar                                      12 non-null     str
 168  Bağlantılar                                                    7 non-null      str
 169  Kulaklık Tipi                                                  80 non-null     str
 170  NFC                                                            1301 non-null   int64
 171  Aux Girişi                                                     1301 non-null   int64
 172  Uzaktan Kumanda                                                1301 non-null   int64
 173  İşlemci Çekirdek Sayısı                                        141 non-null    object
 174  2.Arka Kamera                                                  1301 non-null   int64
 175  Kamera Zoom                                                    135 non-null    str
 176  Ön Kamera Flaş                                                 1301 non-null   int64
 177  Wi-Fi                                                          1301 non-null   int64
 178  Marka                                                          175 non-null    str
 179  Yüz Haritalama                                                 1301 non-null   int64
 180  Çift Hatlı                                                     1301 non-null   int64
 181  Ses Kayıt                                                      1301 non-null   int64
 182  Ürün Ailesi                                                    66 non-null     str
 183  İşletim Sistemi Versionu                                       72 non-null     str
 184  Görüntülü Konuşma                                              1301 non-null   int64
 185  3 cihazı aynı anda şarj edebilme                               9 non-null      object
 186  Uyumlu olduğu modeller (MPA)                                   21 non-null     str
 187  Güvenli şarj için akım korumalı                                12 non-null     object
 188  Hızlı Şarj desteği                                             1301 non-null   int64
 189  Kablo Tipi                                                     15 non-null     str
 190  Type¬C veya Micro USB kablolarıyla şarj edilebilir             1301 non-null   int64
 191  Kablo uzunluğu                                                 12 non-null     str
 192  Su Geçirmezlik                                                 55 non-null     str
 193  Soğutma Kapasitesi                                             26 non-null     str
 194  Isıtma Kapasitesi (Btu/h)                                      24 non-null     str
 195  Yıllık Tüketim (kW) Soğuma                                     25 non-null     str
 196  Yıllık Tüketim Isıtma (kW)                                     24 non-null     str
 197  Voltaj                                                         74 non-null     str
 198  Isıtmadaki Enerji Verim Oranı (W/W)                            17 non-null     str
 199  Soğutucu Akışkan                                               26 non-null     str
 200  Mevsimsel (SCOP) Enerji Verimi Isıtma (W/W)                    24 non-null     str
 201  Mevsimsel (SEER) Enerji Verimi Soğutma (W/W)                   25 non-null     str
 202  Akıllı Çalışma Sistemi                                         1301 non-null   int64
 203  Gizli Gösterge                                                 26 non-null     str
 204  Uyku Mode                                                      1301 non-null   int64
 205  İç Ünite Soğutma Çalışma Aralığı(°C)                           12 non-null     str
 206  Dış Ünite Soğutma Çalışma Aralığı(°C)                          25 non-null     str
 207  Dış Ünite Isıtma Çalışma Aralığı(°C)                           24 non-null     str
 208  Özel Filtreler                                                 23 non-null     str
 209  Otomatik Temizleme                                             1301 non-null   int64
 210  Otomatik Hava Yönlendirme (Yukarı-Aşağı)                       1301 non-null   int64
 211  4 Yönlü Otomatik Hava Kontrolü                                 1301 non-null   int64
 212  Nem Alma                                                       1301 non-null   int64
 213  Enerji Sınıfı-Isıtma                                           22 non-null     str
 214  Kapasite (Isıtma)                                              20 non-null     str
 215  Anlık Tüketim Göstergesi                                       1301 non-null   int64
 216  Enerji Kontrol                                                 1301 non-null   int64
 217  Sessiz Mod                                                     1301 non-null   int64

In [245]:
# --- 1. SES SEVİYESİ VE DEVİR TEMİZLİĞİ ---
def sadece_sayi_cek(val):
    if pd.isna(val) or isinstance(val, (int, float)): return val
    num = re.search(r"(\d+)", str(val))
    return float(num.group(1)) if num else np.nan

# Ses Seviyelerini birleştir
if 'Ses Gücü Seviyesi (dBA)' in df.columns:
    df['Ses Seviyesi'] = df['Ses Seviyesi'].fillna(df['Ses Gücü Seviyesi (dBA)'].apply(sadece_sayi_cek))
    df.drop(columns=['Ses Gücü Seviyesi (dBA)'], inplace=True)

# Sıkma Devrini sayısallaştır
if 'Maksimum Sıkma Devri' in df.columns:
    df['Sikma_Devri'] = df['Maksimum Sıkma Devri'].apply(sadece_sayi_cek)
    df.drop(columns=['Maksimum Sıkma Devri'], inplace=True)

# --- 2. GERİDE KALAN HACİM SÜTUNLARINI STANDARTLAŞTIRMA ---
# Tambur, Fırın, Toz Haznesi gibi hacimleri ultra_temizleyici ile float yap
hacim_adaylari = ['Tambur Hacmi (L)', 'Fırın Hacmi', 'Kurutma Kapasitesi', 
                  'Pişirme Kapasitesi', 'İç Hazne Kapasitesi', 'Toz Haznesi Kapasitesi']

for col in hacim_adaylari:
    if col in df.columns:
        df[col] = df[col].apply(ultra_temizleyici)

# --- 3. ÇOK SEYREK SÜTUNLARI SİLME ---
# 10'dan az veri içeren sütunları temizleyerek gürültüyü azaltıyoruz
limit = 10
seyrek_cols = [col for col in df.columns if df[col].count() < limit]
# Önemli olabilecek kategori sütunlarını koruyalım
korunacaklar = ['urun_linki', 'urun_adi', 'fiyat']
seyrek_cols = [c for c in seyrek_cols if c not in korunacaklar]

df.drop(columns=seyrek_cols, inplace=True)

# --- 4. TİP DÜZELTME (OBJECT -> STR/INT) ---
# Hala object görünen ama aslında string olanları netleştirelim
obj_to_str = df.select_dtypes(include=['object']).columns
for col in obj_to_str:
    # Liste içermeyenleri str yapalım
    if not df[col].apply(lambda x: isinstance(x, list)).any():
        df[col] = df[col].astype(str).replace('nan', np.nan)

print(f"Final Dokunuş Tamamlandı! Kalan Sütun Sayısı: {len(df.columns)}")

Final Dokunuş Tamamlandı! Kalan Sütun Sayısı: 340

In [246]:
df.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 340 columns):
 #    Column                                                         Non-Null Count  Dtype
---   ------                                                         --------------  -----
 0    urun_linki                                                     1301 non-null   str
 1    urun_adi                                                       1301 non-null   str
 2    fiyat                                                          1176 non-null   float64
 3    enerji_sinifi                                                  270 non-null    str
 4    favori_sayisi                                                  1237 non-null   Int64
 5    Product_Group                                                  1301 non-null   str
 6    Main_Category                                                  1301 non-null   str
 7    Subcategory                                                    1301 non-null   str
 8    Dondurucu Bölme Teknolojisi                                    12 non-null     str
 9    Derinlik                                                       1055 non-null   float64
 10   Genişlik                                                       1072 non-null   float64
 11   Yükseklik                                                      1106 non-null   float64
 12   Sıcaklık Yükselme Süresi (Saat)                                76 non-null     str
 13   Dondurucu Yeri                                                 77 non-null     str
 14   Elektronik Gösterge                                            58 non-null     str
 15   Kontrol Sistemi                                                100 non-null    str
 16   Tatil Modu                                                     1301 non-null   int64
 17   ProSmart™ Inverter Kompresör                                   1301 non-null   int64
 18   Aydınlatma Tipi                                                59 non-null     str
 19   Kapı Yönü Değiştirme                                           1301 non-null   int64
 20   İklim Sınıfı                                                   78 non-null     str
 21   Ses Seviyesi                                                   157 non-null    float64
 22   Ses Seviyesi Sınıfı                                            78 non-null     str
 23   Soğutma Sistemi                                                78 non-null     str
 24   Soğutucu Bölme Fanı                                            1301 non-null   int64
 25   EverFresh+ Teknolojisi                                         1301 non-null   int64
 26   Kahvaltılık Çekmecesi                                          1301 non-null   int64
 27   Dondurucu Çekmece Sayısı                                       54 non-null     str
 28   Buzluk Tipi                                                    66 non-null     str
 29   Dondurucu Bölme Aydınlatma Tipi                                32 non-null     str
 30   Sebzelik Adedi                                                 53 non-null     str
 31   Yıllık Enerji Tüketimi (kWh)                                   93 non-null     float64
 32   Günlük Enerji Tüketimi (kwh/Gün)                               78 non-null     str
 33   Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP)             78 non-null     str
 34   Ürün Tipi                                                      159 non-null    str
 35   Kapı Kilidi                                                    16 non-null     float64
 36   Hızlı Soğutma                                                  1301 non-null   int64
 37   Toplam Dondurucu Bölme Sayısı                                  19 non-null     str
 38   Hızlı Dondurma Bölmesi                                         1301 non-null   int64
 39   Kapasite                                                       87 non-null     str
 40   IronFast                                                       1301 non-null   int64
 41   Çocuk Kilidi                                                   1301 non-null   int64
 42   Deterjan Sistemi                                               1301 non-null   int64
 43   Buhar                                                          20 non-null     str
 44   Motor Tipi                                                     131 non-null    str
 45   Tambur Deseni                                                  34 non-null     str
 46   Elektronik Su Kontrol Sistemi                                  1301 non-null   int64
 47   Gösterge Tipi                                                  23 non-null     str
 48   Kalan Zaman Göstergesi                                         1301 non-null   int64
 49   Su Taşma Emniyet Sistemi                                       1301 non-null   int64
 50   Dengesiz Yük Kontrolü                                          1301 non-null   int64
 51   Su Kesik İkazı                                                 1301 non-null   int64
 52   Enerji Tüketimi (100 Çevrim)                                   19 non-null     str
 53   Programlar                                                     114 non-null    object
 54   Dinamik Rezistans                                              1301 non-null   int64
 55   Bağlantı                                                       39 non-null     str
 56   Fonksiyonlar                                                   164 non-null    object
 57   Ekran Tipi                                                     227 non-null    str
 58   Paslanmaz Çelik İç Gövde                                       1301 non-null   int64
 59   Otomatik Kapı Açma Özelliği                                    1301 non-null   int64
 60   Bardak Koruma Sistemi                                          1301 non-null   int64
 61   Yarım Yük Yıkama                                               1301 non-null   int64
 62   Yüksekliği Ayarlanabilir Fincan Rafları                        1301 non-null   int64
 63   Fincan Raf Sayısı                                              33 non-null     str
 64   Çatal Kaşık Sepeti                                             33 non-null     str
 65   Güç (W)                                                        33 non-null     str
 66   Enerji Tüketimi                                                33 non-null     str
 67   Su Tüketimi                                                    52 non-null     str
 68   Parlatıcı Göstergesi                                           1301 non-null   int64
 69   Tuz Göstergesi                                                 1301 non-null   int64
 70   Su Güvenlik Sistemi                                            33 non-null     str
 71   Kir Sensörü                                                    1301 non-null   int64
 72   Kurutma Kapasitesi                                             15 non-null     float64
 73   Dokunmatik Tuş                                                 1301 non-null   int64
 74   Direkt Su Tahliyesi                                            1301 non-null   int64
 75   Su Tankı Dolu Uyarısı                                          1301 non-null   int64
 76   Kondenser Temizleme Uyarısı                                    1301 non-null   int64
 77   Fıltre Temizleme Uyarısı                                       1301 non-null   int64
 78   Pratik Filtre                                                  13 non-null     str
 79   Isı pompalı Kurutma Teknolojisi                                14 non-null     str
 80   Akıllı Nem Sensörü                                             14 non-null     str
 81   Tambur Hacmi (L)                                               14 non-null     float64
 82   Ürün Serisi                                                    48 non-null     str
 83   Fırın Hacmi                                                    35 non-null     float64
 84   Fırın İçi Aydınlatma                                           1301 non-null   int64
 85   Elektrikli Izgara                                              1301 non-null   int64
 86   Ön Kapak Cam Sayısı                                            35 non-null     str
 87   Elektroturbo (Fan Destekli Pişirme)                            1301 non-null   int64
 88   Saat Tipi                                                      27 non-null     str
 89   Fan ve Alt Isıtıcı                                             1301 non-null   int64
 90   Alt Isıtıcı                                                    1301 non-null   int64
 91   Fan Destekli Isıtıcı                                           1301 non-null   int64
 92   Küçük Izgara                                                   1301 non-null   int64
 93   Kolayca Sökülebilir ve Temizlenebilir Komple İç Cam            1301 non-null   int64
 94   Buharlı Pişirme                                                32 non-null     str
 95   Doğalgaz                                                       1301 non-null   int64
 96   Ocak Yüzeyi                                                    58 non-null     str
 97   Kahve Beki Adaptörü                                            30 non-null     str
 98   Gaz Emniyet Sistemi                                            1301 non-null   int64
 99   Buhar Destekli Pişirme                                         11 non-null     str
 100  3D Pişirme                                                     1301 non-null   int64
 101  FitFry Teknolojisi                                             1301 non-null   int64
 102  Ekran Kilidi                                                   1301 non-null   int64
 103  Ocak Tipi Ve Göz Sayısı                                        52 non-null     str
 104  Ocak Tipi                                                      52 non-null     str
 105  Bek Şapkası Tipi                                               43 non-null     str
 106  Kontrol Tipi ve Yeri                                           52 non-null     str
 107  Sol Ön Bölme                                                   48 non-null     str
 108  Sağ Arka Bölme                                                 49 non-null     str
 109  Toplam Elektrik Gücü (kW)                                      48 non-null     str
 110  Tencere Izgara Tipi                                            35 non-null     str
 111  Çerçeve                                                        25 non-null     str
 112  Sağ Ön Bölme                                                   49 non-null     str
 113  Sol Arka Bölme                                                 48 non-null     str
 114  Güç                                                            149 non-null    str
 115  Zamanlayıcı                                                    24 non-null     float64
 116  Sıcaklık Ayarı                                                 22 non-null     str
 117  Bulaşık Makinesinde Yıkanabilir Aksesuarlar                    1301 non-null   int64
 118  LCD Ekran                                                      1301 non-null   int64
 119  Aşırı Isınma Emniyeti                                          1301 non-null   int64
 120  Yoğun Emiş Gücü (m³/h)                                         17 non-null     str
 121  Minimum Ses Seviyesi                                           46 non-null     str
 122  Davlumbaz Tipi                                                 33 non-null     str
 123  Maksimum Çekiş Gücü                                            46 non-null     str
 124  Yağ Filtre Adedi                                               46 non-null     str
 125  Montaj Yüksekliği (mm)                                         35 non-null     str
 126  Bulaşık Makinesinde Yıkanabilir Filtre                         1301 non-null   int64
 127  Kontrol Tipi                                                   58 non-null     str
 128  Lamba Adedi                                                    46 non-null     str
 129  Yoğun Emiş Gücü                                                1301 non-null   int64
 130  Otomatik Kapanma Özelliği                                      1301 non-null   int64
 131  Kademe Sayısı                                                  46 non-null     str
 132  Filtre Tipi                                                    41 non-null     str
 133  Filtre Doluluk Göstergesi                                      1301 non-null   int64
 134  Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre)  40 non-null     str
 135  Hava Temizleme Özelliği                                        1301 non-null   int64
 136  Önden Ayarlanablir Arka Ayaklar                                1301 non-null   int64
 137  Yüksek Bazaya Montaj                                           1301 non-null   int64
 138  Tezgah Altı Yüksekliği                                         10 non-null     str
 139  Ekran Boyutu                                                   215 non-null    str
 140  İşlemci Tipi                                                   19 non-null     str
 141  RAM Özellikleri                                                16 non-null     str
 142  İşletim Sistemi                                                207 non-null    str
 143  USB Bağlantısı                                                 1301 non-null   int64
 144  HDMI                                                           1301 non-null   int64
 145  İşlemci Özellikleri                                            16 non-null     str
 146  Pil Ömrü                                                       16 non-null     str
 147  Bluetooth                                                      279 non-null    str
 148  SSD Özellikleri                                                19 non-null     str
 149  Ekran Kartı Özellikleri                                        15 non-null     str
 150  Arka Kamera                                                    116 non-null    str
 151  Ön Kamera                                                      188 non-null    str
 152  Aksesuar (Ek Donanım)                                          15 non-null     str
 153  İşlemci                                                        151 non-null    str
 154  Ekran Çözünürlüğü                                              137 non-null    str
 155  Micro USB                                                      15 non-null     str
 156  Mikrofon                                                       99 non-null     float64
 157  GPS                                                            1301 non-null   int64
 158  Uyumlu Olduğu Platformlar                                      12 non-null     str
 159  Kulaklık Tipi                                                  80 non-null     str
 160  NFC                                                            1301 non-null   int64
 161  Aux Girişi                                                     1301 non-null   int64
 162  Uzaktan Kumanda                                                1301 non-null   int64
 163  İşlemci Çekirdek Sayısı                                        141 non-null    str
 164  2.Arka Kamera                                                  1301 non-null   int64
 165  Kamera Zoom                                                    135 non-null    str
 166  Ön Kamera Flaş                                                 1301 non-null   int64
 167  Wi-Fi                                                          1301 non-null   int64
 168  Marka                                                          175 non-null    str
 169  Yüz Haritalama                                                 1301 non-null   int64
 170  Çift Hatlı                                                     1301 non-null   int64
 171  Ses Kayıt                                                      1301 non-null   int64
 172  Ürün Ailesi                                                    66 non-null     str
 173  İşletim Sistemi Versionu                                       72 non-null     str
 174  Görüntülü Konuşma                                              1301 non-null   int64
 175  Uyumlu olduğu modeller (MPA)                                   21 non-null     str
 176  Güvenli şarj için akım korumalı                                12 non-null     str
 177  Hızlı Şarj desteği                                             1301 non-null   int64
 178  Kablo Tipi                                                     15 non-null     str
 179  Type¬C veya Micro USB kablolarıyla şarj edilebilir             1301 non-null   int64
 180  Kablo uzunluğu                                                 12 non-null     str
 181  Su Geçirmezlik                                                 55 non-null     str
 182  Soğutma Kapasitesi                                             26 non-null     str
 183  Isıtma Kapasitesi (Btu/h)                                      24 non-null     str
 184  Yıllık Tüketim (kW) Soğuma                                     25 non-null     str
 185  Yıllık Tüketim Isıtma (kW)                                     24 non-null     str
 186  Voltaj                                                         74 non-null     str
 187  Isıtmadaki Enerji Verim Oranı (W/W)                            17 non-null     str
 188  Soğutucu Akışkan                                               26 non-null     str
 189  Mevsimsel (SCOP) Enerji Verimi Isıtma (W/W)                    24 non-null     str
 190  Mevsimsel (SEER) Enerji Verimi Soğutma (W/W)                   25 non-null     str
 191  Akıllı Çalışma Sistemi                                         1301 non-null   int64
 192  Gizli Gösterge                                                 26 non-null     str
 193  Uyku Mode                                                      1301 non-null   int64
 194  İç Ünite Soğutma Çalışma Aralığı(°C)                           12 non-null     str
 195  Dış Ünite Soğutma Çalışma Aralığı(°C)                          25 non-null     str
 196  Dış Ünite Isıtma Çalışma Aralığı(°C)                           24 non-null     str
 197  Özel Filtreler                                                 23 non-null     str
 198  Otomatik Temizleme                                             1301 non-null   int64
 199  Otomatik Hava Yönlendirme (Yukarı-Aşağı)                       1301 non-null   int64
 200  4 Yönlü Otomatik Hava Kontrolü                                 1301 non-null   int64
 201  Nem Alma                                                       1301 non-null   int64
 202  Enerji Sınıfı-Isıtma                                           22 non-null     str
 203  Kapasite (Isıtma)                                              20 non-null     str
 204  Anlık Tüketim Göstergesi                                       1301 non-null   int64
 205  Enerji Kontrol                                                 1301 non-null   int64
 206  Sessiz Mod                                                     1301 non-null   int64
 207  Yumuşak Hava                                                   1301 non-null   int64
 208  Auto Swing                                                     1301 non-null   int64
 209  Dış Ünite (GxYxD) mm                                           21 non-null     str
 210  İç Ünite (GxYxD) mm                                            21 non-null     str
 211  Su Tankı Kapasitesi                                            35 non-null     float64
 212  Hız Kademesi adedi                                             11 non-null     str
 213  Vantilatör Tipi                                                11 non-null     str
 214  Devrilme Emniyeti                                              1301 non-null   int64
 215  Isıtma Gücü                                                    11 non-null     str
 216  Titanyum Emaye Kaplamalı Kazan                                 1301 non-null   int64
 217  Yüksek Basınç Emniyet Valfi                                    1301 non-null   int64
 218  Susuz Çalışma Emniyeti                                         1301 non-null   int64

In [247]:
# Adım 1: Güç Sütunlarını Nihai Olarak Birleştirme
# 114 (Güç) ve 109 (kW) sütunlarını temizleyip ana sütuna aktaralım
guc_ek_adaylar = ['Güç', 'Toplam Elektrik Gücü (kW)', 'Güç (W)', 'Güç (W) (9)']

for col in guc_ek_adaylar:
    if col in df.columns:
        # Daha önce yazdığımız ultra_temizleyici'yi kullanarak sayıya çeviriyoruz
        cleaned = df[col].apply(ultra_temizleyici)
        df['Guc (W)'] = df['Guc (W)'].combine_first(cleaned)

# Adım 2: Enerji ve Su Tüketimini Sayısallaştırma
tuketim_cols = ['Günlük Enerji Tüketimi (kwh/Gün)', 'Enerji Tüketimi (100 Çevrim)', 'Su Tüketimi']
for col in tuketim_cols:
    if col in df.columns:
        df[col] = df[col].apply(ultra_temizleyici)

# Adım 3: Kalan Teknik Özellikleri Temizleme
teknik_cols = ['Maksimum Sıkma Devri', 'Kapasite', 'Toz Torbası Kapasitesi']
for col in teknik_cols:
    if col in df.columns:
        df[col] = df[col].apply(ultra_temizleyici)

# Adım 4: Gereksizleşen Ara Sütunları Silme
# Artık Guc (W) içinde toplandıkları için orijinallerini silebiliriz
df.drop(columns=[c for c in guc_ek_adaylar if c in df.columns], errors='ignore', inplace=True)

# Adım 5: Çok Seyrek Sütunları Budama
# Bir satırda 20'den az (yaklaşık %1.5 doluluk) veri varsa o sütunu silelim
limit = 20
seyrek_sutunlar = [col for col in df.columns if df[col].count() < limit]
# Fiyat gibi hedef değişkenleri koru
korunacaklar = ['urun_linki', 'urun_adi', 'fiyat', 'Main_Category', 'Subcategory']
seyrek_sutunlar = [c for c in seyrek_sutunlar if c not in korunacaklar]

df.drop(columns=seyrek_sutunlar, inplace=True)

# Adım 6: Final Tip Zorlaması (Object -> String)
# Kalan metin sütunlarını netleştirelim
obj_cols = df.select_dtypes(include=['object']).columns
for col in obj_cols:
    df[col] = df[col].astype(str).replace('nan', np.nan)

print(f"Düzenleme Tamamlandı. Kalan Sütun Sayısı: {len(df.columns)}")

Düzenleme Tamamlandı. Kalan Sütun Sayısı: 285

In [249]:
df.info(verbose=True, show_counts=True  )

<class 'pandas.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 285 columns):
 #    Column                                                         Non-Null Count  Dtype
---   ------                                                         --------------  -----
 0    urun_linki                                                     1301 non-null   str
 1    urun_adi                                                       1301 non-null   str
 2    fiyat                                                          1176 non-null   float64
 3    enerji_sinifi                                                  270 non-null    str
 4    favori_sayisi                                                  1237 non-null   Int64
 5    Product_Group                                                  1301 non-null   str
 6    Main_Category                                                  1301 non-null   str
 7    Subcategory                                                    1301 non-null   str
 8    Derinlik                                                       1055 non-null   float64
 9    Genişlik                                                       1072 non-null   float64
 10   Yükseklik                                                      1106 non-null   float64
 11   Sıcaklık Yükselme Süresi (Saat)                                76 non-null     str
 12   Dondurucu Yeri                                                 77 non-null     str
 13   Elektronik Gösterge                                            58 non-null     str
 14   Kontrol Sistemi                                                100 non-null    str
 15   Tatil Modu                                                     1301 non-null   int64
 16   ProSmart™ Inverter Kompresör                                   1301 non-null   int64
 17   Aydınlatma Tipi                                                59 non-null     str
 18   Kapı Yönü Değiştirme                                           1301 non-null   int64
 19   İklim Sınıfı                                                   78 non-null     str
 20   Ses Seviyesi                                                   157 non-null    float64
 21   Ses Seviyesi Sınıfı                                            78 non-null     str
 22   Soğutma Sistemi                                                78 non-null     str
 23   Soğutucu Bölme Fanı                                            1301 non-null   int64
 24   EverFresh+ Teknolojisi                                         1301 non-null   int64
 25   Kahvaltılık Çekmecesi                                          1301 non-null   int64
 26   Dondurucu Çekmece Sayısı                                       54 non-null     str
 27   Buzluk Tipi                                                    66 non-null     str
 28   Dondurucu Bölme Aydınlatma Tipi                                32 non-null     str
 29   Sebzelik Adedi                                                 53 non-null     str
 30   Yıllık Enerji Tüketimi (kWh)                                   93 non-null     float64
 31   Günlük Enerji Tüketimi (kwh/Gün)                               78 non-null     float64
 32   Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP)             78 non-null     str
 33   Ürün Tipi                                                      159 non-null    str
 34   Hızlı Soğutma                                                  1301 non-null   int64
 35   Hızlı Dondurma Bölmesi                                         1301 non-null   int64
 36   Kapasite                                                       87 non-null     float64
 37   IronFast                                                       1301 non-null   int64
 38   Çocuk Kilidi                                                   1301 non-null   int64
 39   Deterjan Sistemi                                               1301 non-null   int64
 40   Buhar                                                          20 non-null     str
 41   Motor Tipi                                                     131 non-null    str
 42   Tambur Deseni                                                  34 non-null     str
 43   Elektronik Su Kontrol Sistemi                                  1301 non-null   int64
 44   Gösterge Tipi                                                  23 non-null     str
 45   Kalan Zaman Göstergesi                                         1301 non-null   int64
 46   Su Taşma Emniyet Sistemi                                       1301 non-null   int64
 47   Dengesiz Yük Kontrolü                                          1301 non-null   int64
 48   Su Kesik İkazı                                                 1301 non-null   int64
 49   Programlar                                                     114 non-null    str
 50   Dinamik Rezistans                                              1301 non-null   int64
 51   Bağlantı                                                       39 non-null     str
 52   Fonksiyonlar                                                   164 non-null    str
 53   Ekran Tipi                                                     227 non-null    str
 54   Paslanmaz Çelik İç Gövde                                       1301 non-null   int64
 55   Otomatik Kapı Açma Özelliği                                    1301 non-null   int64
 56   Bardak Koruma Sistemi                                          1301 non-null   int64
 57   Yarım Yük Yıkama                                               1301 non-null   int64
 58   Yüksekliği Ayarlanabilir Fincan Rafları                        1301 non-null   int64
 59   Fincan Raf Sayısı                                              33 non-null     str
 60   Çatal Kaşık Sepeti                                             33 non-null     str
 61   Enerji Tüketimi                                                33 non-null     str
 62   Su Tüketimi                                                    52 non-null     float64
 63   Parlatıcı Göstergesi                                           1301 non-null   int64
 64   Tuz Göstergesi                                                 1301 non-null   int64
 65   Su Güvenlik Sistemi                                            33 non-null     str
 66   Kir Sensörü                                                    1301 non-null   int64
 67   Dokunmatik Tuş                                                 1301 non-null   int64
 68   Direkt Su Tahliyesi                                            1301 non-null   int64
 69   Su Tankı Dolu Uyarısı                                          1301 non-null   int64
 70   Kondenser Temizleme Uyarısı                                    1301 non-null   int64
 71   Fıltre Temizleme Uyarısı                                       1301 non-null   int64
 72   Ürün Serisi                                                    48 non-null     str
 73   Fırın Hacmi                                                    35 non-null     float64
 74   Fırın İçi Aydınlatma                                           1301 non-null   int64
 75   Elektrikli Izgara                                              1301 non-null   int64
 76   Ön Kapak Cam Sayısı                                            35 non-null     str
 77   Elektroturbo (Fan Destekli Pişirme)                            1301 non-null   int64
 78   Saat Tipi                                                      27 non-null     str
 79   Fan ve Alt Isıtıcı                                             1301 non-null   int64
 80   Alt Isıtıcı                                                    1301 non-null   int64
 81   Fan Destekli Isıtıcı                                           1301 non-null   int64
 82   Küçük Izgara                                                   1301 non-null   int64
 83   Kolayca Sökülebilir ve Temizlenebilir Komple İç Cam            1301 non-null   int64
 84   Buharlı Pişirme                                                32 non-null     str
 85   Doğalgaz                                                       1301 non-null   int64
 86   Ocak Yüzeyi                                                    58 non-null     str
 87   Kahve Beki Adaptörü                                            30 non-null     str
 88   Gaz Emniyet Sistemi                                            1301 non-null   int64
 89   3D Pişirme                                                     1301 non-null   int64
 90   FitFry Teknolojisi                                             1301 non-null   int64
 91   Ekran Kilidi                                                   1301 non-null   int64
 92   Ocak Tipi Ve Göz Sayısı                                        52 non-null     str
 93   Ocak Tipi                                                      52 non-null     str
 94   Bek Şapkası Tipi                                               43 non-null     str
 95   Kontrol Tipi ve Yeri                                           52 non-null     str
 96   Sol Ön Bölme                                                   48 non-null     str
 97   Sağ Arka Bölme                                                 49 non-null     str
 98   Tencere Izgara Tipi                                            35 non-null     str
 99   Çerçeve                                                        25 non-null     str
 100  Sağ Ön Bölme                                                   49 non-null     str
 101  Sol Arka Bölme                                                 48 non-null     str
 102  Zamanlayıcı                                                    24 non-null     float64
 103  Sıcaklık Ayarı                                                 22 non-null     str
 104  Bulaşık Makinesinde Yıkanabilir Aksesuarlar                    1301 non-null   int64
 105  LCD Ekran                                                      1301 non-null   int64
 106  Aşırı Isınma Emniyeti                                          1301 non-null   int64
 107  Minimum Ses Seviyesi                                           46 non-null     str
 108  Davlumbaz Tipi                                                 33 non-null     str
 109  Maksimum Çekiş Gücü                                            46 non-null     str
 110  Yağ Filtre Adedi                                               46 non-null     str
 111  Montaj Yüksekliği (mm)                                         35 non-null     str
 112  Bulaşık Makinesinde Yıkanabilir Filtre                         1301 non-null   int64
 113  Kontrol Tipi                                                   58 non-null     str
 114  Lamba Adedi                                                    46 non-null     str
 115  Yoğun Emiş Gücü                                                1301 non-null   int64
 116  Otomatik Kapanma Özelliği                                      1301 non-null   int64
 117  Kademe Sayısı                                                  46 non-null     str
 118  Filtre Tipi                                                    41 non-null     str
 119  Filtre Doluluk Göstergesi                                      1301 non-null   int64
 120  Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre)  40 non-null     str
 121  Hava Temizleme Özelliği                                        1301 non-null   int64
 122  Önden Ayarlanablir Arka Ayaklar                                1301 non-null   int64
 123  Yüksek Bazaya Montaj                                           1301 non-null   int64
 124  Ekran Boyutu                                                   215 non-null    str
 125  İşletim Sistemi                                                207 non-null    str
 126  USB Bağlantısı                                                 1301 non-null   int64
 127  HDMI                                                           1301 non-null   int64
 128  Bluetooth                                                      279 non-null    str
 129  Arka Kamera                                                    116 non-null    str
 130  Ön Kamera                                                      188 non-null    str
 131  İşlemci                                                        151 non-null    str
 132  Ekran Çözünürlüğü                                              137 non-null    str
 133  Mikrofon                                                       99 non-null     float64
 134  GPS                                                            1301 non-null   int64
 135  Kulaklık Tipi                                                  80 non-null     str
 136  NFC                                                            1301 non-null   int64
 137  Aux Girişi                                                     1301 non-null   int64
 138  Uzaktan Kumanda                                                1301 non-null   int64
 139  İşlemci Çekirdek Sayısı                                        141 non-null    str
 140  2.Arka Kamera                                                  1301 non-null   int64
 141  Kamera Zoom                                                    135 non-null    str
 142  Ön Kamera Flaş                                                 1301 non-null   int64
 143  Wi-Fi                                                          1301 non-null   int64
 144  Marka                                                          175 non-null    str
 145  Yüz Haritalama                                                 1301 non-null   int64
 146  Çift Hatlı                                                     1301 non-null   int64
 147  Ses Kayıt                                                      1301 non-null   int64
 148  Ürün Ailesi                                                    66 non-null     str
 149  İşletim Sistemi Versionu                                       72 non-null     str
 150  Görüntülü Konuşma                                              1301 non-null   int64
 151  Uyumlu olduğu modeller (MPA)                                   21 non-null     str
 152  Hızlı Şarj desteği                                             1301 non-null   int64
 153  Type¬C veya Micro USB kablolarıyla şarj edilebilir             1301 non-null   int64
 154  Su Geçirmezlik                                                 55 non-null     str
 155  Soğutma Kapasitesi                                             26 non-null     str
 156  Isıtma Kapasitesi (Btu/h)                                      24 non-null     str
 157  Yıllık Tüketim (kW) Soğuma                                     25 non-null     str
 158  Yıllık Tüketim Isıtma (kW)                                     24 non-null     str
 159  Voltaj                                                         74 non-null     str
 160  Soğutucu Akışkan                                               26 non-null     str
 161  Mevsimsel (SCOP) Enerji Verimi Isıtma (W/W)                    24 non-null     str
 162  Mevsimsel (SEER) Enerji Verimi Soğutma (W/W)                   25 non-null     str
 163  Akıllı Çalışma Sistemi                                         1301 non-null   int64
 164  Gizli Gösterge                                                 26 non-null     str
 165  Uyku Mode                                                      1301 non-null   int64
 166  Dış Ünite Soğutma Çalışma Aralığı(°C)                          25 non-null     str
 167  Dış Ünite Isıtma Çalışma Aralığı(°C)                           24 non-null     str
 168  Özel Filtreler                                                 23 non-null     str
 169  Otomatik Temizleme                                             1301 non-null   int64
 170  Otomatik Hava Yönlendirme (Yukarı-Aşağı)                       1301 non-null   int64
 171  4 Yönlü Otomatik Hava Kontrolü                                 1301 non-null   int64
 172  Nem Alma                                                       1301 non-null   int64
 173  Enerji Sınıfı-Isıtma                                           22 non-null     str
 174  Kapasite (Isıtma)                                              20 non-null     str
 175  Anlık Tüketim Göstergesi                                       1301 non-null   int64
 176  Enerji Kontrol                                                 1301 non-null   int64
 177  Sessiz Mod                                                     1301 non-null   int64
 178  Yumuşak Hava                                                   1301 non-null   int64
 179  Auto Swing                                                     1301 non-null   int64
 180  Dış Ünite (GxYxD) mm                                           21 non-null     str
 181  İç Ünite (GxYxD) mm                                            21 non-null     str
 182  Su Tankı Kapasitesi                                            35 non-null     float64
 183  Devrilme Emniyeti                                              1301 non-null   int64
 184  Titanyum Emaye Kaplamalı Kazan                                 1301 non-null   int64
 185  Yüksek Basınç Emniyet Valfi                                    1301 non-null   int64
 186  Susuz Çalışma Emniyeti                                         1301 non-null   int64
 187  Donma Emniyeti                                                 1301 non-null   int64
 188  Korozyona Karşı Koruma                                         1301 non-null   int64
 189  Yerden Isıtmaya Uygunluk                                       1301 non-null   int64
 190  Oda Termostatı İle Çalışma                                     1301 non-null   int64
 191  Alev Modülasyonu                                               1301 non-null   int64
 192  Fan Modülasyonu                                                1301 non-null   int64
 193  Arıza Teşhis Sistemi                                           1301 non-null   int64
 194  Emniyet Termostatı                                             1301 non-null   int64
 195  Emniyet Ventili                                                1301 non-null   int64
 196  Hava Emiş Emniyeti                                             1301 non-null   int64
 197  Alev Sönme Emniyeti                                            1301 non-null   int64
 198  3 Yollu Vana Blokaj Sistemi                                    1301 non-null   int64
 199  Otomatik By-Pass Sistemi                                       1301 non-null   int64
 200  Pompa Anti Blokaj Sistemi                                      1301 non-null   int64
 201  Fincan Kapasitesi                                              20 non-null     str
 202  Işıklı Uyarı                                                   1301 non-null   int64
 203  Ölçü Kaşığı                                                    1301 non-null   int64
 204  Sesli Uyarı                                                    1301 non-null   int64
 205  Cook Sense Teknolojisi (Pişmeyi Algılama)                      1301 non-null   int64
 206  Anti Spill Teknolojisi (Taşmayı Önleme)                        1301 non-null   int64
 207  Tek Tuşla Kontrol                                              1301 non-null   int64
 208  Fincan Boyutu Seçimi                                           1301 non-null   int64
 209  Su Seviye Göstergesi                                           1301 non-null   int64
 210  Otomatik Kapanma                                               42 non-null     str
 211  Sıcak Tutma Özelliği                                           1301 non-null   int64
 212  Kablo Sarma Yuvası                                             1301 non-null   int64
 213  Pompa Basıncı                                                  21 non-null     str
 214  Çıkarılabilir Su tankı                                         1301 non-null   int64
 215  Motor Gücü                                                   36 non-null     str
 216  İkili Isıtma Sistemi                                           1301 non-null   int64
 217  360° Dönebilen Kablosuz Kullanım                               1301 non-null   int64

In [252]:


# --- 1. GÜÇ VE PERFORMANS HAVUZU ---
# Kaçak güç sütunlarını ana Guc (W) sütununa aktarıyoruz
guc_ek_sutunlar = ['Güç', 'Toplam Elektrik Gücü (kW)', 'Motor Gücü', 'Isıtma Gücü', 'Güç (W)']

for col in guc_ek_sutunlar:
    if col in df.columns:
        # ultra_temizleyici fonksiyonunu (önceki adımda tanımladığımız) kullanıyoruz
        cleaned_val = df[col].apply(ultra_temizleyici)
        df['Guc (W)'] = df['Guc (W)'].combine_first(cleaned_val)

# --- 2. SES SEVİYESİ BİRLEŞTİRME ---
if 'Minimum Ses Seviyesi' in df.columns:
    cleaned_min_ses = df['Minimum Ses Seviyesi'].apply(ultra_temizleyici)
    df['Ses Seviyesi'] = df['Ses Seviyesi'].combine_first(cleaned_min_ses)

# --- 3. TEKNİK ÖZELLİKLERİ SAYISALLAŞTIRMA (STR -> FLOAT) ---
# Hala str duran ama sayısal olanları zorla dönüştürüyoruz
zorunlu_sayisallar = [
    'Yıllık Enerji Tüketimi (kWh)', 'Günlük Enerji Tüketimi (kwh/Gün)', 
    'Su Tüketimi', 'Fincan Kapasitesi', 'Toz Torbası Kapasitesi'
]

for col in zorunlu_sayisallar:
    if col in df.columns:
        df[col] = df[col].apply(ultra_temizleyici)

# --- 4. SEYREK SÜTUNLARI BUDAMA (%1.5 ALTINDAKİLER) ---
limit = 20
seyrek_sutunlar = [col for col in df.columns if df[col].count() < limit]
# Kritik kategori ve hedef sütunlarını koru
korunacaklar = ['urun_linki', 'urun_adi', 'fiyat', 'Main_Category', 'Subcategory', 'Product_Group']
seyrek_sutunlar = [c for c in seyrek_sutunlar if c not in korunacaklar]

df.drop(columns=seyrek_sutunlar, inplace=True)

# --- 5. GEREKSİZLEŞEN ARA SÜTUNLARI SİLME ---
df.drop(columns=[c for c in guc_ek_sutunlar if c in df.columns], errors='ignore', inplace=True)
if 'Minimum Ses Seviyesi' in df.columns: df.drop(columns=['Minimum Ses Seviyesi'], inplace=True)

# --- 6. KATEGORİK SÜTUNLARI STANDARTLAŞTIRMA ---
# Kalan metin sütunlarını temiz str tipine çeviriyoruz
obj_cols = df.select_dtypes(include=['object']).columns
for col in obj_cols:
    df[col] = df[col].astype(str).replace('nan', np.nan).str.strip()

print(f"Optimizasyon Tamamlandı! Yeni Sütun Sayısı: {len(df.columns)}")

Optimizasyon Tamamlandı! Yeni Sütun Sayısı: 284

In [253]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

df.sample(10, random_state=42)

,urun_linki,urun_adi,fiyat,enerji_sinifi,favori_sayisi,Product_Group,Main_Category,Subcategory,Derinlik,Genişlik,Yükseklik,Sıcaklık Yükselme Süresi (Saat),Dondurucu Yeri,Elektronik Gösterge,Kontrol Sistemi,Tatil Modu,ProSmart™ Inverter Kompresör,Aydınlatma Tipi,Kapı Yönü Değiştirme,İklim Sınıfı,Ses Seviyesi,Ses Seviyesi Sınıfı,Soğutma Sistemi,Soğutucu Bölme Fanı,EverFresh+ Teknolojisi,Kahvaltılık Çekmecesi,Dondurucu Çekmece Sayısı,Buzluk Tipi,Dondurucu Bölme Aydınlatma Tipi,Sebzelik Adedi,Yıllık Enerji Tüketimi (kWh),Günlük Enerji Tüketimi (kwh/Gün),Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP),Ürün Tipi,Hızlı Soğutma,Hızlı Dondurma Bölmesi,Kapasite,IronFast,Çocuk Kilidi,Deterjan Sistemi,Buhar,Motor Tipi,Tambur Deseni,Elektronik Su Kontrol Sistemi,Gösterge Tipi,Kalan Zaman Göstergesi,Su Taşma Emniyet Sistemi,Dengesiz Yük Kontrolü,Su Kesik İkazı,Programlar,Dinamik Rezistans,Bağlantı,Fonksiyonlar,Ekran Tipi,Paslanmaz Çelik İç Gövde,Otomatik Kapı Açma Özelliği,Bardak Koruma Sistemi,Yarım Yük Yıkama,Yüksekliği Ayarlanabilir Fincan Rafları,Fincan Raf Sayısı,Çatal Kaşık Sepeti,Enerji Tüketimi,Su Tüketimi,Parlatıcı Göstergesi,Tuz Göstergesi,Su Güvenlik Sistemi,Kir Sensörü,Dokunmatik Tuş,Direkt Su Tahliyesi,Su Tankı Dolu Uyarısı,Kondenser Temizleme Uyarısı,Fıltre Temizleme Uyarısı,Ürün Serisi,Fırın Hacmi,Fırın İçi Aydınlatma,Elektrikli Izgara,Ön Kapak Cam Sayısı,Elektroturbo (Fan Destekli Pişirme),Saat Tipi,Fan ve Alt Isıtıcı,Alt Isıtıcı,Fan Destekli Isıtıcı,Küçük Izgara,Kolayca Sökülebilir ve Temizlenebilir Komple İç Cam,Buharlı Pişirme,Doğalgaz,Ocak Yüzeyi,Kahve Beki Adaptörü,Gaz Emniyet Sistemi,3D Pişirme,FitFry Teknolojisi,Ekran Kilidi,Ocak Tipi Ve Göz Sayısı,Ocak Tipi,Bek Şapkası Tipi,Kontrol Tipi ve Yeri,Sol Ön Bölme,Sağ Arka Bölme,Tencere Izgara Tipi,Çerçeve,Sağ Ön Bölme,Sol Arka Bölme,Zamanlayıcı,Sıcaklık Ayarı,Bulaşık Makinesinde Yıkanabilir Aksesuarlar,LCD Ekran,Aşırı Isınma Emniyeti,Davlumbaz Tipi,Maksimum Çekiş Gücü,Yağ Filtre Adedi,Montaj Yüksekliği (mm),Bulaşık Makinesinde Yıkanabilir Filtre,Kontrol Tipi,Lamba Adedi,Yoğun Emiş Gücü,Otomatik Kapanma Özelliği,Kademe Sayısı,Filtre Tipi,Filtre Doluluk Göstergesi,Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre),Hava Temizleme Özelliği,Önden Ayarlanablir Arka Ayaklar,Yüksek Bazaya Montaj,Ekran Boyutu,İşletim Sistemi,USB Bağlantısı,HDMI,Bluetooth,Arka Kamera,Ön Kamera,İşlemci,Ekran Çözünürlüğü,Mikrofon,GPS,Kulaklık Tipi,NFC,Aux Girişi,Uzaktan Kumanda,İşlemci Çekirdek Sayısı,2.Arka Kamera,Kamera Zoom,Ön Kamera Flaş,Wi-Fi,Marka,Yüz Haritalama,Çift Hatlı,Ses Kayıt,Ürün Ailesi,İşletim Sistemi Versionu,Görüntülü Konuşma,Uyumlu olduğu modeller (MPA),Hızlı Şarj desteği,Type¬C veya Micro USB kablolarıyla şarj edilebilir,Su Geçirmezlik,Soğutma Kapasitesi,Isıtma Kapasitesi (Btu/h),Yıllık Tüketim (kW) Soğuma,Yıllık Tüketim Isıtma (kW),Voltaj,Soğutucu Akışkan,Mevsimsel (SCOP) Enerji Verimi Isıtma (W/W),Mevsimsel (SEER) Enerji Verimi Soğutma (W/W),Akıllı Çalışma Sistemi,Gizli Gösterge,Uyku Mode,Dış Ünite Soğutma Çalışma Aralığı(°C),Dış Ünite Isıtma Çalışma Aralığı(°C),Özel Filtreler,Otomatik Temizleme,Otomatik Hava Yönlendirme (Yukarı-Aşağı),4 Yönlü Otomatik Hava Kontrolü,Nem Alma,Enerji Sınıfı-Isıtma,Kapasite (Isıtma),Anlık Tüketim Göstergesi,Enerji Kontrol,Sessiz Mod,Yumuşak Hava,Auto Swing,Dış Ünite (GxYxD) mm,İç Ünite (GxYxD) mm,Su Tankı Kapasitesi,Devrilme Emniyeti,Titanyum Emaye Kaplamalı Kazan,Yüksek Basınç Emniyet Valfi,Susuz Çalışma Emniyeti,Donma Emniyeti,Korozyona Karşı Koruma,Yerden Isıtmaya Uygunluk,Oda Termostatı İle Çalışma,Alev Modülasyonu,Fan Modülasyonu,Arıza Teşhis Sistemi,Emniyet Termostatı,Emniyet Ventili,Hava Emiş Emniyeti,Alev Sönme Emniyeti,3 Yollu Vana Blokaj Sistemi,Otomatik By-Pass Sistemi,Pompa Anti Blokaj Sistemi,Fincan Kapasitesi,Işıklı Uyarı,Ölçü Kaşığı,Sesli Uyarı,Cook Sense Teknolojisi (Pişmeyi Algılama),Anti Spill Teknolojisi (Taşmayı Önleme),Tek Tuşla Kontrol,Fincan Boyutu Seçimi,Su Seviye Göstergesi,Otomatik Kapanma,Sıcak Tutma Özelliği,Kablo Sarma Yuvası,Pompa Basıncı,Çıkarılabilir Su tankı,Motor Gücü,İkili Isıtma Sistemi,360° Dönebilen Kablosuz Kullanım,Işıklı Açma/Kapama Düğmesi,Kablo Uzunluğu,Çıkarılabilir Plakalar,Kilitleme Mandalı,Yağ Toplama Haznesi,Açma/Kapama Düğmesi,Sıcaklık Kontrolü,Çalışma Göstergesi,Maksimum Sıcaklık Derecesi,Minimum Sıcaklık Derecesi (°C),Iyon Özelliği,Saçları Pürüzsüz ve Kıvırcık Yapma,Ürün Kilidi,Sıcaklık Ayarı Kilidi,LED Ekran,Hız Ayarı,Difüzör Başlığı,Çıkarılabilir hava giriş ızgarası,Cool Shot,Fön Başlığı,Soğuk Ayarı,Seramik Izgara,Asma Halkası,Vigo Difüzör Başlık,Toz Torbası Kapasitesi,360° Derece Dönebilen Hortum,Taşıma sapı,Kullanım tipi,Döşeme/Koltuk Fırçası,Dar Ağızlı Uç,Duvara Monte Edilebilen Şarj aleti,Turbo Fırça,Paspas Özelliği,Şarj istasyonu,Led Fırça,Yüksek Performanslı Elektrikli Fırça,Buharsız Ütüleme,Şok Buhar Özelliği,Dikey Ütüleme,Turbo Özelliği,Doğrayıcı,Paslanmaz Çelik Çırpıcı,Paslanmaz Çelik Blender,Paslanmaz Çelik Bıçak,Doğrayıcı Kabı,Ölçü Kabı,Güvenlik Kilidi,Renk_Siyah,Renk_Gri,Renk_Mavi,Renk_Pembe,Renk_Beyaz,Renk_Kırmızı,Renk_Sarı,Renk_Yeşil,Renk_Turuncu,Renk_Bej,Renk_Mor,Renk_Kahverengi,Agirlik (kg),Sarj_Suresi_dk,Guc (W),Su_Kapasitesi (L),RAM (GB),Depolama (GB),Batarya (mAh),Sikma_Devri
478,https://www.beko.com.tr/kulaklik/samsung-typec...,Samsung TypeC Kablolu Kulaklık-Siyah Kulaklık,599.00,NaN,1,Kulaklik,Elektronik,Ses& Görüntü Sistemleri,7.00,9.00,2.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1.00,0,Kablolu Kulak İçi Kulaklık,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,https://www.beko.com.tr/cep-telefonu-aksesuarl...,UGREEN USB-C 60W Örgülü Kablo Syh 1M Cep Telef...,379.00,NaN,0,Cep Telefonu Aksesuarlari,Elektronik,Cep Telefonu,2.00,4.00,5.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,https://www.beko.com.tr/ankastre-mikrodalgalar...,BMM 2020 I Ankastre Mikrodalgalar,16420.00,NaN,22,Ankastre Mikrodalgalar,Diğer,Diğer,37.70,47.00,28.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ankastre,0,0,NaN,0,1,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,['9'],NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,1,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,15.50,NaN,1200.00,NaN,NaN,NaN,NaN,NaN
661,https://www.beko.com.tr/android-telefon-modell...,Xiaomi Redmi Note 14 Pro 12/512GB Siyah Androi...,20999.00,NaN,1,Android Telefon Modelleri,Elektronik,Cep Telefonu,17.00,6.00,5.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,AMOLED,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,6.67 in,NaN,0,0,1,NaN,32MP,NaN,1080 x 2400,NaN,1,NaN,0,0,0,8,1,NaN,0,1,Xiaomi,1,1,0,NaN,NaN,1,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,12.00,512.00,5500000.00,NaN
969,https://www.beko.com.tr/espresso-makinesi/nesp...,Nespresso Aeroccino 4 Süt Köpürtücü Espresso M...,5999.00,NaN,0,Espresso Makinesi,Küçük Ev Aletleri,Kahve Makinesi,10.00,10.00,17.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,220-240,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,https://www.beko.com.tr/4-programli-bulasik-ma...,BM 4144 OK A 4 Programlı Bulaşık Makinesi,25979.00,D,44,4 Programli Bulasik Makinesi,Beyaz Eşya,Bulaşık Makinesi,60.00,60.00,85.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,47.00,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Solo,0,0,14.00,0,1,0,NaN,Standart,NaN,0,NaN,0,0,0,0,"['Makine Yıkama', '35-50-65-70', '190 dk']",0,NaN,"['HijyenMax', 'Ekstra Parlaklık/ Kurutma Fonks...",LED,1,1,1,1,1,2,Hareketli,0.849 kWh,11.50,1,1,Taşma Emniyeti,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,43.40,NaN,2100.00,NaN,NaN,NaN,NaN,NaN
814,https://www.beko.com.tr/akilli-saat/apple-watc...,Apple Watch SE GPS 40mm Y. Işığı SB S/M Akıllı...,10999.00,NaN,0,Akilli Saat,Elektronik,Giyilebilir Teknoloji,1.00,3.00,4.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,50 metreye kadar su geçirmezlik.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1262,https://www.beko.com.tr/el-blender/hbs-5410-ka...,HBS 5410 El Blender,3349.00,NaN,13,El Blender,Küçük Ev Aletleri,Karıştırıcı& Doğrayıcı,13.00,13.00,36.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,1,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,1,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1.43,NaN,1500.00,NaN,NaN,NaN,NaN,NaN
1103,https://www.beko.com.tr/yaslanma-karsiti-bakim...,Foreo FAQ 302 Black Yaşlanma Karşıtı Bakım,25999.00,NaN,1,Yaslanma Karsiti Bakim,Diğer,Diğer,5.00,12.00,16.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,https://www.beko.com.tr/elite-serisi-solo-bula...,B 710 bc Elite Serisi Solo Bulaşık Makinesi,28079.00,B,5,Elite Serisi Solo Bulasik Makinesi,Beyaz Eşya,Bulaşık Makinesi,60.00,60.00,85.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,46.00,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Solo,0,0,14.00,0,1,0,NaN,Standart,NaN,0,NaN,0,0,0,0,"[""Hızlı 49'"", '35-40-50-65-70', 'Hassas 40', '...",0,Wi-Fi + BLE,"['HomeWhiz', 'HijyenMax (App)', 'Extra kurutma...",LED,1,1,0,1,1,2,Hareketli,0.645 kWh,10.90,1,1,Taşma Emniyeti,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,50.10,NaN,2100.00,NaN,NaN,NaN,NaN,NaN

In [254]:

# 1. ADIM: LİSTELERDEN "ADET/SAYI" ÇIKARMA
def liste_sayisi_al(val):
    if pd.isna(val) or val == "" or val == "nan": return 0
    # Eğer veri bir liste görünümündeyse (örn: "['a', 'b']")
    if "[" in str(val):
        try:
            # Virgülleri sayarak eleman sayısını tahmin et (+1)
            return str(val).count(',') + 1
        except: return 1
    return 1 if val != 0 else 0

# Program ve Fonksiyon sayılarını yeni sütun yapalım
df['Program_Sayisi'] = df['Programlar'].apply(liste_sayisi_al)
df['Fonksiyon_Sayisi'] = df['Fonksiyonlar'].apply(liste_sayisi_al)

# 2. ADIM: ADET BELİRTEN STR SÜTUNLARI SAYIYA ÇEVİRME
adet_sutunlari = [
    'Dondurucu Çekmece Sayısı', 'Sebzelik Adedi', 'Fincan Raf Sayısı', 
    'Ön Kapak Cam Sayısı', 'Lamba Adedi', 'İşlemci Çekirdek Sayısı'
]

for col in adet_sutunlari:
    if col in df.columns:
        # Metin içindeki sayıları çek (Örn: "2 Adet" -> 2)
        df[col] = pd.to_numeric(df[col].astype(str).str.extract(r'(\d+)')[0], errors='coerce')

# 3. ADIM: EKRAN BOYUTU (INCH -> FLOAT)
if 'Ekran Boyutu' in df.columns:
    # "6.67 in" -> 6.67
    df['Ekran_Boyutu_Inch'] = df['Ekran Boyutu'].astype(str).str.replace(',', '.').str.extract(r'(\d+\.?\d*)')[0].astype(float)
    df.drop(columns=['Ekran Boyutu'], inplace=True)

# 4. ADIM: ÇOK SEYREK SÜTUNLARI SİLME (GÜLTÜ AZALTMA)
# 1301 satırda 20'den az veri varsa o özellik model için genelleme yapamaz.
limit = 20
seyrek_cols = [col for col in df.columns if df[col].count() < limit]
# Önemli olabilecekleri koruyalım
korunacaklar = ['urun_adi', 'fiyat', 'Main_Category', 'Subcategory', 'Guc (W)', 'Agirlik (kg)']
seyrek_cols = [c for c in seyrek_cols if c not in korunacaklar]

df.drop(columns=seyrek_cols, inplace=True)

# 5. ADIM: FİNAL VERİ TİPİ DÜZENLEME
# Bellek tasarrufu için 1/0 olanları int8 yapabilirsin
binary_cols = df.columns[df.isin([0, 1]).all()]
for col in binary_cols:
    df[col] = df[col].astype(np.int8)

print(f"Final Optimizasyon Tamamlandı! Yeni Sütun Sayısı: {len(df.columns)}")

Final Optimizasyon Tamamlandı! Yeni Sütun Sayısı: 286

In [255]:
df.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 286 columns):
 #    Column                                                         Non-Null Count  Dtype
---   ------                                                         --------------  -----
 0    urun_linki                                                     1301 non-null   str
 1    urun_adi                                                       1301 non-null   str
 2    fiyat                                                          1176 non-null   float64
 3    enerji_sinifi                                                  270 non-null    str
 4    favori_sayisi                                                  1237 non-null   Int64
 5    Product_Group                                                  1301 non-null   str
 6    Main_Category                                                  1301 non-null   str
 7    Subcategory                                                    1301 non-null   str
 8    Derinlik                                                       1055 non-null   float64
 9    Genişlik                                                       1072 non-null   float64
 10   Yükseklik                                                      1106 non-null   float64
 11   Sıcaklık Yükselme Süresi (Saat)                                76 non-null     str
 12   Dondurucu Yeri                                                 77 non-null     str
 13   Elektronik Gösterge                                            58 non-null     str
 14   Kontrol Sistemi                                                100 non-null    str
 15   Tatil Modu                                                     1301 non-null   int8
 16   ProSmart™ Inverter Kompresör                                   1301 non-null   int8
 17   Aydınlatma Tipi                                                59 non-null     str
 18   Kapı Yönü Değiştirme                                           1301 non-null   int8
 19   İklim Sınıfı                                                   78 non-null     str
 20   Ses Seviyesi                                                   203 non-null    float64
 21   Ses Seviyesi Sınıfı                                            78 non-null     str
 22   Soğutma Sistemi                                                78 non-null     str
 23   Soğutucu Bölme Fanı                                            1301 non-null   int8
 24   EverFresh+ Teknolojisi                                         1301 non-null   int8
 25   Kahvaltılık Çekmecesi                                          1301 non-null   int8
 26   Dondurucu Çekmece Sayısı                                       54 non-null     float64
 27   Buzluk Tipi                                                    66 non-null     str
 28   Dondurucu Bölme Aydınlatma Tipi                                32 non-null     str
 29   Sebzelik Adedi                                                 53 non-null     float64
 30   Yıllık Enerji Tüketimi (kWh)                                   93 non-null     float64
 31   Günlük Enerji Tüketimi (kwh/Gün)                               78 non-null     float64
 32   Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP)             78 non-null     str
 33   Ürün Tipi                                                      159 non-null    str
 34   Hızlı Soğutma                                                  1301 non-null   int8
 35   Hızlı Dondurma Bölmesi                                         1301 non-null   int8
 36   Kapasite                                                       87 non-null     float64
 37   IronFast                                                       1301 non-null   int8
 38   Çocuk Kilidi                                                   1301 non-null   int8
 39   Deterjan Sistemi                                               1301 non-null   int8
 40   Buhar                                                          20 non-null     str
 41   Motor Tipi                                                     131 non-null    str
 42   Tambur Deseni                                                  34 non-null     str
 43   Elektronik Su Kontrol Sistemi                                  1301 non-null   int8
 44   Gösterge Tipi                                                  23 non-null     str
 45   Kalan Zaman Göstergesi                                         1301 non-null   int8
 46   Su Taşma Emniyet Sistemi                                       1301 non-null   int8
 47   Dengesiz Yük Kontrolü                                          1301 non-null   int8
 48   Su Kesik İkazı                                                 1301 non-null   int8
 49   Programlar                                                     114 non-null    str
 50   Dinamik Rezistans                                              1301 non-null   int8
 51   Bağlantı                                                       39 non-null     str
 52   Fonksiyonlar                                                   164 non-null    str
 53   Ekran Tipi                                                     227 non-null    str
 54   Paslanmaz Çelik İç Gövde                                       1301 non-null   int8
 55   Otomatik Kapı Açma Özelliği                                    1301 non-null   int8
 56   Bardak Koruma Sistemi                                          1301 non-null   int8
 57   Yarım Yük Yıkama                                               1301 non-null   int8
 58   Yüksekliği Ayarlanabilir Fincan Rafları                        1301 non-null   int8
 59   Fincan Raf Sayısı                                              33 non-null     float64
 60   Çatal Kaşık Sepeti                                             33 non-null     str
 61   Enerji Tüketimi                                                33 non-null     str
 62   Su Tüketimi                                                    52 non-null     float64
 63   Parlatıcı Göstergesi                                           1301 non-null   int8
 64   Tuz Göstergesi                                                 1301 non-null   int8
 65   Su Güvenlik Sistemi                                            33 non-null     str
 66   Kir Sensörü                                                    1301 non-null   int8
 67   Dokunmatik Tuş                                                 1301 non-null   int8
 68   Direkt Su Tahliyesi                                            1301 non-null   int8
 69   Su Tankı Dolu Uyarısı                                          1301 non-null   int8
 70   Kondenser Temizleme Uyarısı                                    1301 non-null   int8
 71   Fıltre Temizleme Uyarısı                                       1301 non-null   int8
 72   Ürün Serisi                                                    48 non-null     str
 73   Fırın Hacmi                                                    35 non-null     float64
 74   Fırın İçi Aydınlatma                                           1301 non-null   int8
 75   Elektrikli Izgara                                              1301 non-null   int8
 76   Ön Kapak Cam Sayısı                                            35 non-null     float64
 77   Elektroturbo (Fan Destekli Pişirme)                            1301 non-null   int8
 78   Saat Tipi                                                      27 non-null     str
 79   Fan ve Alt Isıtıcı                                             1301 non-null   int8
 80   Alt Isıtıcı                                                    1301 non-null   int8
 81   Fan Destekli Isıtıcı                                           1301 non-null   int8
 82   Küçük Izgara                                                   1301 non-null   int8
 83   Kolayca Sökülebilir ve Temizlenebilir Komple İç Cam            1301 non-null   int8
 84   Buharlı Pişirme                                                32 non-null     str
 85   Doğalgaz                                                       1301 non-null   int8
 86   Ocak Yüzeyi                                                    58 non-null     str
 87   Kahve Beki Adaptörü                                            30 non-null     str
 88   Gaz Emniyet Sistemi                                            1301 non-null   int8
 89   3D Pişirme                                                     1301 non-null   int8
 90   FitFry Teknolojisi                                             1301 non-null   int8
 91   Ekran Kilidi                                                   1301 non-null   int8
 92   Ocak Tipi Ve Göz Sayısı                                        52 non-null     str
 93   Ocak Tipi                                                      52 non-null     str
 94   Bek Şapkası Tipi                                               43 non-null     str
 95   Kontrol Tipi ve Yeri                                           52 non-null     str
 96   Sol Ön Bölme                                                   48 non-null     str
 97   Sağ Arka Bölme                                                 49 non-null     str
 98   Tencere Izgara Tipi                                            35 non-null     str
 99   Çerçeve                                                        25 non-null     str
 100  Sağ Ön Bölme                                                   49 non-null     str
 101  Sol Arka Bölme                                                 48 non-null     str
 102  Zamanlayıcı                                                    24 non-null     float64
 103  Sıcaklık Ayarı                                                 22 non-null     str
 104  Bulaşık Makinesinde Yıkanabilir Aksesuarlar                    1301 non-null   int8
 105  LCD Ekran                                                      1301 non-null   int8
 106  Aşırı Isınma Emniyeti                                          1301 non-null   int8
 107  Davlumbaz Tipi                                                 33 non-null     str
 108  Maksimum Çekiş Gücü                                            46 non-null     str
 109  Yağ Filtre Adedi                                               46 non-null     str
 110  Montaj Yüksekliği (mm)                                         35 non-null     str
 111  Bulaşık Makinesinde Yıkanabilir Filtre                         1301 non-null   int8
 112  Kontrol Tipi                                                   58 non-null     str
 113  Lamba Adedi                                                    46 non-null     float64
 114  Yoğun Emiş Gücü                                                1301 non-null   int8
 115  Otomatik Kapanma Özelliği                                      1301 non-null   int8
 116  Kademe Sayısı                                                  46 non-null     str
 117  Filtre Tipi                                                    41 non-null     str
 118  Filtre Doluluk Göstergesi                                      1301 non-null   int8
 119  Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre)  40 non-null     str
 120  Hava Temizleme Özelliği                                        1301 non-null   int8
 121  Önden Ayarlanablir Arka Ayaklar                                1301 non-null   int8
 122  Yüksek Bazaya Montaj                                           1301 non-null   int8
 123  İşletim Sistemi                                                207 non-null    str
 124  USB Bağlantısı                                                 1301 non-null   int8
 125  HDMI                                                           1301 non-null   int8
 126  Bluetooth                                                      279 non-null    str
 127  Arka Kamera                                                    116 non-null    str
 128  Ön Kamera                                                      188 non-null    str
 129  İşlemci                                                        151 non-null    str
 130  Ekran Çözünürlüğü                                              137 non-null    str
 131  Mikrofon                                                       99 non-null     float64
 132  GPS                                                            1301 non-null   int8
 133  Kulaklık Tipi                                                  80 non-null     str
 134  NFC                                                            1301 non-null   int8
 135  Aux Girişi                                                     1301 non-null   int8
 136  Uzaktan Kumanda                                                1301 non-null   int8
 137  İşlemci Çekirdek Sayısı                                        141 non-null    float64
 138  2.Arka Kamera                                                  1301 non-null   int8
 139  Kamera Zoom                                                    135 non-null    str
 140  Ön Kamera Flaş                                                 1301 non-null   int8
 141  Wi-Fi                                                          1301 non-null   int8
 142  Marka                                                          175 non-null    str
 143  Yüz Haritalama                                                 1301 non-null   int8
 144  Çift Hatlı                                                     1301 non-null   int8
 145  Ses Kayıt                                                      1301 non-null   int8
 146  Ürün Ailesi                                                    66 non-null     str
 147  İşletim Sistemi Versionu                                       72 non-null     str
 148  Görüntülü Konuşma                                              1301 non-null   int8
 149  Uyumlu olduğu modeller (MPA)                                   21 non-null     str
 150  Hızlı Şarj desteği                                             1301 non-null   int8
 151  Type¬C veya Micro USB kablolarıyla şarj edilebilir             1301 non-null   int8
 152  Su Geçirmezlik                                                 55 non-null     str
 153  Soğutma Kapasitesi                                             26 non-null     str
 154  Isıtma Kapasitesi (Btu/h)                                      24 non-null     str
 155  Yıllık Tüketim (kW) Soğuma                                     25 non-null     str
 156  Yıllık Tüketim Isıtma (kW)                                     24 non-null     str
 157  Voltaj                                                         74 non-null     str
 158  Soğutucu Akışkan                                               26 non-null     str
 159  Mevsimsel (SCOP) Enerji Verimi Isıtma (W/W)                    24 non-null     str
 160  Mevsimsel (SEER) Enerji Verimi Soğutma (W/W)                   25 non-null     str
 161  Akıllı Çalışma Sistemi                                         1301 non-null   int8
 162  Gizli Gösterge                                                 26 non-null     str
 163  Uyku Mode                                                      1301 non-null   int8
 164  Dış Ünite Soğutma Çalışma Aralığı(°C)                          25 non-null     str
 165  Dış Ünite Isıtma Çalışma Aralığı(°C)                           24 non-null     str
 166  Özel Filtreler                                                 23 non-null     str
 167  Otomatik Temizleme                                             1301 non-null   int8
 168  Otomatik Hava Yönlendirme (Yukarı-Aşağı)                       1301 non-null   int8
 169  4 Yönlü Otomatik Hava Kontrolü                                 1301 non-null   int8
 170  Nem Alma                                                       1301 non-null   int8
 171  Enerji Sınıfı-Isıtma                                           22 non-null     str
 172  Kapasite (Isıtma)                                              20 non-null     str
 173  Anlık Tüketim Göstergesi                                       1301 non-null   int8
 174  Enerji Kontrol                                                 1301 non-null   int8
 175  Sessiz Mod                                                     1301 non-null   int8
 176  Yumuşak Hava                                                   1301 non-null   int8
 177  Auto Swing                                                     1301 non-null   int8
 178  Dış Ünite (GxYxD) mm                                           21 non-null     str
 179  İç Ünite (GxYxD) mm                                            21 non-null     str
 180  Su Tankı Kapasitesi                                            35 non-null     float64
 181  Devrilme Emniyeti                                              1301 non-null   int8
 182  Titanyum Emaye Kaplamalı Kazan                                 1301 non-null   int8
 183  Yüksek Basınç Emniyet Valfi                                    1301 non-null   int8
 184  Susuz Çalışma Emniyeti                                         1301 non-null   int8
 185  Donma Emniyeti                                                 1301 non-null   int8
 186  Korozyona Karşı Koruma                                         1301 non-null   int8
 187  Yerden Isıtmaya Uygunluk                                       1301 non-null   int8
 188  Oda Termostatı İle Çalışma                                     1301 non-null   int8
 189  Alev Modülasyonu                                               1301 non-null   int8
 190  Fan Modülasyonu                                                1301 non-null   int8
 191  Arıza Teşhis Sistemi                                           1301 non-null   int8
 192  Emniyet Termostatı                                             1301 non-null   int8
 193  Emniyet Ventili                                                1301 non-null   int8
 194  Hava Emiş Emniyeti                                             1301 non-null   int8
 195  Alev Sönme Emniyeti                                            1301 non-null   int8
 196  3 Yollu Vana Blokaj Sistemi                                    1301 non-null   int8
 197  Otomatik By-Pass Sistemi                                       1301 non-null   int8
 198  Pompa Anti Blokaj Sistemi                                      1301 non-null   int8
 199  Fincan Kapasitesi                                              20 non-null     float64
 200  Işıklı Uyarı                                                   1301 non-null   int8
 201  Ölçü Kaşığı                                                    1301 non-null   int8
 202  Sesli Uyarı                                                    1301 non-null   int8
 203  Cook Sense Teknolojisi (Pişmeyi Algılama)                      1301 non-null   int8
 204  Anti Spill Teknolojisi (Taşmayı Önleme)                        1301 non-null   int8
 205  Tek Tuşla Kontrol                                              1301 non-null   int8
 206  Fincan Boyutu Seçimi                                           1301 non-null   int8
 207  Su Seviye Göstergesi                                           1301 non-null   int8
 208  Otomatik Kapanma                                               42 non-null     str
 209  Sıcak Tutma Özelliği                                           1301 non-null   int8
 210  Kablo Sarma Yuvası                                             1301 non-null   int8
 211  Pompa Basıncı                                                  21 non-null     str
 212  Çıkarılabilir Su tankı                                         1301 non-null   int8
 213  Motor Gücü                                                   36 non-null     str
 214  İkili Isıtma Sistemi                                           1301 non-null   int8
 215  360° Dönebilen Kablosuz Kullanım                               1301 non-null   int8
 216  Işıklı Açma/Kapama Düğmesi                                     1301 non-null   int8
 217  Kablo Uzunluğu                                                 40 non-null     str
 218  Çıkarılabilir Plakalar                                         1301 non-null   int8

In [256]:
df.sample(10, random_state=42)

,urun_linki,urun_adi,fiyat,enerji_sinifi,favori_sayisi,Product_Group,Main_Category,Subcategory,Derinlik,Genişlik,Yükseklik,Sıcaklık Yükselme Süresi (Saat),Dondurucu Yeri,Elektronik Gösterge,Kontrol Sistemi,Tatil Modu,ProSmart™ Inverter Kompresör,Aydınlatma Tipi,Kapı Yönü Değiştirme,İklim Sınıfı,Ses Seviyesi,Ses Seviyesi Sınıfı,Soğutma Sistemi,Soğutucu Bölme Fanı,EverFresh+ Teknolojisi,Kahvaltılık Çekmecesi,Dondurucu Çekmece Sayısı,Buzluk Tipi,Dondurucu Bölme Aydınlatma Tipi,Sebzelik Adedi,Yıllık Enerji Tüketimi (kWh),Günlük Enerji Tüketimi (kwh/Gün),Günlük enerji tüketimi 16°C (kWh/24h) (EU_2021_EP),Ürün Tipi,Hızlı Soğutma,Hızlı Dondurma Bölmesi,Kapasite,IronFast,Çocuk Kilidi,Deterjan Sistemi,Buhar,Motor Tipi,Tambur Deseni,Elektronik Su Kontrol Sistemi,Gösterge Tipi,Kalan Zaman Göstergesi,Su Taşma Emniyet Sistemi,Dengesiz Yük Kontrolü,Su Kesik İkazı,Programlar,Dinamik Rezistans,Bağlantı,Fonksiyonlar,Ekran Tipi,Paslanmaz Çelik İç Gövde,Otomatik Kapı Açma Özelliği,Bardak Koruma Sistemi,Yarım Yük Yıkama,Yüksekliği Ayarlanabilir Fincan Rafları,Fincan Raf Sayısı,Çatal Kaşık Sepeti,Enerji Tüketimi,Su Tüketimi,Parlatıcı Göstergesi,Tuz Göstergesi,Su Güvenlik Sistemi,Kir Sensörü,Dokunmatik Tuş,Direkt Su Tahliyesi,Su Tankı Dolu Uyarısı,Kondenser Temizleme Uyarısı,Fıltre Temizleme Uyarısı,Ürün Serisi,Fırın Hacmi,Fırın İçi Aydınlatma,Elektrikli Izgara,Ön Kapak Cam Sayısı,Elektroturbo (Fan Destekli Pişirme),Saat Tipi,Fan ve Alt Isıtıcı,Alt Isıtıcı,Fan Destekli Isıtıcı,Küçük Izgara,Kolayca Sökülebilir ve Temizlenebilir Komple İç Cam,Buharlı Pişirme,Doğalgaz,Ocak Yüzeyi,Kahve Beki Adaptörü,Gaz Emniyet Sistemi,3D Pişirme,FitFry Teknolojisi,Ekran Kilidi,Ocak Tipi Ve Göz Sayısı,Ocak Tipi,Bek Şapkası Tipi,Kontrol Tipi ve Yeri,Sol Ön Bölme,Sağ Arka Bölme,Tencere Izgara Tipi,Çerçeve,Sağ Ön Bölme,Sol Arka Bölme,Zamanlayıcı,Sıcaklık Ayarı,Bulaşık Makinesinde Yıkanabilir Aksesuarlar,LCD Ekran,Aşırı Isınma Emniyeti,Davlumbaz Tipi,Maksimum Çekiş Gücü,Yağ Filtre Adedi,Montaj Yüksekliği (mm),Bulaşık Makinesinde Yıkanabilir Filtre,Kontrol Tipi,Lamba Adedi,Yoğun Emiş Gücü,Otomatik Kapanma Özelliği,Kademe Sayısı,Filtre Tipi,Filtre Doluluk Göstergesi,Her Kademe İçin Ses Güçleri (DIN/EN 60704-3 standardına göre),Hava Temizleme Özelliği,Önden Ayarlanablir Arka Ayaklar,Yüksek Bazaya Montaj,İşletim Sistemi,USB Bağlantısı,HDMI,Bluetooth,Arka Kamera,Ön Kamera,İşlemci,Ekran Çözünürlüğü,Mikrofon,GPS,Kulaklık Tipi,NFC,Aux Girişi,Uzaktan Kumanda,İşlemci Çekirdek Sayısı,2.Arka Kamera,Kamera Zoom,Ön Kamera Flaş,Wi-Fi,Marka,Yüz Haritalama,Çift Hatlı,Ses Kayıt,Ürün Ailesi,İşletim Sistemi Versionu,Görüntülü Konuşma,Uyumlu olduğu modeller (MPA),Hızlı Şarj desteği,Type¬C veya Micro USB kablolarıyla şarj edilebilir,Su Geçirmezlik,Soğutma Kapasitesi,Isıtma Kapasitesi (Btu/h),Yıllık Tüketim (kW) Soğuma,Yıllık Tüketim Isıtma (kW),Voltaj,Soğutucu Akışkan,Mevsimsel (SCOP) Enerji Verimi Isıtma (W/W),Mevsimsel (SEER) Enerji Verimi Soğutma (W/W),Akıllı Çalışma Sistemi,Gizli Gösterge,Uyku Mode,Dış Ünite Soğutma Çalışma Aralığı(°C),Dış Ünite Isıtma Çalışma Aralığı(°C),Özel Filtreler,Otomatik Temizleme,Otomatik Hava Yönlendirme (Yukarı-Aşağı),4 Yönlü Otomatik Hava Kontrolü,Nem Alma,Enerji Sınıfı-Isıtma,Kapasite (Isıtma),Anlık Tüketim Göstergesi,Enerji Kontrol,Sessiz Mod,Yumuşak Hava,Auto Swing,Dış Ünite (GxYxD) mm,İç Ünite (GxYxD) mm,Su Tankı Kapasitesi,Devrilme Emniyeti,Titanyum Emaye Kaplamalı Kazan,Yüksek Basınç Emniyet Valfi,Susuz Çalışma Emniyeti,Donma Emniyeti,Korozyona Karşı Koruma,Yerden Isıtmaya Uygunluk,Oda Termostatı İle Çalışma,Alev Modülasyonu,Fan Modülasyonu,Arıza Teşhis Sistemi,Emniyet Termostatı,Emniyet Ventili,Hava Emiş Emniyeti,Alev Sönme Emniyeti,3 Yollu Vana Blokaj Sistemi,Otomatik By-Pass Sistemi,Pompa Anti Blokaj Sistemi,Fincan Kapasitesi,Işıklı Uyarı,Ölçü Kaşığı,Sesli Uyarı,Cook Sense Teknolojisi (Pişmeyi Algılama),Anti Spill Teknolojisi (Taşmayı Önleme),Tek Tuşla Kontrol,Fincan Boyutu Seçimi,Su Seviye Göstergesi,Otomatik Kapanma,Sıcak Tutma Özelliği,Kablo Sarma Yuvası,Pompa Basıncı,Çıkarılabilir Su tankı,Motor Gücü,İkili Isıtma Sistemi,360° Dönebilen Kablosuz Kullanım,Işıklı Açma/Kapama Düğmesi,Kablo Uzunluğu,Çıkarılabilir Plakalar,Kilitleme Mandalı,Yağ Toplama Haznesi,Açma/Kapama Düğmesi,Sıcaklık Kontrolü,Çalışma Göstergesi,Maksimum Sıcaklık Derecesi,Minimum Sıcaklık Derecesi (°C),Iyon Özelliği,Saçları Pürüzsüz ve Kıvırcık Yapma,Ürün Kilidi,Sıcaklık Ayarı Kilidi,LED Ekran,Hız Ayarı,Difüzör Başlığı,Çıkarılabilir hava giriş ızgarası,Cool Shot,Fön Başlığı,Soğuk Ayarı,Seramik Izgara,Asma Halkası,Vigo Difüzör Başlık,Toz Torbası Kapasitesi,360° Derece Dönebilen Hortum,Taşıma sapı,Kullanım tipi,Döşeme/Koltuk Fırçası,Dar Ağızlı Uç,Duvara Monte Edilebilen Şarj aleti,Turbo Fırça,Paspas Özelliği,Şarj istasyonu,Led Fırça,Yüksek Performanslı Elektrikli Fırça,Buharsız Ütüleme,Şok Buhar Özelliği,Dikey Ütüleme,Turbo Özelliği,Doğrayıcı,Paslanmaz Çelik Çırpıcı,Paslanmaz Çelik Blender,Paslanmaz Çelik Bıçak,Doğrayıcı Kabı,Ölçü Kabı,Güvenlik Kilidi,Renk_Siyah,Renk_Gri,Renk_Mavi,Renk_Pembe,Renk_Beyaz,Renk_Kırmızı,Renk_Sarı,Renk_Yeşil,Renk_Turuncu,Renk_Bej,Renk_Mor,Renk_Kahverengi,Agirlik (kg),Sarj_Suresi_dk,Guc (W),Su_Kapasitesi (L),RAM (GB),Depolama (GB),Batarya (mAh),Sikma_Devri,Program_Sayisi,Fonksiyon_Sayisi,Ekran_Boyutu_Inch
478,https://www.beko.com.tr/kulaklik/samsung-typec...,Samsung TypeC Kablolu Kulaklık-Siyah Kulaklık,599.00,NaN,1,Kulaklik,Elektronik,Ses& Görüntü Sistemleri,7.00,9.00,2.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1.00,0,Kablolu Kulak İçi Kulaklık,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
722,https://www.beko.com.tr/cep-telefonu-aksesuarl...,UGREEN USB-C 60W Örgülü Kablo Syh 1M Cep Telef...,379.00,NaN,0,Cep Telefonu Aksesuarlari,Elektronik,Cep Telefonu,2.00,4.00,5.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
312,https://www.beko.com.tr/ankastre-mikrodalgalar...,BMM 2020 I Ankastre Mikrodalgalar,16420.00,NaN,22,Ankastre Mikrodalgalar,Diğer,Diğer,37.70,47.00,28.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ankastre,0,0,NaN,0,1,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,['9'],NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,1,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,15.50,NaN,1200.00,NaN,NaN,NaN,NaN,NaN,0,1,NaN
661,https://www.beko.com.tr/android-telefon-modell...,Xiaomi Redmi Note 14 Pro 12/512GB Siyah Androi...,20999.00,NaN,1,Android Telefon Modelleri,Elektronik,Cep Telefonu,17.00,6.00,5.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,AMOLED,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,0,0,1,NaN,32MP,NaN,1080 x 2400,NaN,1,NaN,0,0,0,8.00,1,NaN,0,1,Xiaomi,1,1,0,NaN,NaN,1,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,12.00,512.00,5500000.00,NaN,0,0,6.67
969,https://www.beko.com.tr/espresso-makinesi/nesp...,Nespresso Aeroccino 4 Süt Köpürtücü Espresso M...,5999.00,NaN,0,Espresso Makinesi,Küçük Ev Aletleri,Kahve Makinesi,10.00,10.00,17.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,220-240,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
115,https://www.beko.com.tr/4-programli-bulasik-ma...,BM 4144 OK A 4 Programlı Bulaşık Makinesi,25979.00,D,44,4 Programli Bulasik Makinesi,Beyaz Eşya,Bulaşık Makinesi,60.00,60.00,85.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,47.00,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Solo,0,0,14.00,0,1,0,NaN,Standart,NaN,0,NaN,0,0,0,0,"['Makine Yıkama', '35-50-65-70', '190 dk']",0,NaN,"['HijyenMax', 'Ekstra Parlaklık/ Kurutma Fonks...",LED,1,1,1,1,1,2.00,Hareketli,0.849 kWh,11.50,1,1,Taşma Emniyeti,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,43.40,NaN,2100.00,NaN,NaN,NaN,NaN,NaN,3,6,NaN
814,https://www.beko.com.tr/akilli-saat/apple-watc...,Apple Watch SE GPS 40mm Y. Işığı SB S/M Akıllı...,10999.00,NaN,0,Akilli Saat,Elektronik,Giyilebilir Teknoloji,1.00,3.00,4.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,50 metreye kadar su geçirmezlik.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
1262,https://www.beko.com.tr/el-blender/hbs-5410-ka...,HBS 5410 El Blender,3349.00,NaN,13,El Blender,Küçük Ev Aletleri,Karıştırıcı& Doğrayıcı,13.00,13.00,36.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,1,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,1,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1.43,NaN,1500.00,NaN,NaN,NaN,NaN,NaN,0,0,NaN
1103,https://www.beko.com.tr/yaslanma-karsiti-bakim...,Foreo FAQ 302 Black Yaşlanma Karşıtı Bakım,25999.00,NaN,1,Yaslanma Karsiti Bakim,Diğer,Diğer,5.00,12.00,16.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,0,NaN,0,0,0,0,NaN,0,NaN,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
101,https://www.beko.com.tr/elite-serisi-solo-bula...,B 710 bc Elite Serisi Solo Bulaşık Makinesi,28079.00,B,5,Elite Serisi Solo Bulasik Makinesi,Beyaz Eşya,Bulaşık Makinesi,60.00,60.00,85.00,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN,46.00,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Solo,0,0,14.00,0,1,0,NaN,Standart,NaN,0,NaN,0,0,0,0,"[""Hızlı 49'"", '35-40-50-65-70', 'Hassas 40', '...",0,Wi-Fi + BLE,"['HomeWhiz', 'HijyenMax (App)', 'Extra kurutma...",LED,1,1,0,1,1,2.00,Hareketli,0.645 kWh,10.90,1,1,Taşma Emniyeti,0,0,0,0,0,0,NaN,NaN,0,0,NaN,0,NaN,0,0,0,0,0,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,0,NaN,0,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,0,NaN,0,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,NaN,0,NaN,0,0,0,NaN,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,50.10,NaN,2100.00,NaN,NaN,NaN,NaN,NaN,4,4,NaN

# Şikayet Var

In [258]:
df = pd.read_csv("../web-scraping-data/data/raw/sikayet-var/sikayet_var_yorumlar.csv")
df.head()

,Yorum_Linki,Sikayet_Basligi,Sikayet,Sikayet_Tarihi,Goruntuleme_Sayisi,Destek_Sayisi,Kategori,Urun_Adi,Sirket_Cevabi,Gelisme_Tarih,Gelisme_Yorum,Cevap_Tarihi,Cevap_Mesaji,Cevaba_Cevap_1_Tarih,Cevaba_Cevap_1_Mesaj,Cevaba_Cevap_2_Tarih,Cevaba_Cevap_2_Mesaj,Cevaba_Cevap_3_Tarih,Cevaba_Cevap_3_Mesaj,Cevaba_Cevap_4_Tarih,Cevaba_Cevap_4_Mesaj,Cevaba_Cevap_5_Tarih,Cevaba_Cevap_5_Mesaj
0,https://www.sikayetvar.com/beko/ic-haznedeki-p...,İç Haznedeki Paslanma Sorunu TekrarlayanBekoFı...,2025 yılı Haziran ayında Esenyurt Beko bayisin...,28 Nisan 14:56,160,0,Ankastre Fırın,BFC 631,1,NaN,NaN,28 Nisan 15:49,"Sevgili müşterimiz ,\n\nÖncelikle Firmamıza gö...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.sikayetvar.com/beko/beko-magazasi-...,"BekoMağazası Büyük Ocağı Geri Almayı Reddetti,...",Kocaeli Gebze’de bulunan Beko Piranlar şubesin...,14 Nisan 21:12,225,0,Ocak,BFC 631,1,NaN,NaN,15 Nisan 11:55,"Sevgili müşterimiz ,\n\nÖncelikle Firmamıza gö...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.sikayetvar.com/beko/beko-fitfry-fi...,BekoFitfry Fırının Yanık Lekeleri Temizlenmiyor,Beko Fitfry bfc 631 s fırını 8 Kasım 2025 tari...,01 Nisan 14:58,379,0,Fırın,BFC 631,1,NaN,NaN,01 Nisan 17:54,"Sevgili müşterimiz ,\n\nÖncelikle Firmamıza gö...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.sikayetvar.com/beko/teslim-edilmey...,Teslim Edilmeyen Ürünler Ve Cevapsız Telefon A...,Beko markasının Sultanbeyli ilçesinde bulunan ...,02 Mart 00:48,854,0,Ankastre Fırın,BFC 631,1,NaN,NaN,02 Mart 14:40,"Sevgili müşterimiz ,\n\nÖncelikle Firmamıza gö...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.sikayetvar.com/beko/beko-ankastre-...,BekoAnkastre Fırında Özellik Eksikliği Ve Pişi...,Beko marka ankastre set kapsamında aldığım fır...,04 Şubat 00:04,1.114,1,Ankastre Fırın,BFC 631,1,NaN,NaN,04 Şubat 14:17,"Sevgili müşterimiz ,\n\nÖncelikle Firmamıza gö...",05 Şubat 20:34,05/02 Tarihinde fırın için teknisyeniniz geldi...,26 Şubat 17:01,Tüketici olarak Beko marka ürünmü almak asla.....,NaN,NaN,NaN,NaN,NaN,NaN

In [259]:
df.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 12367 entries, 0 to 12366
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Yorum_Linki           12367 non-null  str
 1   Sikayet_Basligi       12367 non-null  str
 2   Sikayet               12367 non-null  str
 3   Sikayet_Tarihi        12367 non-null  str
 4   Goruntuleme_Sayisi    12367 non-null  str
 5   Destek_Sayisi         12367 non-null  int64
 6   Kategori              12367 non-null  str
 7   Urun_Adi              12367 non-null  str
 8   Sirket_Cevabi         12367 non-null  int64
 9   Gelisme_Tarih         1476 non-null   str
 10  Gelisme_Yorum         1476 non-null   str
 11  Cevap_Tarihi          11751 non-null  str
 12  Cevap_Mesaji          11751 non-null  str
 13  Cevaba_Cevap_1_Tarih  5683 non-null   str
 14  Cevaba_Cevap_1_Mesaj  5683 non-null   str
 15  Cevaba_Cevap_2_Tarih  1842 non-null   str
 16  Cevaba_Cevap_2_Mesaj  1842 non-null   str
 17  Cevaba_Cevap_3_Tarih  655 non-null    str
 18  Cevaba_Cevap_3_Mesaj  655 non-null    str
 19  Cevaba_Cevap_4_Tarih  265 non-null    str
 20  Cevaba_Cevap_4_Mesaj  265 non-null    str
 21  Cevaba_Cevap_5_Tarih  113 non-null    str
 22  Cevaba_Cevap_5_Mesaj  113 non-null    str
dtypes: int64(2), str(21)
memory usage: 22.7 MB

In [ ]:

def sayi_temizle(val):
    if pd.isna(val): 
        return 0
    
    # Metni standartlaştır: küçük harf, binlik ayracı (nokta) sil ve boşlukları at
    s = str(val).lower().replace('.', '').strip()
    
    # 1. Hatanın Kaynağı: '-' veya boş metin kontrolü
    if s == '-' or s == '' or not any(char.isdigit() for char in s):
        return 0
        
    # 2. Binlik Kısaltma Kontrolü (Örn: 1.2b veya 5k)
    # İşlem: $1.2b \rightarrow 1.2 \times 1000 = 1200$
    if 'b' in s or 'k' in s:
        try:
            temiz_s = s.replace('b', '').replace('k', '').replace(',', '.')
            return int(float(temiz_s) * 1000)
        except:
            return 0
            
    # 3. Standart Sayıya Dönüştürme
    try:
        # Virgül varsa noktaya çevirip float üzerinden int'e geçmek en garantisidir
        return int(float(s.replace(',', '.')))
    except ValueError:
        return 0

# --- VERİ TİPİ DÖNÜŞÜM MERKEZİ ---

# 1. Görüntüleme Sayısı (Hata Onarılmış)
if 'Goruntuleme_Sayisi' in df.columns:
    df['Goruntuleme_Sayisi'] = df['Goruntuleme_Sayisi'].apply(sayi_temizle)

# 2. Tarih Sütunlarını Optimize Et
tarih_sutunlari = [
    'Sikayet_Tarihi', 'Gelisme_Tarih', 'Cevap_Tarihi', 
    'Cevaba_Cevap_1_Tarih', 'Cevaba_Cevap_2_Tarih', 
    'Cevaba_Cevap_3_Tarih', 'Cevaba_Cevap_4_Tarih', 'Cevaba_Cevap_5_Tarih'
]

for col in tarih_sutunlari:
    if col in df.columns:
        # Hatalı tarihleri pas geçmek için errors='coerce' kullanıyoruz
        df[col] = pd.to_datetime(df[col], errors='coerce')

# 3. Kategori ve Ürün Adı (Bellek Tasarrufu)
# 12.367 satırda bu sütunları 'category' yapmak RAM kullanımını %50 düşürür
for col in ['Kategori', 'Urun_Adi']:
    if col in df.columns:
        df[col] = df[col].astype('category')

# 4. Şirket Cevabı (1/0 ise En Küçük Tamsayı Tipi)
if 'Sirket_Cevabi' in df.columns:
    df['Sirket_Cevabi'] = df['Sirket_Cevabi'].astype('int8')

print("Veri tipleri başarıyla güncellendi! Hatalı karakterler temizlendi.")

Veri tipleri başarıyla güncellendi! Hatalı karakterler temizlendi.

In [262]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12367 entries, 0 to 12366
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Yorum_Linki           12367 non-null  str
 1   Sikayet_Basligi       12367 non-null  str
 2   Sikayet               12367 non-null  str
 3   Sikayet_Tarihi        0 non-null      datetime64[s]
 4   Goruntuleme_Sayisi    12367 non-null  int64
 5   Destek_Sayisi         12367 non-null  int64
 6   Kategori              12367 non-null  category
 7   Urun_Adi              12367 non-null  category
 8   Sirket_Cevabi         12367 non-null  int8
 9   Gelisme_Tarih         0 non-null      datetime64[s]
 10  Gelisme_Yorum         1476 non-null   str
 11  Cevap_Tarihi          0 non-null      datetime64[s]
 12  Cevap_Mesaji          11751 non-null  str
 13  Cevaba_Cevap_1_Tarih  0 non-null      datetime64[s]
 14  Cevaba_Cevap_1_Mesaj  5683 non-null   str
 15  Cevaba_Cevap_2_Tarih  0 non-null      datetime64[s]
 16  Cevaba_Cevap_2_Mesaj  1842 non-null   str
 17  Cevaba_Cevap_3_Tarih  0 non-null      datetime64[s]
 18  Cevaba_Cevap_3_Mesaj  655 non-null    str
 19  Cevaba_Cevap_4_Tarih  0 non-null      datetime64[s]
 20  Cevaba_Cevap_4_Mesaj  265 non-null    str
 21  Cevaba_Cevap_5_Tarih  0 non-null      datetime64[s]
 22  Cevaba_Cevap_5_Mesaj  113 non-null    str
dtypes: category(2), datetime64[s](8), int64(2), int8(1), str(10)
memory usage: 21.5 MB